### ISSUE TITLE
Convert A_TRUEHD to EAC3

### ISSUE THREAD

**Issue by traxinv** [mdhiggins/sickbeard_mp4_automator#1001]
At the moment mp4_automator is ignoring all audio tracks that are encoded using the new Dolby Atmos or TrueHD standard:

```
Format : | TrueHD
Format profile : | TrueHD+Atmos / TrueHD
Codec ID : | A_TRUEHD
Channel(s) : | Object Based / 8 channels
```

As far as I can determine ATMOS (Dolby TrueHD) is NOT supported in mp4 containers, from the sample files that I have been able to find on Dolby's website ([Here](https://www.dolby.com/us/en/guide/dolby-atmos-trailers.html)) they use MP4 containers with the audio encoded in "eac3":

```
Format : | E-AC-3
Format/Info : | Audio Coding 3
Format settings, Endianness : Big
Codec ID : | ec-3
```

Would it be possible to convert TrueHD to eac3 ("Dolby Digital Plus"), it will still not be perfect (since FFMPEG is still only limited to 6 channels) but the audio quality should be better.

I managed to get this working using the following command to ffmpeg:
`ffmpeg.exe -i input.mkv -c:v copy -c:a eac3 output.mp4`

```
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (truehd (native) -> eac3 (native))
  Stream #0:3 -> #0:2 (copy)
```
encoder log:
![image](https://user-images.githubusercontent.com/3995322/56470132-e68b0380-6442-11e9-97a9-30b8eb7331a6.png)

**Comment by traxinv** [comment]
Having played around with the settings the issue is not really related to EAC3 as your code perfectly passes the parameters are required, but rather that the code does not recognise the TrueHD format which we may need to add.

**Comment by mdhiggins** [comment]
This is because most releases that include TrueHD streams also will include the EAC3 audio track as the next available track, so the default behavior is to just ignore the TrueHD stream and use the included EAC3 track (often the next track). If you’re using sources that don’t include that I just pushed an update that adds an option to autoProcess.ini (ignore_truehd) that makes this behavior optional.

As far as the channels, you can specify a max channel of 6 already in the options.

Let me know if that helps

From: traxinv
Sent: Sunday, April 21, 2019 8:39 AM
To: mdhiggins/sickbeard_mp4_automator
Cc: Subscribed
Subject: [mdhiggins/sickbeard_mp4_automator] Convert A_TRUEHD to EAC3 (#1001)

At the moment mp4_automator is ignoring all audio tracks that are encoded using the new Dolby Atmos or TrueHD standard:
Format : | TrueHD
Format profile : | TrueHD+Atmos / TrueHD
Codec ID : | A_TRUEHD
Channel(s) : | Object Based / 8 channels
as far as I can determine ATMOS is NOT supported in mp4 containers, from the sample files that I have been able to find on doly's website they use MP4 containers with the audio encoded in "eac3":
Format : | E-AC-3
Format/Info : | Audio Coding 3
Format settings, Endianness : Big
Codec ID : | ec-3
Would it be possible to convert TrueHD to eac3, it will still not be perfect but the audio quality should be better.
I managed to get this working using the following command to ffmpeg:
ffmpeg.exe -i input.mkv copy -c:v copy -c:a eac3 output.mp4
Stream mapping:
Stream #0:0 -> #0:0 (copy)
Stream #0:1 -> #0:1 (truehd (native) -> eac3 (native))
Stream #0:3 -> #0:2 (copy)
encoder log:

**Comment by traxinv** [comment]
HI @mdhiggins 

Thanks for replying so quickly much appreciated. 

Generally you are correct there usually is a second track that has the audio in a "lower" codec, but i am encountering rather a few that don't have the second track so the option would be greatly appreciated. 

Sorry i missed the max channels setting in the ini file, i have updated it now, will do a pull now and see if all is solved.

Thanks again.

**Comment by traxinv** [comment]
absolutely perfect, thanks so much:

 ```
   "audio": {
        "0": {
            "map": 1,
            "language": "eng",
            "channels": 2,
            "codec": "aac",
            "disposition": "default",
            "bitrate": 256,
            "filter": null
        },
        "1": {
            "map": 1,
            "language": "eng",
            "channels": 6,
            "codec": "eac3",
            "disposition": "none",
            "bitrate": 1536,
            "filter": null
        }
```

**Comment by traxinv** [comment]
Fixed by commit: https://github.com/mdhiggins/sickbeard_mp4_automator/commit/c29bde3b2b4cfc194e5bb3a868b248acd2780d89
