### ISSUE TITLE
No AC3 audio stream and low audio bitrate

### ISSUE THREAD

**Issue by kevindd992002** [mdhiggins/sickbeard_mp4_automator#1013]
I'm using the sonarr-rma and radarr-rma containers and I just tested my first mp4 conversion using them. Here's my autoProcess.ini contents: https://pastebin.com/Mn6Mib89

When I use MediaInfo for the converted file, here's what I get:

![image](https://user-images.githubusercontent.com/3907957/58763203-7798e280-858a-11e9-9ae0-7da9346b30d4.png)

I've been a long time user of your script in Windows and usually I also get an AC3 audio stream and the bitrate is higher thank 126Kbps (because I set it to 256 in the ini file). Why am I experiencing a difference now that I'm all doing this in Linux?

Will your script ever add an audio stream that's not present? Sorry, I'm not an expert with ffmpeg. And is it generally a good idea to always move the iOS audio (AAC stereo) as the last audio stream?

**Comment by mdhiggins** [comment]
It will never add an audio stream that's not present, there's no source of audio streams in existence to check against

In situations where your source audio stream only has 2 channels it doesn't bother to create a duplicate 2 channel AC3 which is the way the iOS audio track behavior has been for years. Looking at the log for this file that you posted on the other issue it appears it already came with a stereo AAC track so this seems to be the correct behavior

**Comment by kevindd992002** [comment]
I see. So if my understanding is correct, the video and audio codecs parameters in the ini file are like filters as to which codecs will be "allowed" to be either copied or converted, correct?

When does it copy as opposed to convert it?

**Comment by mdhiggins** [comment]
Answer to that is somewhat complicated, as its based on a number of factors and conditions that are dynamic
Essentially it tries to copy whenever it can, as copying preserves quality of source 100% and uses no CPU power, converting always results in some quality loss regardless of settings and increases CPU usage and time to complete a file. Once you configure which codecs are allowed it will try to copy whenever possible. As you define more parameters in autoProcess (such as channels, bitrate, etc) you gradually reduce your chances of getting a 'copy' just because you're being pickier about what you want in the final result

**Comment by kevindd992002** [comment]
Ok, it's starting to make sense now. Thanks for the explanation.

As for 4K content, does ffmpeg with your script support handling it?

**Comment by mdhiggins** [comment]
Yes

**Comment by kevindd992002** [comment]
Ok. I'll have to fiddle with it after I get a UHD TV then. Thanks!
