### ISSUE TITLE
Allow to set default audio and subtitles

### ISSUE THREAD

**Issue by Nottt** [mdhiggins/sickbeard_mp4_automator#1038]
It'd be nice if there was a way to set the default audio/subtitles in the mp4 to a desired language...

**Comment by uchagani** [comment]
from the docs:

audio-codec = set your desired audio codecs. May specify multiple comma separated values (ex: ac3, aac). **The first value specified will be the default conversion choice when an undesired codec is encountered**; any codecs specified here will be remuxed/copied rather than converted.

**Comment by mdhiggins** [comment]
This is already done

**Comment by Nottt** [comment]
This is not what I meant, but yes, I noticed that `audio-default-language = por` would make the `por` audio have the default flag in the converted files.

It'd be nice to add that to the documentation tho
