### ISSUE TITLE
Running mp4 in a separate container

### ISSUE THREAD

**Issue by promo76** [mdhiggins/sickbeard_mp4_automator#1048]
Hello,

I am currently running sabnzbd, sonarr and radarr in containers on synology docker. I installed the prerequisite packages in the sabnzbd container, however if I update the container I would have to install them again. Can I run mp4 in it's own container and point the sabnzbd container to the mp4 container?

Thank you!

**Comment by kevindd992002** [comment]
I would really want to know anything about this. Currently, mdhiggins has docker containers for sma embedded in sonarr and radarr, which meand the post processing happens in radaar and sonarr but that has a lot of disadvantages, at least for my use case. Post processing with sma is more optimized when done from the download clients instead of the media managers.

**Comment by promo76** [comment]
I was thinking that it could be possible if you link the containers. I haven't tried it yet. I want to run the conversion in a separate container and install all the prerequisites there. Would mapping the ffmpeg and ffprobe path in the ini file to the mp4 container mean that the conversion would run in that environment or in the sabnzbd container? That is what I can't figure out. I guess the only way to find out is to try it. I was hoping mdhiggins would give me some input before I go through the hassle of creating a separate container.

**Comment by mdhiggins** [comment]
I have docker containers but they use completed download handling and do the conversion and tagging once as the final step. Disadvantage here as opposed to doing the conversion between the download step and the sonarr/radarr notification step is that you conversion takes place potentially in the final destination of the file which isn't desirable for some. Its not more or less optimized though, the same process is conducted either way but instead of breaking things into 2 steps its done as a single step (more optimized some might say) and lets the download handling be handled by the media managers. This removes the step of needing the notification scripts which have become the legacy method of handling things left over from the sickbeard days.

I don't have containers created for the alternative solutions though you could see how I handle the installation and setup of the SMA script in the docker containers I did create and create something similar for your specific use cases. 

There are a lot of advantages with regards to reliability of communication and monitoring by transitioning to the completed download handling approach so this may not be a bad idea if there's no reason that prevents you from doing your conversion at the final step.

**Comment by promo76** [comment]
Hello mdhiggins,

Thank you for your reply. The issue is not when the conversion takes place, but where the conversion process runs. If you have the prereqs installed in the sabnzbd conatiner or the radarr conatiner, you run into the same issue. On an image update you will have to reinstall the prereqs. 
I want to know if I can run mp4 in a separate container and then configure the sabpostprocess.py script to run the conversion in that container instead of the sabnzbd container.

**Comment by mdhiggins** [comment]
So I'm not sure if there's a way to have an isolated container that does everything, I haven't been able to create such a thing but my experience with docker is a bit limited

That being said, I have 2 docker containers for Sonarr/Radarr that as part of their installation process download and install all the prereqs and set them up in a virtual python environment so if you update the image everything is reinstalled as part of the build process, which sounds like it would address the issue you're having

https://cloud.docker.com/u/mdhiggins/repository/docker/mdhiggins/radarr-sma
https://cloud.docker.com/u/mdhiggins/repository/docker/mdhiggins/sonarr-sma

**Comment by kevindd992002** [comment]
@mdhiggins I understand the advantages of having post-processing done in your sonarr and radarr containers. Everything works well when converting a handful of media episodes but everything starts to bug down when, say, full seasons are downloaded especially when the conversion of one media file takes a while (1 hour plus, depending on your sma configuration). 

As you know, I have an existing ticket [here ](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1022) that explains what I'm experiencing. Basically, when a long conversion happens the "Check for Finished Downloads" task in Sonarr/Radarr gets stuck until that conversion finishes. This creates a bottleneck for other files that should've been post-processed in the first place. I did not have this problem when I was using Windows and had post processing delegated to the download client instead of the media managers doing it.

**Comment by mdhiggins** [comment]
You could probably just wrap the python command in a shell script with the & option so sonarr/radarr don't need to wait for it to finish to move on
`/usr/local/bin/sma/env/bin/python3 /usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py "%@" &` 
Something like that would probably work

**Comment by kevindd992002** [comment]
Hmm, that's interesting. I'm a Linux beginner though. If I understood that correctly, you would always need to do this everytime the containers get updated, correct? In that case, would there be a chance you can implement this in your containers if it makes sense to you?

**Comment by mdhiggins** [comment]
If that works, just store the script somewhere and mount that location in your docker image, no need for me to modify the docker container and it should persist fine

**Comment by kevindd992002** [comment]
> 
> 
> If that works, just store the script somewhere and mount that location in your docker image, no need for me to modify the docker container and it should persist fine

Ok, that makes sense. So this is the exact content of the shell script, right?

`/usr/local/bin/sma/env/bin/python3 /usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py "%@" &`

And the file should have a .sh extension and then have Sonarr/Radarr use that script instead. Do you see any disadvantages to this though? If I do this, will all files be converted in parallel then using the same Sonarr/Radarr-sma containers?

**Comment by mdhiggins** [comment]
Might work, it was just meant as a sample so you may need to tweak it. The `&` symbol should allow for the program to run without waiting for close which should in turn allow sonarr/radarr to move on and allow conversions to continue in parallel
The rest of the paths you'll need to modify for your setup, those examples were setup using my server but may not reflect yours
Just make sure to include the `"%@"` to pass all the command line arguments

**Comment by kevindd992002** [comment]
Got it. Yes, I'm using the same paths as the paths in your containers so that should work. I'll test this and will post back if it's a success.

**Comment by kevindd992002** [comment]
I'm trying to research regarding shell scripts, and all I see is to include `"$@"` to pass all command line arguments. Is there a difference between `"%@"` and `"$@"`?

**Comment by mdhiggins** [comment]
Whoops yeah it’s supposed to be `"$@"` my mistake

**Comment by kevindd992002** [comment]
Right, no worries. And based on how I understand the usage of `"$@"`, the shell script wrapper should contain this:

`#!/bin/sh
/usr/local/bin/sma/env/bin/python3 "%@" &`

And then put the path to the shell script in Sonarr/Radarr's custom script path field and the argument field will still have:

/usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py

In this way, the argument to the shell script will all be passed to where the `$@` is. Does that make sense?

**Comment by mdhiggins** [comment]
Yeah, that should work fine, except you still have the % symbol in the example you posted. I think either way should work. I will say that I believe the next version of Sonarr/Radarr they are removing the argument field so the solution I posted above where you keep the script path in the shell command might be more future proof but either way should work in the current version

**Comment by kevindd992002** [comment]
Oops, I just edited that. 

Yes, I read about the argument field being deprecated. I understand that putting everything (python command plus argument) all wrapped in one shell script is more future proofed but what is the use of the $@ if you won't put an argument to the shell script itself? Sorry if I'm missing something.

**Comment by mdhiggins** [comment]
It just forwards any command line arguments that sonarr/radarr might be trying to pass essentially. As of now I think they've mostly transitioned away from using any arguments and instead use environment variables so it should be ok without it but its another future proofing option

**Comment by kevindd992002** [comment]
Ok, that makes sense. I'll try it and report back.

**Comment by kevindd992002** [comment]
It didn't work. I have this in postSonarr.sh:

`
#!/bin/sh
/usr/local/bin/sma/env/bin/python3 /usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py "$@" &
`

Then pointed Sonarr/Radarr to that shell script (/usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.sh) and then ran `tail -f /var/log/sickbeard_mp4_automator/index.log` inside the Sonarr-SMA docker container and there were no logs. 

Any ideas?

**Comment by mdhiggins** [comment]
Check sonar logs and see if there’s an error
Might be a permissions thing, did you give your script execute permissions?

**Comment by kevindd992002** [comment]
The Sonarr debug logs doesn't show anything too. It's as if it doesn't process the "connector" when the shell script is used. And yes, I made sure it has execute permissions. For reference:

-rwxrwxr-x 1 abc  users   109 Aug 20 23:00 postSonarr.sh

**Comment by mdhiggins** [comment]
Does running the shell script on your own do anything?

**Comment by kevindd992002** [comment]
I just tried now and it does this:

> root@b04083979a86:/# sh /usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.sh
> root@b04083979a86:/# 2019-08-21 22:41:54 - SonarrPostConversion - INFO - Sonarr extra script post processing started.
> 2019-08-21 22:41:54 - readSettings - INFO - /usr/local/bin/sma/env/bin/python3
> Traceback (most recent call last):
>   File "/usr/local/bin/sma/sickbeard_mp4_automator/postSonarr.py", line 38, in <module>
>     tvdb_id = int(os.environ.get('sonarr_series_tvdbid'))
> TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
> 

So I'm guessing it's working. I guess I was just missing the sh/bash/. notation in the Sonarr connector path field as I only have the direct path to the sh there.

**Comment by kevindd992002** [comment]
But I shouldn't have to put in those notations if it's set as an executable, right?

**Comment by mdhiggins** [comment]
Looks like its working, the error above makes sense from manual execution since it won't have the sonarr specific environment variables

As far as sonarr executing, I'm not sure. It kind of depends on how sonarr handles execution. I would  think not by I may be wrong

**Comment by kevindd992002** [comment]
Fixed it. I made the script in Windows so it needed to be converted to Unix format. Sometimes, solutions to weird problems are very easy when you stumble upon them :)

**Comment by mdhiggins** [comment]
So I guess then back to the original question. Does this solution actually work to allow you to batch process multiple files without waiting

**Comment by kevindd992002** [comment]
I have to test that out tomorrow. I'll download a whole season and monitor if the issue happens.

**Comment by kevindd992002** [comment]
I just tested this and nothing has change in the behavior when multiple files are processed. The "Check for Finished Downloads" task is still stuck as long as there's a conversion happening in the background. You can easily tell this because this task's interval is set to 1 minute and when there's a file being converted the "last execution time" increases as well (until it resets when the conversion finishes).

**Comment by mdhiggins** [comment]
Post your final shell script please

**Comment by kevindd992002** [comment]
It's the one I posted here:

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1048#issuecomment-523481040

**Comment by mdhiggins** [comment]
See if any of this info provides a solution

https://askubuntu.com/questions/88091/how-to-run-a-shell-script-in-background#88092

**Comment by kevindd992002** [comment]
So do I need to remove the "&" inside the shell script and append it in the Sonarr command line field?

**Comment by kevindd992002** [comment]
@mdhiggins, do you have any more ideas?

**Comment by kevindd992002** [comment]
@mdhiggins This is still an issue. Do you have any ideas? As long as there's a conversion happening in Sonarr, everything "seems" to be stuck but in the background it just waits for the conversion to finish before things in the Sonarr gui gets updated.

**Comment by mdhiggins** [comment]
That is the default and expected behavior at this current time, sonarr waits to begin processing the next file til its post processing is complete. I was just suggesting possible work around solutions for your particular use case, so nothing is actually broken

Did you try running the command with `nohup`?
