### ISSUE TITLE
Converted file is not being moved from sabnzbd complete folder to media folder

### ISSUE THREAD

**Issue by gouthamravee** [mdhiggins/sickbeard_mp4_automator#1057]
I have setup the script on sabnzbd and radarr using the directions on the homepage. The file is converted and the script seems to run properly. But the file isn't renamed or moved after conversion finishes. 

I'm seeing this error in Sab,  /usr/share/sabnzbdplus/admin/postproc2.sab failed with error <type 'exceptions.ValueError'>

**Comment by uchagani** [comment]
radarr is what actually moves and renames the file.  Have you ran the `test` in radarr?  

<img width="790" alt="image" src="https://user-images.githubusercontent.com/1053584/64922965-f533d780-d7a2-11e9-8350-bb2472d9766b.png">

If that is successful, then the problem most likely is in radarr's ability to parse the downloaded file's name and match it to a movie in your added list.

**Comment by 1stian** [comment]
Try to enable debug logging in radarr/sonarr. Then you'll see if it can access the file correctly.

**Comment by mdhiggins** [comment]
There are two ways the script works, with completed download handling and without.

With completed download handling:
```
Sonarr fetches -> SAB Downloads -> Sonarr monitors (waits for download to complete) <- Sonarr Processes (renames and moves) -> postSonarr.py (converts and tags)
```

Without completed download handling:
```
Sonarr fetches -> SAB Downloads -> SABPostProcess.py converts -> SABPostProcess.py notifies sonarr a download is read -> Sonarr Processes (renames and moves) -> postSonarr.py (only tags as conversion is done)
```

Assumed you're not using completed download handling, if SABPostProcess.py fails with an error, Sonarr will not get the notification and will never process, rename, or move the file, and postSonarr will never run

If you're having an error in SAB that probably means something there is going on. SAB should have more detailed logs about what is happening. Usually if its not getting passed back its because you don't have your Sonarr API settings configured correctly in autoProcess.ini as this is how the notification is sent (via the API) to tell Sonarr a download needs to be processed and where that download is.
