### ISSUE TITLE
radarr-sma:  Warn ImportApprovedMovie Couldn't import movie

### ISSUE THREAD

**Issue by samcro1967** [mdhiggins/sickbeard_mp4_automator#1082]
I am running SABnzbd, radarr-sma, and sonarr-sma all in docker containers. Sonarr seems to be working fine, but radarr-sma does not seem to be executing. Radarr makes the call to SABnzbd and the movie downloads, but I think it is failing to import and then does not call sma. Testing the custom script from the radarr UI works fine. I am using the same settings as in sonarr except calling the postradarr script instead.

From bash within the container, I can get to the config, downloads, and movies folders and see files so I don't think it a volume mount or permissions issue. Not sure what to try next.

Radarr logs
[radarr.4.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/3814583/radarr.4.txt)

Radarr-sma logs
[radarr-sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/3814585/radarr-sma.log)

![image](https://user-images.githubusercontent.com/2319445/68301983-b0237780-0066-11ea-9b32-1345ed422a5b.png)

**Comment by mdhiggins** [comment]
My best guess is that there is some parity issue between the directories of your containers as things transition from NZBget to Radarr.
From within the radarr container, does /movies/The.Kitchen.2019.720p.BluRay.DD5.1.x264-iFT/bzhnq1jdX3Y3Gkyf4KkQe9pQV3x9h2EAY5.mkv actually exist? Does /movies/Downloads/complete actually exist? And are those paths the same from within the NZBGet container?

The ImportApprovedMovie command is a radarr process and happens before the script even does anything so this really doesn't have anything to do with SMA failing, and in fact it looks like no errors for the conversion and tagging process for the lion king are showing up (though not sure why it ran so many times but no errors). 

Try and ensure that between your nzbget container and your radarr containers that the directories are mounted the exact same way. I'm guessing from the fact that these two directories look different in the logs (one being /movies/The.Kitchen.2019.720p.BluRay.DD5.1.x264-iFT/bzhnq1jdX3Y3Gkyf4KkQe9pQV3x9h2EAY5.mkv and one being /movies/Downloads/complete) that its getting confused because these don't match

**Comment by samcro1967** [comment]
Thank you!  I was going cross eyed trying to figure this out.  The paths to the mounts were correct.  I did find the root folder thru the GUI when new movies were being added was not correct.  Not sure how that happened, but correcting it seems to have fixed it.
