### ISSUE TITLE
Audio language doesn't get tagged when file doesn't need converted

### ISSUE THREAD

**Issue by mp998** [mdhiggins/sickbeard_mp4_automator#1089]
The title kind of says it all. The last little while I have noticed that when converting some files wouldn't get the audio language set to the default setting set in the autoProccess.ini. After a little digging I found It only happens when the file doesn't need converted. It looks like the script successfully recognizes that the audio language is "und" and then during the conversion correctly specifies the language the the one I set "eng". Then because it is recognized that the file doesn't need converted that audio language doesn't end up getting saved.

```
Manual processor started.
/usr/bin/python
Audio bitrate was invalid, defaulting to 256 per channel.
Invalid external subtitle codec mov_text, ignoring.
No valid subtitle formats found, defaulting to 'srt'.
64bit Python.
Matched movie title as: James and the Giant Peach 1996-04-12
Processing James and the Giant Peach
Reading video stream.
Video codec detected: h264.
Pix Fmt: yuv420p.
Profile: High.
Reading audio streams.
Audio detected for stream #1: aac [und].
Creating audio stream 0 from source stream 1.
Reading subtitle streams.
Attempting to download subtitles.
Subtitle language array is empty.
{
    "preopts": [],
    "subtitle": {},
    "format": "mp4",
    "postopts": [
        "-threads",
        "0"
    ],
    "video": {
        "profile": null,
        "map": 0,
        "level": null,
        "codec": "copy",
        "bitrate": 2049.47205,
        "pix_fmt": null
    },
    "audio": {
        "0": {
            "map": 1,
            "language": "eng",
            "channels": 2,
            "codec": "copy",
            "disposition": "default",
            "bitrate": 256,
            "filter": null
        }
    }
}
Starting conversion.
Input and output extensions match and every codec is copy, this file probably doesn't need conversion, returning.
/plex_media/Movies/James and the Giant Peach (1996)/James and the Giant Peach (1996) - Bluray-1080p.mp4
Tagging file: /Movies/James and the Giant Peach (1996)/James and the Giant Peach (1996) - Bluray-1080p.mp4.
Trying to write tags.
Tags written successfully.
Relocating MOOV atom to start of file.
2019-11-18 15:53:32 - qtfaststart - ERROR - This file appears to already be setup for streaming!
QT FastStart did not run - perhaps moov atom was at the start already.
```

**Comment by mdhiggins** [comment]
Only way to fix this is to enable convert-mp4 in the options From: Morgan ParrySent: Monday, November 18, 2019 6:20 PMTo: mdhiggins/sickbeard_mp4_automatorCc: SubscribedSubject: [mdhiggins/sickbeard_mp4_automator] Audio language doesn't get tagged when file doesn't need converted (#1089) The title kind of says it all. The last little while I have noticed that when converting some files wouldn't get the audio language set to the default setting set in the autoProccess.ini. After a little digging I found It only happens when the file doesn't need converted. It looks like the script successfully recognizes that the audio language is "und" and then during the conversion correctly specifies the language the the one I set "eng". Then because it is recognized that the file doesn't need converted that audio language doesn't end up getting saved.Manual processor started. /usr/bin/python Audio bitrate was invalid, defaulting to 256 per channel. Invalid external subtitle codec mov_text, ignoring. No valid subtitle formats found, defaulting to 'srt'. 64bit Python. Matched movie title as: James and the Giant Peach 1996-04-12 Processing James and the Giant Peach Reading video stream. Video codec detected: h264. Pix Fmt: yuv420p. Profile: High. Reading audio streams. Audio detected for stream #1: aac [und]. Creating audio stream 0 from source stream 1. Reading subtitle streams. Attempting to download subtitles. Subtitle language array is empty. { "preopts": [], "subtitle": {}, "format": "mp4", "postopts": [ "-threads", "0" ], "video": { "profile": null, "map": 0, "level": null, "codec": "copy", "bitrate": 2049.47205, "pix_fmt": null }, "audio": { "0": { "map": 1, "language": "eng", "channels": 2, "codec": "copy", "disposition": "default", "bitrate": 256, "filter": null } } } Starting conversion. Input and output extensions match and every codec is copy, this file probably doesn't need conversion, returning. /plex_media/Movies/James and the Giant Peach (1996)/James and the Giant Peach (1996) - Bluray-1080p.mp4 Tagging file: /Movies/James and the Giant Peach (1996)/James and the Giant Peach (1996) - Bluray-1080p.mp4. Trying to write tags. Tags written successfully. Relocating MOOV atom to start of file. 2019-11-18 15:53:32 - qtfaststart - ERROR - This file appears to already be setup for streaming! QT FastStart did not run - perhaps moov atom was at the start already.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mp998** [comment]
I should have included this in the initial post. I thought that was the issue at first too but I double checked and made sure that was set to true and it was. Here is the config I am using:
```
[MP4]
ffmpeg = ffmpeg
ffprobe = ffprobe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate = 
video-crf = 
video-max-width = 
video-profile = 
h264-max-level = 
use-qsv-decoder-with-encoder = True
use-hevc-qsv-decoder = True
enable_dxva2_gpu_decode = False
ios-audio = True
ios-first-track-only = True
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 
audio-codec = aac
ignore-trudhd = true
audio-language = eng
audio-default-language = eng
audio-channel-bitrate = 
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = eng
subtitle-default-language = eng
subtitle-encoding = srt
fullpathguess = False
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = Thumbnail
download-subs = True
embed-subs = False
embed-only-internal-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt = 
aac_adtstoasc = False
postopts = 
preopts =
```

**Comment by mdhiggins** [comment]
Hm then I can’t think of any reason that wouldn’t work, want to post an example file or a before after fileset From: Morgan ParrySent: Monday, November 18, 2019 8:07 PMTo: mdhiggins/sickbeard_mp4_automatorCc: Michael Higgins; CommentSubject: Re: [mdhiggins/sickbeard_mp4_automator] Audio language doesn't get tagged when file doesn't need converted (#1089) I should have included this in the initial post. I thought that was the issue at first too but I double checked and made sure that was set to true and it was. Here is the config I am using:[MP4]ffmpeg = ffmpegffprobe = ffprobethreads = 0output_directory = copy_to = move_to = output_extension = mp4output_format = mp4delete_original = Truerelocate_moov = Truevideo-codec = h264,x264video-bitrate = video-crf = video-max-width = video-profile = h264-max-level = use-qsv-decoder-with-encoder = Trueuse-hevc-qsv-decoder = Trueenable_dxva2_gpu_decode = Falseios-audio = Trueios-first-track-only = Trueios-audio-filter = ios-move-last = Falsemax-audio-channels = audio-codec = aacignore-trudhd = trueaudio-language = engaudio-default-language = engaudio-channel-bitrate = audio-filter = audio-copy-original = Falseaudio-first-track-of-language = Falsesubtitle-codec = mov_textsubtitle-language = engsubtitle-default-language = engsubtitle-encoding = srtfullpathguess = Falseconvert-mp4 = Truetagfile = Truetag-language = endownload-artwork = Thumbnaildownload-subs = Trueembed-subs = Falseembed-only-internal-subs = Falsesub-providers = addic7ed,podnapisi,thesubdb,opensubtitlespermissions = 0777post-process = Falsepix-fmt = aac_adtstoasc = Falsepostopts = preopts =—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mp998** [comment]
There is a good sample stock video file. I was able to replicate the issue I was experiencing earlier with it. Just for the sake of testing I also used mkvtoolnix to remux it to an mkv and then I ran it through the automator and that functioned as it should.
[test_video.zip](https://github.com/mdhiggins/sickbeard_mp4_automator/files/3862162/test_video.zip)

**Comment by RandomNinjaAtk** [comment]
I've also seen the same issue with it not tagging, even when MP4 conversion is enabled.

**Comment by mdhiggins** [comment]
Found the issue
If all destination streams are set to copy and the input/output format is the same there is a check that prevents unneeded conversion even with convert-mp4 set to true as a means to reduce system usage. This check essentially is blocking things for you

Added a new option called `force-convert` in the latest update that bypasses that check when set to `True`

**Comment by kevindd992002** [comment]
I thought your script should make the final file to whatever settings specified in the ini file no matter what egardless if the input/output format is the same or if the whole process needs copying or converting? What's the reason behind setting that new force convert setting to true? Sorry if I got this all wrong.

**Comment by mdhiggins** [comment]
There is a check in there to conserve resources where if all codecs are exactly the same and the wrapper is exactly the same it skips the conversion process (because essentially the files are exactly the same) and just moves on to the tagging process. The only caveat here is that the flags for language for individual streams require re-wrapping the container so in that one scenario that resource saving measure will result in languages not being set

**Comment by kevindd992002** [comment]
Gotcha. Does `convert-mp4` need to be set to True for `force-convert` to work though? I see that in the documentation you stated that "it should be used in conjunction with convert-mp4".

**Comment by mdhiggins** [comment]
Yes
