### ISSUE TITLE
Rename files from within the automator

### ISSUE THREAD

**Issue by j-marcon** [mdhiggins/sickbeard_mp4_automator#1092]
Hi all,
I've started using this automator recently and I absolutely love it! It's now in my post-download script and has replaced multiple other utilities. There's one last other utility I'm using in my script, which is a file renamer. It seems that this automator doesn't not have the option to do so at the moment (by itself at least; I understand it integrates in other codes that do). I assume it would be quite straightforward to add and am keen to give it a try myself. I just wanted to first check whether there is any reason/difficulty/rationale why it hasn't been done? Would this be of interest to others?

**Comment by mdhiggins** [comment]
Its not done because this script is design to integrate with the many other media managers out there that handle moving/renaming the files, its not really meant to be standalone From: j-marconSent: Wednesday, November 20, 2019 12:53 PMTo: mdhiggins/sickbeard_mp4_automatorCc: SubscribedSubject: [mdhiggins/sickbeard_mp4_automator] Rename files from within the automator (#1092) Hi all,I've started using this automator recently and I absolutely love it! It's now in my post-download script and has replaced multiple other utilities. There's one last other utility I'm using in my script, which is a file renamer. It seems that this automator doesn't not have the option to do so at the moment (by itself at least; I understand it integrates in other codes that do). I assume it would be quite straightforward to add and am keen to give it a try myself. I just wanted to first check whether there is any reason/difficulty/rationale why it hasn't been done? Would this be of interest to others?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mdhiggins** [comment]
If you want to avoid using any of those programs for some reason it would be very easy using the scripts post-process add on functionality to have renaming be performed

**Comment by j-marcon** [comment]
I will give it a try next week. Thanks for the suggestion.
