### ISSUE TITLE
Copy attached fonts to be used by .ass subtitles

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#1137]
Hello,

I'm trying to keep everything the same about my video file except change it to h264 high@4.1 for better steam-ability with plex

Still in a .mkv and just copy over the .ass subtitles

My problem is when the subs are moved across to the new file all the attached fonts are lost making the subs change to default font, could the script copy over the file attachments too?

**Comment by mdhiggins** [comment]
I would need some sample files to take a look, not sure how fonts are even embedded

**Comment by Smalfinn** [comment]
I can provide anything you need; how shall I send them?

**Comment by mdhiggins** [comment]
Just email me a link either to sample or the full file and I'll take a look on whatever hosting site of your choice

**Comment by Smalfinn** [comment]
Sent you a file via wetransfer

**Comment by mdhiggins** [comment]
This was actually pretty complicated to get working but I found a solution I think. That video had like 70 fonts.

I added support for 'copy' for subtitles instead of reencoding and then had to add an entire stream parameter for attachments

So there's an `attachment-codec` option now. Set whatever attachment types you want to copy to the next stream in there. In that sample video it was ttf and otf so

`attachment-codec = ttf, otf` seems to copy everything and preserve the fonts

And `ass` needs to be listed in subtitle-codec for it to copy

1320b4f9a8731cf916f8e81df613aa9e0a1b3393

**Comment by Smalfinn** [comment]
I will test it out today!
Thank you for adding it 💃 

Just as a side note: 
If my source file has 5 audio tracks: 
1. acc stereo eng
2. acc stereo jpn
3. acc stereo commentary eng
4. ac3 5.1 eng
5. ac3 5.1 jpn

and If I select -
`ios-audio = True`
`audio-first-track-language = True`
`sort-streams = True`
`prefer-more-channels = True`

Will that produce:
1. ac3 5.1 eng
2. acc stereo eng
3. ac3 5.1 jpn
4. acc stereo jpn

**Comment by mdhiggins** [comment]
Easy way to tell actually. There's a new option for manual.py
`manual.py -oo` that shows you what it will output without creating it so you can play around to get things how you want

That being said to get exactly what you wanted requires a small update that I just pushed but now yes that should be it

You will need to set
`ios-move-last = True` and your languages need to have English first

4f7cb5bc41fcc4303a9ed1f64c0d41f748c4a550

**Comment by Smalfinn** [comment]
Think we're good to go!
Thank you for all the help
