### ISSUE TITLE
SABnzbd PostProcessing Issues

### ISSUE THREAD

**Issue by AdnanC** [mdhiggins/sickbeard_mp4_automator#1168]
Hi, 

I just downloaded the latest file and I have been having issues with SABnzbd. I tried to debug a little bit but haven't had a chance to really go through the updated code and was wondering if you can help. I have done a clean install on my Windows 10 machine with Python3 and everything works fine if I use manual.py. but postprocessing through SABnzbd is broken. This is what I have been able to find so far

1. In autoProcess.ini if **output-directory = None** under [SABNZBD] settings then the script uses "None" as an output folder which causes an error during converting. 

```
2020-03-11 10:35:48 - resources.mediaprocessor - ERROR - C:\ffmpeg\bin\ffmpeg.exe -fix_sub_duration -hwaccel dxva2 -i c:\Downloads\Complete\TV Shows\House, M.D. S06E01 Broken (Part 1).mkv\House, M.D. S06E01 Broken (Part 1).mkv -vcodec libx264 -map 0:0 -vb 1094k -c:a:0 aac -map 0:1 -ac:a:0 2 -b:a:0 256k -metadata:s:a:0 language=eng -strict experimental -c:a:1 ac3 -map 0:1 -disposition:a:1 +default -ac:a:1 6 -b:a:1 1536k -metadata:s:a:1 language=eng -c:s:0 mov_text -map 0:2 -metadata:s:s:0 language=eng -f mp4 -threads 0 -y None\House, M.D. S06E01 Broken (Part 1).mp4
```

This can be solved by removing "None" from the config file and just leaving the setting blank. Which brings us to the second issue.

2. If you look at the FFmpeg command the file path is not in "" and that causes the command to throw an error. I am not sure why that is happening. 

Maybe I am missing something obvious. Will appreciate your help.

Thanks

**Comment by mdhiggins** [comment]
None shouldn't be under the config, was this an artifact from migrating the configuration file? (You can check the backup file produced and see if that was present).

The FFMPEG command isn't passed to popen as a string and what you're seeing in the error isn't the direct command, the parameters are passed as an array of options the quotes don't matter and are only absent just because that array is converted into a string for logging purposes

Its failing because you have a None directory getting injected into the output

I'm not sure why that None value would be there but it shouldn't be created from the migration and if it is let me know and I'll try to address it

**Comment by JySzE** [comment]
@mdhiggins

I tested this on my end and if the original config had the value 'none' it was migrated over with it.

**Original Test:**
[autoProcess.ini.backup.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4321885/autoProcess.ini.backup.txt)

**Migrated:** 
[autoProcess.ini.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4321886/autoProcess.ini.txt)

**Comment by AdnanC** [comment]
Quick question how do you migrate? I didn't do any migration, just downloaded the master branch from github and that was it. If you look at config/autoProcess.ini.sample file you see the following default values:

*
[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
couchpotato-category = couchpotato
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = None
*

the last line is where "None" is coming from

I think I might be doing something wrong here :)

**Comment by JySzE** [comment]
Delete the None from 
"output-directory = None"

and try again.

**Comment by mdhiggins** [comment]
Ah good catch! That's a mistake on the sample file and None shouldn't be in there

Migrating was something that happened for people coming from old versions of the script and I was confused because I didn't have logic in place to account for `None` being set before but it makes sense. Yeah just delete `None` and I'll update the sample file to fix that mistake. My bad not sure how None got in there

**Comment by mdhiggins** [comment]
c09682446e875f22c8a5dc85161357e61a5ae69b
