### ISSUE TITLE
Deluge Post Process, ffprobe 'probing' everything

### ISSUE THREAD

**Issue by johnwchambers** [mdhiggins/sickbeard_mp4_automator#1180]
I have the following script executed after something completes downloading in deluge:

>     
    #!/bin/sh
    torrentid=$1
    torrentname=$2
    torrentpath=$3

    if [[ -d "$torrentpath/$torrentname" ]]; then
        #echo "$torrentpath/$torrentname" + " is a directory"
        mkdir "/dwnldr/tor/extracted/$torrentname"
        mkdir "/dwnldr/tor/converted/$torrentname"
        /opt/deluge/unrarall/unrarall -v -o "/dwnldr/tor/extracted/$torrentname" "$torrentpath/$torrentname"
        extracted=$?
        wait $!
        if [ $extracted -eq 0 ]; then
            python3 /opt/mp4automator/manual.py -i "/dwnldr/tor/extracted/$torrentname" -c /opt/mp4automator/config/autoProcess.ini -a -m "/dwnldr/tor/converted/$torrentname"
            python3 /opt/mp4automator/delugePostProcess.py "$torrentid" "$torrentname" "/dwnldr/tor/extracted"
        else
            python3 /opt/mp4automator/delugePostProcess.py "$torrentid" "$torrentname" "$torrentpath"
        fi
        rm -rf "/dwnldr/tor/extracted/$torrentname"
    elif [[ -f "$torrentpath/$torrentname" ]]; then
        #echo "$torrentpath/$torrentname" + " is a file"
        #python /opt/mp4automator/manual.py -i "$torrentpath/$torrentname" -c /opt/mp4automator/autoProcess.ini -a -nd
        python3 /opt/mp4automator/delugePostProcess.py "$torrentid" "$torrentname" "$torrentpath"
    fi

Also, the only way I can get the delugePostProcess.py script to process extracted files and then have the appropriate *arr pick them up is if I execute the manual.py script first. It looks weird but checking the logs it doesn't double-convert the files and is working so far.

I can see when something downloads it executes fine:

![image](https://user-images.githubusercontent.com/752262/76679868-686db780-6627-11ea-9736-4c1c6d38bf2b.png)

But when that download isn't in it's own subfolder, it seems that ffprobe scans everything in the root directory tree structure of /dwnldr/tor/comp/tv or /dwnldr/tor/comp/movie as shown below.

![image](https://user-images.githubusercontent.com/752262/76679891-9521cf00-6627-11ea-98fb-75b97378f1f0.png)

**Comment by mdhiggins** [comment]
Can't really help with your custom script but I'm guessing its scanning the directory because you're passing a directory. The way delugePostProcess works is by querying the API for files included in the torrent. By circumventing this to extract the files and then using manual.py you are in scanning the entire directory so this behavior is to be expected. delugePostProcess is not meant to work with compressed files.

If you're downloading files that are complicated by compression and zips then I would say just ditch any downloader post processing (no deluge scripts), use 'completed download handling' in sonarr/radar which will offload extracting to those programs, and let postSonarr and postRadarr handle the conversion instead

**Comment by mdhiggins** [comment]
And to clarify, the ffprobe scan is expected as well. That's how the script determines what files are potentially valid media that should be converted, it will probe all the files in the torrent

You may actually have more luck using the SABPostProcess.py file instead of delugePostProcess.py for your custom solution. Because deluge queries the API for the files it essentially ignores your directory you custom create whereas SAB just kind of scans whatever directory you feed it so you could trick it and then get the benefit of notifying Sonarr/Radarr. You could probably then ditch manual.py (this is also why you need the manual.py step)

It uses these parameters
```
# SABnzbd argv:
# 1 The final directory of the job (full path)
# 2 The original name of the NZB file
# 3 Clean version of the job name (no path info and ".nzb" removed)
# 4 Indexer's report number (if supported)
# 5 User-defined category
# 6 Group that the NZB was posted in e.g. alt.binaries.x
# 7 Status of post processing. 0 = OK, 1=failed verification, 2=failed unpack, 3=1+2
```

The trouble will be getting the label which I don't think deluge passes which you'd need the API for

**Comment by johnwchambers** [comment]
Roger that, thanks for the information!
