### ISSUE TITLE
Deluge/NZBGet PostProcesses don't process metadata portion of config

### ISSUE THREAD

**Issue by johnwchambers** [mdhiggins/sickbeard_mp4_automator#1182]
I noticed the nzbget and deluge post process scripts don't tag or move the moov part of the file like the postSonarr/Radarr counterparts do even though the metadata part of the config file is set. Do these post-process scripts not do the metadata portion? And if not, can it be added to have the ability to let them do it?

I can't configure the postSonarr/Radarr scripts since doing so makes the files get converted twice between when being passed from nzbget/deluge to the appropriate *arr instance it seems. And with the way I have my servers broken out (one main with plex/*arr/etc and both nzbget/deluge downloaders on separate VMs), I don't want the conversion process running on the main plex server either.

Thank you for all the help and this awesome repository!

**Comment by mdhiggins** [comment]
That's an intentional design decision. The downloaders don't have any metadata information so tagging is held until it gets back to sonarr/radarr which do pass that information. While technically its possible to guess that information from filenames it tends to be inaccurate and is intentionally not includes. You could turn off process-same-extension which would prevent double converting and just save the tagging until the end

**Comment by johnwchambers** [comment]
Ah, so maybe modify the config on the plex server to not convert, not process same extension, but the metadata portion would be done? If so I'll configure both of the *arr post scripts and give them a whirl.

**Comment by johnwchambers** [comment]
Going to close this out, thanks for pointing me in the right direction!

**Comment by mdhiggins** [comment]
f0fc3ac3f86a5768fbdf119bbfe4345e24490827

Been meaning to add this for a while. Reads the 'encoder' tag now if extensions are the same and aborts if SMA was the one that did the conversion. This is another safeguard to prevent double encoding. Tagging should still work fine
