### ISSUE TITLE
NSBGetPostProcess.py: Reports error, deletes output file, report success to NZBGet and Radarr.

### ISSUE THREAD

**Issue by jennec** [mdhiggins/sickbeard_mp4_automator#1201]
When processing some file the encoder encounters an error which reults in the output file being deleted.  The script reports then as an error, then immediately reports that everything is fine and sends a notification to Radarr to process the file.  

Technically the download worked, but if the converstion fails I would have expected to report back to NZBGet that the process failed and not request Radarr to process the unconverted file.

Attached log for detail: 

[NZBGet Log - NZBGetPostProcess false success.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4388846/NZBGet.Log.-.NZBGetPostProcess.false.success.log)

**Comment by mdhiggins** [comment]
Things are designed to fall through because its processing a directory and a failure on some random file that may not be important could break the whole process. Could easily exit the script if not output was returned but that might result in good downloads that include a bad sample file or some random file that get picked up and fails blocking an otherwise good conversion

The post downloader scripts are specifically designed to be more tolerant because bad files will be filtered out by sonarr/radarr

If you think it should just error out and fail I'm open to reasoning or solutions

**Comment by jennec** [comment]
For downloads with multiple files, media files that is, I can understand that. But for downloads with one media file you end up with the unconverted file in your library. Not what I would expect from my work flow. 

Is there a way to determine how many media files (above sample size) being converted and based on that return the appropriate result to NZBGet if there is a failure?

  I.e. if only one media file and it errors during conversion then mark as failed. Two or more could be marked as failed if the one file conversion error results in it being 90% or more of the total amount of files to convert.

**Comment by mdhiggins** [comment]
7727ad551df5fadbeb5baf7b8918e714a24deef0

That should add script aborting if conversion is enabled and no valid conversions take place for all 5 downloader scripts, let me know if you encounter any errors
