### ISSUE TITLE
Automated Processing Not Working

### ISSUE THREAD

**Issue by grokdesigns** [mdhiggins/sickbeard_mp4_automator#1216]
```
- MP4Automator updated to latest before testing
- Windows Version: Server 2016
- Python Version: 3.8.2
- FFMPEG Version: git-2020-04-01-afa5e38 (have tried various versions)
- Sonarr Version: 2.0.0.5343
- SABnzbd Version: 2.3.9 [03c10dc]
```

- When a file is passed from Sonnar and is downloaded via SABnzbd, the SABPostProcess.py script runs, and almost immediately finishes with a "Exit(1) SystemExit: 1" message. The file remains unconverted and stays in the finished download folder rather than being processed and moved by Sonarr.
 - If I have Sonarr import the file through the manual import option, it fill move/rename the file, but it still does not convert it to an MP4 file.
 - If I run manual.py on the same file, it converts successfully.

sma.log attached.
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4435252/sma.log)

**Comment by mdhiggins** [comment]
Alright so probably a few things going on here

Your failure in the log is an FFMPEG error, so your current settings aren't good. I notice you're using h264qsv so I'm guessing its failing because you don't have a build of FFMPEG that supports this or you don't have compatible hardware, though if this is working on manual.py I'm not sure why that would be. If you want to post some logs from a manual.py conversion I can compare the two.

It also looks like you're converting the h264 stream for probably no reason. You can add h264 to your video codecs to allow that to copy

Would also be helpful to have you include your autoProcess config

**Comment by grokdesigns** [comment]
@mdhiggins QSV is definitely supported. My whole setup was working correctly prior to updating MP4Automator maybe 1 or 2 weeks ago. I don't remember how long it had been before then that I updated, so I can't offer much information on what had changed. I do know that the update caused the config file to update to the new format. Attached are the log from a manual conversion and my autoProcess.ini. The re-converting MP4 may be because I have a maximum width and bitrate specified in my conversion settings.
[sma_manual.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4435370/sma_manual.log)
[autoProcess.ini.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4435371/autoProcess.ini.txt)

**Comment by mdhiggins** [comment]
The 'debug' line shows why its encoding instead of copying, in your case its only because you haven't specified h264 in your codec list
`codec = h264qsv, h264` will result in a big performance bump for you by allowing remuxing. Your current configuration will never remux because you only have the hardware encoder listed which will never match ffprobe's reported codec (you need to include the generic).

Now for the crash. It looks like the options being generated are identical (as expected given they both use the same codebase). The error that's causing it to fail from SAB is 

```
[h264 @ 000001ab3a5cf040] No device available for decoder: device type dxva2 needed for codec h264.
...
Device setup failed for decoder on input stream #0:0 : Unknown error occurred
```

These are FFMPEG errors related to hardware acceleration but I don't know why you would only get that from SAB. Is there a potential permission issue where SAB may not have hardware access? Any weird changes between these 2 running? I've seen situations where this error comes about on windows when running in a headless configuration

https://trac.ffmpeg.org/ticket/7511

**Comment by grokdesigns** [comment]
@mdhiggins I think you put me on the right track with that link, so thank you!. It appears to be an issue with the dxva2 hardware acceleration when running in headless mode. Since dxva2 is the first hwaccel option mediaprocessor.py finds that FFMPEG supports, it uses that and causes the crash when running in headless mode, but not with manual.py where the console is present. I moved d3d11va to the front of my hwaccels list so that it picks that up first and it appears to be working as desired now.
