### ISSUE TITLE
Seems to processing files that it shouldn't

### ISSUE THREAD

**Issue by Deihmos** [mdhiggins/sickbeard_mp4_automator#1218]
[autoProcess.txt]

The previous version would have left this file alone but the new version seems to be doing some sort of processing. I have it set to only remux if eac3 audio is detected. Why is the file being processed? 

[logfile.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4441259/logfile.log)

[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4441271/autoProcess.txt)

**Comment by mdhiggins** [comment]
Because the script is now doing a lot more work at the metadata level (adjusting dispositions, titles, tagging, and sorting streams) the bypass that would previously bail out if all streams were `copy` was removed

9cd51d17ae4e84939a533f1a6f7e50492bc963fa

The remuxing process should still be quick but all the above benefits are lost. It does now check if the file was processed by SMA before and will not reprocess it to sort of replace this feature but the codecs all being `copy` is only a small part of what is written to the container now so that check was removed

Previously when only mp4 was supported and little additional data was written during the FFMPEG encode this made sense because mutagen would still run and write metadata but now FFMPEG is writing a lot of the format metadata so bypassing that has consequences

**Comment by Deihmos** [comment]
Ok thanks for the update.
