### ISSUE TITLE
Plex library update for multiple episodes 

### ISSUE THREAD

**Issue by Captain-Wiggles** [mdhiggins/sickbeard_mp4_automator#1220]
I noticed that when a complete season is added and the automator is converting files, it notifies plex to update after each individual file is completed. This results in plex picking up on the temp file that is being converted. Is there a way to make it so that the automator holds off on notifying plex to scan library until all the files are finished converting?

**Comment by mdhiggins** [comment]
Not really a way to fix this since the script is ignorant of what other processes are going on, it's not persistent or self aware since its just a script called by other programs.

You could either try to use other notification techniques (sonarr/radarr) to update plex or you can use the `temp-extension` option in autoProcess.ini to use a temporary extension during conversion that plex won't pick up.
