### ISSUE TITLE
radarr-sma container directions

### ISSUE THREAD

**Issue by promo76** [mdhiggins/sickbeard_mp4_automator#1236]
Hello,

Please see the screenshot below. There is no file postRadarr.sh in the directory mentioned. Am I supposed to point it at the /usr/local/sma/config/postRadarr.py script?

![image](https://user-images.githubusercontent.com/53126190/80854407-03394a00-8c06-11ea-83fd-9cbafe7bac32.png)

**Comment by promo76** [comment]
There is also a bug in Radar that affects the movie posters. Any chance you can update the image to the nightly? It seems that it resolves the issue.

**Comment by mdhiggins** [comment]
postRadarr.sh has been included for a while now, when's the last time you updated the container?

I just did a clean pull and check and its there

![image](https://user-images.githubusercontent.com/3608298/80863524-06a2f480-8c4b-11ea-84a4-57a67451a226.png)

And located here in the repository

https://github.com/mdhiggins/radarr-sma/blob/master/extras/postRadarr.sh

And no I'm not gonna switch to the nightly image, its not remotely stable enough for prime time. There is a preview tag that corresponds to the linuxserver radarr preview tag if you wanted to try that. I'm not having the poster issue on the main branch.

**Comment by promo76** [comment]
I pulled it last night and tried it. Here is my yml file:

---
version: "2"
services:
  radarr:
    image: mdhiggins/radarr-sma:latest
    container_name: radarr-sma
    environment:
      - PUID=1024
      - PGID=101
      - TZ=America/New_York
      - SMA_PATH=/usr/local/sma
      - SMA_UPDATE=true
    volumes:
      - /volume1/configs/Radarr:/config
      - /volume1/configs/SMP4A:/usr/local/sma/config
      - /volume1/Media/UHD Movies:/uhdmovies
      - /volume1/Media/Movies:/movies
    ports:
      - 33000:7878
      - 33001:9898
    restart: unless-stopped

**Comment by mdhiggins** [comment]
So the file should be there then. Post some start up logs and directory structure if you’re not seeing that. It’s the main launch file for the container and I haven’t touched it in months and no one else is saying it’s missing so it’s unlikely to be absent or lots of people would notice. 

And for your other question, you either use completed download handling and no SAB script or you use the SAB script without completed download handling. It’s an either or situation. Since I haven’t built a SAB container with the script I just instruct people to use completed download handling and only have to maintain 2 containers so they can use off the shelf downloads containers. 

postRadarr notifies Plex

**Comment by promo76** [comment]
Thanks! I will try the container download again.

**Comment by mdhiggins** [comment]
Make sure after you pull the update that you also rebuild the container

I use docker compose but that involves **pull** followed by **up**
