### ISSUE TITLE
Radarr/Sab

### ISSUE THREAD

**Issue by TinTin192** [mdhiggins/sickbeard_mp4_automator#1237]
Sorry if this has been mentioned before but i couldn't find it.

Fresh install of everything. Radarr/Sabnzbd/Sickbeard MP4

All setup as i have previously.

Downloading works fine. 
Then it starts doing it's thing.
Then.. This happens..

Traceback (most recent call last):
File "/home/.scripts/SABPostProcess.py", line 8, in <module>
from resources.mediaprocessor import MediaProcessor
File "/home/.scripts/resources/mediaprocessor.py", line 12, in <module>
from resources.metadata import Metadata
File "/home/.scripts/resources/metadata.py", line 12, in <module>
import tmdbsimple as tmdb
ModuleNotFoundError: No module named 'tmdbsimple'

Permissions are set correctly as the same on all my other servers.
Fresh Git pulled.
Setting's updated.
Requirements installed etc.

**Comment by mdhiggins** [comment]
Did you install tmdbsimple?

If you did then it’s either broken or you have additional python environments and things are being executed outside the environment with your dependency

**Comment by TinTin192** [comment]
Yes tmdbsimple was installed with the requirements and even double checked it.
There can't be any additional python environments anywhere as it's a fresh install of the server + Everything else that's on it, Which is Radarr,Sabnzbd..

**Comment by mdhiggins** [comment]
I mean its a ModuleNotFoundError, its only caused by one thing
SAB is probably executing things its in own python environment. SAB is written in python2 and will execute the code internally its it own python environment sometimes

Try creating a shell wrapper script and point SAB to the correct location

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1211

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1215

https://forums.sabnzbd.org/viewtopic.php?f=2&t=24563

**Comment by mdhiggins** [comment]
```
#!/bin/bash
/path/to/python3 /home/.scripts/SABPostProcess.py "$@"
```
