### ISSUE TITLE
feature request: post*arr qtfast before file is actually moved to final location

### ISSUE THREAD

**Issue by johnwchambers** [mdhiggins/sickbeard_mp4_automator#1239]
Is is possible to have the post*arr processes do the moving of the moov stuff before it gets placed into its final destination? The path where everything is located right before the final move happens to be on a 2TB NVMe disk and the final destination is a share on my Synology unit with a max 1GbE link. I'm thinking this would make this process much faster than copying the file to the share to then have to read/write back to it again.

Thank you!

**Comment by mdhiggins** [comment]
It's unfortunately not possible for the post*arr processes. Those scripts only get called after the moving is complete and *arr doesn't have an option to run a script before the move (wish it did).

If you're using a downloader script (SAB/NZBGet/torrent etc) you can force the qtfast process through FFMPEG so that its done before *arr is notified.  You can do this by added `-movflags, faststart` to your post-opts in autoProcess.ini

Just a warning though, the reason this isn't the default behavior is that back when the script was first developed I was seeing issues with playback after tagging if you moved the moov atom before the tagging metadata was written. It was a rare problem and I was never able to pin down if there was a specific reason why but moving the atom after tagging resolved it. I will say I haven't revisited this for testing and mutagen has since received a lot of updates (there was a few years where mutagen was abandoned and buggy and then only recently did it get forked and updated again) so it may not be an issue anymore. Feel free to try.

**Comment by johnwchambers** [comment]
i'll give the modification a go in my autoprocess.ini file. what happens when the file gets processed by the post*arr processes though since it was moved already, will it just skip that part?

**Comment by mdhiggins** [comment]
Yeah it checks to see if it’s done already and skips  that part if it’s been moved

**Comment by johnwchambers** [comment]
awesome, thanks for the help with the additional command parameters. i'll close this out now.
