### ISSUE TITLE
PostRadarr.py

### ISSUE THREAD

**Issue by TinTin192** [mdhiggins/sickbeard_mp4_automator#1243]
Hi MDhiggins.

Sorry to open something that may have been approached before. But it's REALLY annoying me.

Everything setup correctly as i have done numerous amounts of times.
Permissions set. etc etc

Radarr > Sab > Script > Radarr.
Generally theme of things.. All working

![image](https://user-images.githubusercontent.com/45340611/81841966-238cd100-9543-11ea-857e-d6b61c0b5b45.png)

And then this... :| Any help is appreciated.

**Comment by mdhiggins** [comment]
I mean this has to be a permissions thing. You'll need to post your permissions for that file to prove otherwise along with some info about what user/group is running radarr

That being said though I think you're using an old version of SMA because I've moved away from /var/log in future updates specifically because it was prone to permission issues (its now stored in the config folder inside the script directory). Updating might resolve this.
