### ISSUE TITLE
Maxing out my CPU

### ISSUE THREAD

**Issue by mozzer502** [mdhiggins/sickbeard_mp4_automator#1244]
I see a pull request to set the concurrent instances to just one #326 
I'm currently downloading a lot of TV episodes and having multiple FFMPEG processes running is maxing out the CPU.
Do I need to wait for this pull request to be delivered (assuming it's asking for what I think it's asking), or is there a setting somewhere that can limit the processor usage of FFMPEG?

**Comment by mdhiggins** [comment]
You can limit the number of threads via the threads option but that’s about the extent of it. 

That pull request is old and not really focused on this issue and unlikely to ever be merged

**Comment by mozzer502** [comment]
as always, thank you.

**Comment by mdhiggins** [comment]
https://stackoverflow.com/questions/4565567/how-can-i-limit-ffmpeg-cpu-usage

Hope that provides some resources, don't have any great solutions to this

Most of the download managers will queue jobs instead of just doing multiple at once so that might be another avenue to explore. Sonarr/Radarr/NZBGet should all queue processes
