### ISSUE TITLE
Docker sonarr-sma with linuxserver/sabnzbd

### ISSUE THREAD

**Issue by eric9876-git** [mdhiggins/sickbeard_mp4_automator#1256]
Hey Mike,

Quick question, I am running sonarr-sma docker container.  My downloader is SABNzbd, also in a docker container using image linuxserver/sabnzbd.  The docker hub instructions say to enable "Completed Download Handling" and use  postSonarr.sh.  Now I didn't used to have "Completed Download Handling" enabled before I migrated to sonarr-sma, I had tried it but found it to be somewhat unreliable or unpredictable at time.  

Now before migrating SABNzbd to docker, I had it configured per SMA instructions which is to use SABPostProcess.py.  There doesn't appear to be an official release image of sabnzbd-sma.  I can understand that you probably didn't want to go down the rat hole of creating "-sma" variants of all the applications you support.  So I customized linuxserver/sabnzbd to include SMA.  I have been using it, somewhat successfully, but recently I started having some post processing issues at the very end of the process when the mp4 file has been moved to its final destination and the second QTFS file is being created.  When the QTFS file is done being created, what's been happening, intermittently, is the sonarr imported mp4 file and the new QTFS file are both getting deleted leaving me with no files whatsoever because sonarr has already imported and cleaned up the downloads folder.

Two questions: 

1) What is the recommended linuxserver/sabnzbd docker image configuration (i.e. no SMA in SAB) for sonarr-sma?

2) In my case, I built SMA into linuxserver/sabnzbd, leveraging SABPostProcess.py, and then went back to my pre-docker Sonarr config which did not use "Completed Download Handling".  Should this work or did you move some of that SABPostProcess.py functionality into the sonarr post processing script?  Because my issue is intermittent, I feel like maybe SAB and Sonarr are both trying to do the same cleanup at the end of post processing.  

Edit: Enabling "Completed Download Handling" in Sonarr and disabling SABPostProcess.py in SABnzbd seems to work.

Thanks,
Eric

**Comment by RandomNinjaAtk** [comment]
I've built a custom container that has MP4 automator integrated, github link:
https://github.com/randomninjaatk/docker-sabnzbd-extended

Personally for me, I only encode with SMA in SAB, I also may re-process the files in Radarr/Sonarr, but that is only for tagging purposes.

I do not connect the SAB SMA script to Radarr/Sonarr via API. Strictly use manual.py for encoding. That way I can ensure only one file is ever processed at a time, using SAB's built in post processing functions.

But that is just my personal preference. This also allows me to use the normal Completed Download Handling in both apps without any issue.

**Comment by mdhiggins** [comment]
I would say the recommendation is that you either use Completed Download Handling **without** a post downloader script (SABPostProcess.py if we're sticking with that example) or don't use Completed Download Handling and then do use a downloader script. Completed download handling may prematurely grab files that are being converted when the download finishes resulting in issues which is why its left off if you're using a downloader script and the downloader script contains logic that notifies the parent where and when to retrieve a complete download. 

If you opt not to use a completed download handler, then you need to use some kind of script otherwise it will sit in the download folder and never get handed back to the parent

Sonarr/Radarr have pretty robust queueing systems using their normal workflows so I don't think that's a major issue. The postSonarr/postRadarr scripts can do everything as a single step so its easier to maintain those 2 docker containers and just use off the shelf containers for downloaders but it comes down to personal preference of when you want the conversion to take place and you can use a custom container that implements SMA at the downloader level.

**Comment by mdhiggins** [comment]
Hopefully that clarifies things, reopen if there's any issues

**Comment by eric9876-git** [comment]
Thanks to both of you for the inputs.  Personally, I like the idea of using stock docker images as much as possible so will go with Mike's recommendations.  I've had the post processing script disabled on my custom SAB image since I opened this case and everything seems to be working well when allowing Sonarr to do it all.
