### ISSUE TITLE
How to force video conversion

### ISSUE THREAD

**Issue by laryan61** [mdhiggins/sickbeard_mp4_automator#1273]
First, you’ve been extremely helpful in assisting me get my system configured and up and running.
Still in the early stages of “properly” configuring my installation of SMA. While running a bunch of videos through the manual.py script and reviewing final videos I discovered there were several videos with larger files sizes that others from same series.
In reviewing the debug logs I discovered the smaller files were processed with "codec": "h264_nvenc" and the larger with "codec": "copy".

I think the Video configuration setting, “crf-profiles” might be the answer, but frankly I I’m not sure how to tune it to do what I want. I’ve started with your default settings. I would like SMA to convert all videos I run through the script to create a smaller file. With my current settings when I try to process an AVI file, manual.py crashes. In my script that calls manual.py, it has SMA use a different ini file (without preopts = -hwaccel,cuvid,-c:v,h264_cuvid and crf-profiles) if processing an AVI file. That does work. But wonder if a proper setting might allow a single ini file.

I’ve attached the following.
Small-video-file.log: the sma.log file for the video that does uses “h264_nvenc” and create a smaller file.
Larger-video-file.log: the sma.log file for the video that does uses “copy” and create a larger file.
Avi-fail.log: the sma.log file for a AVI DVD rip video that fails manual.py file.
And my autoProcess.ini file

[config.tar.gz](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4832859/config.tar.gz)
[avi-fail.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4832860/avi-fail.log)
[small-video-file.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4832861/small-video-file.log)
[larger-video-file.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4832862/larger-video-file.log)

**Comment by mdhiggins** [comment]
I would just delete everything you have in preopts that's all conflicting with the options you're generating and not in the right location anyway and you're probably causing some instability and crashing. This is probably why the avi sample is failing

hwaccel is natively supported and that will be added to the generated path if you're using a hwaccel codec and have those options configured in autoprocess.ini, shoehorning it into preopts will lead to issues and crashes like you're seeing with your avi file

the debug line in the output settings that generated tells you why a codec isn't being copied

the small file sample is not being copied because your source bitrate exceeds your maximum bitrate

this is not the case for the larger video files it proceeds with copying

you may also benefit form increasing your analyze duration and probe size to add stability for the older codecs like AVI
`Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options`

Can add something like `-probesize, 50M, -analyzeduration, 100M` to preopts

**Comment by mdhiggins** [comment]
if you never want to copy just remove h264 from your codec list and only leave h264_nvenc though not remuxing seems silly
`codec = h264_nvenc`

**Comment by laryan61** [comment]
Thanks for your assistance, you've been extremely helpful.

I've made your suggested changes to my autoprocess.ini config file. It looks like it has fixed all my issues; AVI crashing, audio volume, video size reduction, etc. After additional testing I'll provide my changes for your information and others who my come cross this thread.

**Comment by mdhiggins** [comment]
Sounds good thanks for following up
Gonna close this for now but feel free to addend additional information
