### ISSUE TITLE
postsonarr error.

### ISSUE THREAD

**Issue by KamikazeComazzi** [mdhiggins/sickbeard_mp4_automator#1281]
This is my first attempt at setting up the mp4 automator and searched and review my error first, but can't resolve it.  

When the postsonarr.py is executed, the following error ocurrs: 
Traceback (most recent call last):
  File "C:\mp4_automator\postsonarr.py", line 84, in <module>
    tvdb_id = int(os.environ.get('sonarr_series_tvdbid'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' executed, 

Other info

- I am running on a Windows 10 platform with Sonarr v3.0.3.896 - python 3.7,8. The python packages and ffmeg are installed. 
- I configured the autoprocess.ini (see attached)
- I created a bat file for the execute of the script, The batch file is just the following:
    "C:\Users\Comazzi\AppData\Local\Programs\Python\Python37\python.exe" "C:\mp4_automator\postsonarr.py
- Sonarr will not save the custom script connection, stating script exited with code 1

Any suggestions? 

[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4890599/autoProcess.txt)
![image](https://user-images.githubusercontent.com/68012454/86918531-dcf7c500-c0f4-11ea-8f8a-fa4ee2229526.png)

**Comment by mdhiggins** [comment]
When running the test to add/test the custom script it shouldn't even get to line 84

Are you seeing that error when running the test within Sonarr's log files?

`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' executed,`

Or are you seeing that error when trying to run your bat file manually. If you are seeing that running manually, that's expected because running it manually the script will be missing all of the Sonarr provided environment variables

If all of the above is true, you need to look in the Sonarr logs for the error that's causing your exit code 1 which is almost always an import error

Also make sure you can launch manual.py without any errors as a means to test your dependencies

**Comment by KamikazeComazzi** [comment]
I was running it manually because of the exit code 1 .   I am not having  this issue with radarr.

Let me run the manual.py method and review the sonarr logs

Thanks for the help

Sent from my iPhone

On Jul 8, 2020, at 9:51 AM, Michael Higgins <notifications@github.com> wrote:

﻿

When running the test to add/test the custom script it shouldn't even get to line 84

Are you seeing that error when running the test within Sonarr's log files?

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' executed,

Or are you seeing that error when trying to run your bat file manually. If you are seeing that running manually, that's expected because running it manually the script will be missing all of the Sonarr provided environment variables

If all of the above is true, you need to look in the Sonarr logs for the error that's causing your exit code 1 which is almost always an import error

Also make sure you can launch manual.py without any errors as a means to test your dependencies

**Comment by mdhiggins** [comment]
Gotcha, so to determine the cause of exit code 1 in sonarr you need to just run the test and then look at the sonarr logs for the error

**Comment by KamikazeComazzi** [comment]
So the error in the sonarr logs,; cmd.exe access denied.  So i change the script from a .bat to a powershell .ps1.  It worked, i was able to save an test it.  

As for as the manual.py test, i get a failure:
Manual processor started.
Python 64-bit 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)].
Traceback (most recent call last):
  File "C:\mp4_automator\manual.py", line 408, in <module>
    main()
  File "C:\mp4_automator\manual.py", line 330, in main
    print("Guessit version: %s." % guessit.__version__)
NameError: name 'guessit' is not defined

guessit-3.1.1 is installed.  searching past issues now ...

**Comment by mdhiggins** [comment]
Ensure that its installed under the correct python environment

**Comment by KamikazeComazzi** [comment]
I believe it is ... manual test of guess it works.
C:\mp4_automator>guessit "M:\test\After_Life_S02E01.mkv"
For: M:\test\After_Life_S02E01.mkv
GuessIt found: {
    "title": "After Life",
    "season": 2,
    "episode": 1,
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}

C:\mp4_automator>manual.py -i "M:\Test\After_Life_S02E01.mkv"
Manual processor started.
Python 64-bit 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)].
Traceback (most recent call last):
  File "C:\mp4_automator\manual.py", line 408, in <module>
    main()
  File "C:\mp4_automator\manual.py", line 330, in main
    print("Guessit version: %s." % guessit.__version__)
NameError: name 'guessit' is not defined

however, the script works both from Sonarr and Sabnzbd.  So i think you can close this out.  Not sure why the manual test failed, but the other ones are so im good!   thank you!

**Comment by mdhiggins** [comment]
manual.py is the only aspect of the script that depends on guessit so radarr and sonarr should proceed without issue even if that's not installed.

Guessit I believe installs differently than some packages by default and can be unavailable to different users depending on which user installed versus which is executing and I suspect that's why you're having your issue

Either way, glad its working
