### ISSUE TITLE
What have I done script no longer works and I cant work out what i did

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#1305]
Im not even sure what happened, I downloaded the new master push and things don't seem to work now
[sma.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/5093038/sma.log)

**Comment by mdhiggins** [comment]
Please try to make your issues better / more detailed and not just paste massive log files in the future as this is really frustrating

```
Impossible to convert between the formats supported by the filter 'Parsed_null_0' and the filter 'auto_scaler_0'

Error reinitializing filters!
```

Its an FFmpeg error that seems like its probably because your decoder and encoder aren't playing nice together

Without knowing what you changed its tough to say what the culprit here is. 

1. Was this working before? 
2. Did you just add some new hwaccel options?
3. If you take out the hwaccel options does it go away?
4. Was this after a recent software update? (there was some new changes to hwaccel functionality)
5. Does adding this filter `hwdownload,format=nv12,hwupload_cuda` make any difference?

**Comment by morpheus2n2** [comment]
Sorry about that, found the problem was not just the HW decoding, I had accidently added an comma at the beginning of the line of decoders after removing it its all working again 🤦
