### ISSUE TITLE
postprocess before moving to final

### ISSUE THREAD

**Issue by hroman73** [mdhiggins/sickbeard_mp4_automator#1311]
using sonarr-sma and radarr-sma dockers:

is there a way the postprocess script can be done in the /downloads directory then moved to /movies? the downloads folder is a local ssd where as my movies and tv directories are my nas...

thank you!

**Comment by mdhiggins** [comment]
Not really though having a temporary 'processing' directory is something I'd like to add in a future update

**Comment by mdhiggins** [comment]
489fee596c9d80af21aac694fd153a0e78105faf

Try that, use the `output-directory` option in `Converter`. Should do all the processing and QTFS/tagging in that directory then move the file to its final destination

Sonarr/Radarr will still copy the original file to the final folder first, just because they don't call their scripts until after that step but at least this way files won't be created in that final directory until finished

**Comment by hroman73** [comment]
I know you closed this but I wanted to thank you, everything works and is now running smoothly...

**Comment by mdhiggins** [comment]
Thanks for following up glad it's working for you

**Comment by johnwchambers** [comment]
I've noticed with this change that sometimes nzbget reports a failure for the sonar postprocessing with an error stating that the directory doesn't match what it passed to sonarr for scanning. I didn't have debug logging turned on at the time this ran but have since turned it on now. I'll open a separate issue if I see it again but figured I'd just chime in on this thread with this tidbit of info.

**Comment by mdhiggins** [comment]
@johnwchambers 
The message you're seeing here isn't related to this change (which actually does not impact NZBGetPostProcess) but instead is related to this issue

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1301

Its a new change introduced to try to catch and correct for a bug in Sonarr. It should not have changed any underlying behavior because the error would otherwise have just been undetected with no report

**Comment by johnwchambers** [comment]
@mdhiggins 
Roger that. Thanks for the info!
