### ISSUE TITLE
Are default values correct?

### ISSUE THREAD

**Issue by joreilly02** [mdhiggins/sickbeard_mp4_automator#1314]
In the default values section of the main page, it says that Sickbeard mp4 Automator will default to AAC 2.0 with additional AC3 track when source has >2 channels (ex 5.1). In the default AutoProcess.ini it says that the default video codec is AC3.  Does this do what the default section claims?   

Also, is there a way to passthrough audio/video?  I'm using this mostly to embed subtitle tracks in an already converted file.    

Thanks for making such an incredible program!

**Comment by mdhiggins** [comment]
Default video is h264, don't think it says default video anywhere is AC3

Defaults are correct but I think your interpretation is a little off.  Default audio is AC3 with universal audio enabled for AAC. Universal audio creates an additional stereo AAC track for any track >2 channels. If it encounters a 2 channel track then the universal audio settings are used instead to maximize combability (instead of creating 2 tracks)

Don't set a codec for universal audio if you don't want that feature

Remuxing is probably what you want for passthrough. Any codec included on the list will be copied/remuxed assuming there's not some other setting that prevents it (for example, max bitrate can block remuxing if bitrate is too high). Just include whatever codecs you want to keep on the list to achieve passthrough
