### ISSUE TITLE
Post process scripts called with renamed filename

### ISSUE THREAD

**Issue by bbobrian** [mdhiggins/sickbeard_mp4_automator#1325]
My post process scripts are getting called with filenames such as 'Episode.rnm.mp4'

The rest of the SMA process is working, but this causes post processing to fail.

**Comment by mdhiggins** [comment]
In what way is it failing?

**Comment by bbobrian** [comment]
Trying to post process 'Episode.rnm.mp4' instead of the actual file 'Episode.mp4'

**Comment by bbobrian** [comment]
To add more detail, my post processing scripts are asynchronous in nature.

One triggers plex_autoscan which seems to actually work ok with the 'rnm' file name, but I think it's just coincidental luck due to the timing of the final rename and Plex actually scanning the directory.

Another script queues the file to be uploaded to gdrive. This one fails because when the actual upload is attempted, the file no longer has the 'rnm' in the filename.

**Comment by mdhiggins** [comment]
Got it that's very helpful
I've added 2 options that should help address this
084ff183e452e7fb47614aea6a9a8983f7275f63

First one is to just make this new .rnm thing optional since it is only needed for very specific workflows (ones where codec information is included in the name and will change during the conversion)

I also added an option to have the script wait for post-process scripts to finish which will prevent this asynchronous issue in the event that the above rename feature is desired

Both of these default to False so with that update it should revert back to normal for you

`force-rename` in Sonarr/Radarr sectiosn
`wait-post-process` in Converter section

I'll update the wiki shortly

**Comment by mdhiggins** [comment]
Wiki updated

**Comment by mdhiggins** [comment]
d41c270a8e080c4bc53040228b08aa2948b5c944

The `wait-post-process` feature will be temporarily enabled if the `force-rename` feature is enabled for postSonarr/postRadarr workflows regardless of user setting to prevent this asynchronous issue you had as well

**Comment by bbobrian** [comment]
Tested and working as expected. Thanks!
