### ISSUE TITLE
ffmpeg always invoked on mkv files, even when all streams are copied

### ISSUE THREAD

**Issue by tulomov** [mdhiggins/sickbeard_mp4_automator#1365]
I've tried this with my settings (below) and something as close to the default as possible. Running with `manual.py` (and, I presume, `postSonnar.py` and `postRadarr.py`) always runs ffmpeg, even when all of the streams are copied. This is true even when you run `manual.py` *again* on the generated file. I would expect my settings to be idempotent. I need convert all of the eac3 files in my collection, and I would like to be able to run `manual.py` on the root directory instead of finding all of the files by hand.

```
[Converter]
ffmpeg = /usr/bin/ffmpeg
ffprobe = /usr/bin/ffprobe
output-extension = mkv
output-format = mkv
postopts = -max_muxing_queue_size, 9999
threads = 0
output-directory = 
temp-extension = .mkv.tmp
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
sort-streams = False
process-same-extensions = True
force-convert = False
post-process = False
detailed-progress = False
preopts = 
hwdevices = 
hwaccel-output-format = 
hwaccels = 
hwaccel-decoders = 
wait-post-process = False

[Metadata]
relocate-moov = False
tag = False
full-path-guess = True
tag-language = eng
download-artwork = False
sanitize-disposition = 

[Video]
codec = h264,x264,h265,x265,hevc
max-bitrate = 0
crf = -1
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = False
max-width = 0
profile = 
max-level = 0.0
pix-fmt = 
filter = 
force-filter = False

[Audio]
codec = ac3,aac,mp3
channel-bitrate = 0
max-channels = 6
prefer-more-channels = True
default-more-channels = True
languages = 
default-language = 
first-stream-of-language = False
allow-language-relax = True
max-bitrate = 0
filter = 
force-filter = False
sample-rates = 
copy-original = False
aac-adtstoasc = False
ignore-truehd = mp4, m4v, mkv
ignored-dispositions = 
unique-dispositions = True

[Permissions]
chmod = 0664
uid = -1
gid = -1

[HDR]
pix-fmt = 
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = 
codec-parameters = 
filter = 
force-filter = False

[Universal Audio]
codec = 
channel-bitrate = 0
first-stream-only = True
move-after = True
filter = 
force-filter = False

[Subtitle]
codec = srt, subrip
codec-image-based = hdmv_pgs_subtitle, pgs
languages = 
default-language = 
first-stream-of-language = False
encoding = utf-8
burn-subtitles = False
burn-dispositions = 
download-subs = False
download-hearing-impaired-subs = False
download-providers = 
embed-subs = True
embed-image-subs = True
embed-only-internal-subs = True
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
unique-dispositions = True
attachment-codec = 
```

**Comment by mdhiggins** [comment]
Not recommended to run manual.py on root directories.

The situations where manual.py won't rerun FFMPEG are limited especially for MKVs. If you don't have process-same-extension turned on being one of them.
For MP4s it looks to see if its a file that's been encoded by SMA before and will skip there but MKVs don't support writing the encoder via FFMPEG so this check doesn't apply

I used to have an option that would look to see if all streams are being copied and would skip conversion assuming the input and output extensions were the same but people complained because other features weren't being applied  (sorting, stream level metadata,

3c0953a674f00e04cbc0863508143305f3aa4dad

That update I just pushed introduces an option to restore that check, off by default, called `bypass-if-copying-all`

Criteria include

1. Input and output extension must match
2. force-convert must be false
3. process-same-extension must be true
4. All audio, video, and subtitle streams must be copy
5. the number of video, audio, and subtitle streams is equal on the input and output end

See if that works

That being said I still think its a poor practice to run manual.py on root folders

**Comment by tulomov** [comment]
That seems to be doing the right thing, thanks!!

Thanks for the warning. I'll take an fs-level snapshot to mitigate any possible disasters. One thing that could help in that regard is if `-oo` also observed the new setting. This is probably a matter of taste, but if `-oo` went all the way to determining that it's actually not going to run `ffmpeg`, then you could run it as a safe dry run on larger directories where you only want to convert a subset.

Thanks again for the quick patch!

**Comment by mdhiggins** [comment]
`-oo` does actually include this, it adds a `bypassConvert = true` to the output file parameters
