### ISSUE TITLE
Set default audio track only

### ISSUE THREAD

**Issue by chaganiu** [mdhiggins/sickbeard_mp4_automator#1373]
I have a bunch of videos I have configured using this tool (thank you, btw).  I used the option to set create and set a stereo AAC track as the default.  I always kept the original audio in the file.

Now I want to go back and set the original audio back as the default audio.  Is there a way to do that?  I don't want to change anything with the video.  Just set the highest quality audio back as the default.

**Comment by mdhiggins** [comment]
No way to do this as an isolated function and in order to change the default track the container will need to be rewritten

Best way would be to make a special autoProcess.ini file that remuxes everything so no quality is lost and use a couple specific settings so that the bigger audio track becomes the default

Things you'll need to do

1. Disable universal audio (otherwise you'll get extra tracks being created if this was already done) by blanking the codecs in that section
2. Set `force-convert` to `True`
3. Set `default-more-channels` to `True`
4. Set `default` for `sanitize-disposition` so the old defaults get wiped
5. Include all source video audio and subtitle codecs so that they are copied and no quality is lost
6. Disable any random first-stream options that would otherwise delete streams (ex `first-stream-of-language`)
