### ISSUE TITLE
Anamorphism and Auto-Cropping

### ISSUE THREAD

**Issue by jennec** [mdhiggins/sickbeard_mp4_automator#1375]
How would I go about having this script autocrop, maximise bit rate application and maintain aspect ratio regardless of the if the unconverted source has the correct aspect ratio applied or not?

My issue is that, after getting an Ultra wide screen recently, playback 21:9 or similar content has revealed that some files are actually 16:9 with the black bars at the top and bottom as part of the video.  This seems like a waste of bit rate to me and I was hoping to get this script to autocrop and create an anamorphic file so that the bit rate is applied to the actual content and maintain the original aspect ratio excluding any black bars.  

Hope this makes sense.

**Comment by mdhiggins** [comment]
Probably not something I'm going to be able to automate reliably, you might be better off manually cropping files for these edge cases. Open to solutions and pull requests or even a logical flow proposal without code but this would be quite challenging to implement

I also think you're probably operating under some false assumptions regarding how bitrate works. For any modern codec stationary black bars should be almost negligible with the way video compression works and I would see if you could find any tests / analysis that prove otherwise before you invest a lot of effort in this. 

https://forum.doom9.org/showthread.php?t=150222

There's some interesting discussion from one of the h264 codec developers here that goes into it. Its a complex answer

https://forum.doom9.org/showthread.php?t=150222

Another thread with a similar question
