### ISSUE TITLE
Skipping over .mp4 files is slow

### ISSUE THREAD

**Issue by oregonpillow** [mdhiggins/sickbeard_mp4_automator#1378]
I don't understand why the script takes so long to skip over exiting .mp4 files before deciding it's .mp4 file and can be skipped. On even a small library the script spends 99% of it's execution time deciding if it should skip a file or not. I would expect it to skip .mp4 files in milliseconds before arriving at .mkv or other formats for example.

Any suggestions? Is this normal or expected behaviour?

**Comment by mdhiggins** [comment]
Script is not meant to be bulk run on a directory and it always updates and retags all files including MP4s when it encounters them so that's probably where the time is coming from. If that's how you are using the script I would caution against this and suggest a media manager like Sonarr/Radarr instead. If you want it to just ignore MP4 files entirely and not do a tagging pass or other analysis and move on just add them to the `ignored-extensions` option and that should speed things up.

**Comment by oregonpillow** [comment]
thanks @mdhiggins that's very helpful. I'm running radarr/sonarr but I can't get it to run scripts. It never seems to work which is why i use a cron job to schedule a directory scan each night.

**Comment by mdhiggins** [comment]
Hmmm that's odd why can't you get it to run scripts?
