### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by mgaulton** [mdhiggins/sickbeard_mp4_automator#1391]
I'm looking at the script, for a particular use case.
I'd like to run it during postprocessing not to convert but just to identify languages, remove non-english audio tracks and if no english audio is found, delete the file, so that nzbToMedia will treat it as a failed down and tell SickChill/CP to get the next.
I'm finding CP is grabbing a lot of non-english of late.

**Comment by mdhiggins** [comment]
Not really what this script is for and seems like it would be silly to use this and nzbToMedia since they are sort of competing solutions.
You could potentially write your own script and leverage the libraries included. The converter folder inside the script has everything you would need to read the languages and accomplish your task but this is not a baseline function of this script

**Comment by mgaulton** [comment]
I borrowed your libs and wrote something that is working well enough for me
to identify non-english. Other than the "und" ones anyway.
Thank you for taking the time!

**Comment by mdhiggins** [comment]
Nice good stuff 👍
