### ISSUE TITLE
How to only convert audio, without modifying anything else ?

### ISSUE THREAD

**Issue by Chuckame** [mdhiggins/sickbeard_mp4_automator#1393]
Hello,

How to only convert and replace audio to ac3, without modifying anything else (simple copy of the rest) ? The output file will be suffixed with `converted.mkv`
I know the command using ffmpeg : `ffmpeg -hide_banner -i "$f" -map 0 -c:v copy -c:a ac3 -c:s copy "${f%.mkv}.AC3.mkv"`

**Comment by mdhiggins** [comment]
No explicit way to do this but what you'll want to do is basically include all other codecs on the approved list so they will be remuxed and that should result in the same behavior. Any codec included on the list will be copied (assuming you don't have some other setting like bitrate with width etc that forces encoding). You'll also want to disable universal audio by setting the codecs there to nothing

Output file renaming is intended to be handled by the media management programs though but you could include a small renamer as an optional post processing script.

**Comment by Fizqen** [comment]
Did you ever solve this @Chuckame  ? Have the same need.

**Comment by mdhiggins** [comment]
The answer I provided. 

The script is always designed to remux as top priority so just include relaxed settings and it will.

Can also just set your video and subtitle codecs to 'copy' though it's better to include approved codecs than to blanket copy but this is a core feature of what the script was created to do.

**Comment by Fizqen** [comment]
I managed to get it working, it now converts only audio and leaves the video codecs as specified in approved codecs section in autoprocess. The file is being converted and then renamed by sonarr and transferred to correct location.

Although everything works as expected, I get the following error after the conversion is completed in the postprocess log in Sab:

KeyError: 'status' 

2021-12-20 18:56:42 - autoprocess.sonarr - ERROR - Update to Sonarr failed, check if Sonarr is running, autoProcess.ini settings and make sure your Sonarr settings are correct (apikey?), or check install of python modules requests.
Traceback (most recent call last):
File "C:\Users\sh\Desktop\sickbeard_mp4_automator-master\autoprocess\sonarr.py", line 82, in accessAPI
log.info("%sSonarr response: %s." % (infoprefix, rstate['status']))
KeyError: 'status'

Apikey is correct (double checked and refreshed in settings), and since everything works despite the error message, this confuses me a bit.

Any ideas what might be wrong? (Thanks for taking your time) !

**Comment by mdhiggins** [comment]
This is an old bug logging bug that was fixed, just update your script
