### ISSUE TITLE
Problems automating conversion with Sonarr

### ISSUE THREAD

**Issue by Habboman** [mdhiggins/sickbeard_mp4_automator#1420]
So I am struggling to setup the converter with Sonarr. I am pretty new to this whole coding thing so please explain like I am your grandma...

So I set up (almost) everything as intended and tried downloading and see if it may work. The manual conversion works. To no surprise the automatic conversion didn't..

So what I didn't understand/ found out how to solve are two steps:

A) In the sonarr part of Autostart.ini I set  host, port and apikey. As I wasn't able to find anything on google about sonarrs webroot I left that one blank (which probably causes problems?)

B) I didn't get part 3) of the Sonarr setup. It states:

> Set the Drone Factory Interval' to 0 to disable it, and disable 'Completed Download Handling' in Radarr settings. The script will trigger a specific path re-scan, allowing the conversion to be completed before Radarr starts moving stuff around. This step is optional if you do not desire any processing between the downloading by whichever downloader you choose (NZB or Torrent), but is required if you wish to convert the file before it is handed back to Radarr. You must use either a download script or enabled Completed Download Handling. If neither are used the file will never be passed back

As it says upfront I disabled Completed Download Handling and did anything else... But the last part says it has to be enabled or else I need a download script... Which script? 

I have high hopes that fixing these would allow me to have automatic conversion... 

Thank anyone so much for any help!

**Comment by mdhiggins** [comment]
1. Webroot is usually blank, this is more for people running reverse proxies or things where multiple services are consolidated on one port behind different webroots, seems like you did everything correctly
2. Its an either or situation. Something needs to tell Sonarr your downloads have completed, no matter what downloading program you're using. Completed download handling is the easier way to do this and is fine to use, and sonarr will run postSonarr.py after it moves and renames the file to its final destination and run the conversion. Some people want all the conversion done before Sonarr gets passed the completed file for various reasons, so the other option is to turn off completed download handling and use a downloader script that will do the conversion and pass the now already converted file back to Sonarr so all Sonarr has to do is move, rename, and tag the file but the bulk of the conversion is done before Sonarr gets the download back from the downloader. In this context, a downloader is something like NZBGet, SAB, Deluge, etc and downloader scripts are the NZBGetPostProcess.py, SABPostProcess.py, DelugePostProcess.py etc each matched with their respective download program. The big thing here is you don't want to use both methods (completed downloading handling AND one of those scripts) because they will conflict with each other and Sonarr will start trying to grab downloads while conversion is in progress.

The fact that manual.py is working is a good sign, you just need to get your automation stuff configured

**Comment by mdhiggins** [comment]
Feel free to continue discussion just closing this since it's not a technical issue

**Comment by Habboman** [comment]
I tried starting from scratch but it also does not work. Somehow once Sonarr downloaded everything it just stops and the data never gets converted. After trying to find a solution for hours I kind of just gave up.

So I looked just for some way to bulk convert manually but I could not figure out settings for ffmpeg that work for me. So if I use your manual converter I can watch the videos on plex. But if I transcode them manually, it does not seem to work. Right now I am using simple batch file 
`for %%a in ("*.mkv") do ffmpeg -i "%%a" -c:v libx264 -preset fast -crf 20 -b:v 288k "newfiles\%%~na.m4v"
pause
`
But this does convert my files but they are not able to be watched on plex whilst the one converted with your manual are. Your code is extremely extensive so I was not able to find the solution by myself. Could you tell me which conversion settings you do use? So I could have a batch file that just runs over my library? Inputting each seperately into the manual has been quite tedious (although way less time consuming than to fix it myself).

**Comment by mdhiggins** [comment]
The conversion is dynamic and adjusted based on the input source so there's not going to be a universal FFMPEG command that will get you the same results. Did you configure your postSonarr.py script? Post some pics or examples of your configuration and check the logs its probably something minor required to get it working.
