### ISSUE TITLE
Question about AMD and Nvidia GPU HWaccels support

### ISSUE THREAD

**Issue by Weezzel** [mdhiggins/sickbeard_mp4_automator#1421]
My machine i have is a AMD Ryzen 9 with a RTX 3080 GPU. I am want to verify if the code options are correct for what I am wanting to achieve.
I am want all NON-HDR files to be converted to hevc_nvenc and all HDR to be converted to HEVC, using Nvidia HWaccels.
I feel that I have the Codec's correct, but I am not sure that I have the **_HWaccels, hwaccel-decoders, hwdevices and hwaccel-output-format_** options correct.

I have seen where this **_hwdevices = vaapi:/dev/dri/renderD128_** is changed to **_hwdevices = 0_** to specify the GPU for a single GPU installed
And this would be changed from **_hwaccel-output-format = vaapi:vaapi_** to **_hwaccel-output-format = cuda_**, but I am not sure and dont know enough about setting up these options

Input on the correct setting for these options would be appreciated., 

The code I have running now is;
[Converter]
ffmpeg = ffmpeg.exe
ffprobe = ffprobe.exe
threads = 0
**_hwaccels = nvdec,hevc_nvenc,hevc_cuvid,cuda,dxva2,d3d11va,vaapi
hwaccel-decoders = nvdec, hevc_nvenc, hevc_cuvid, h265_cuvid, h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_vaapi
hwdevices = vaapi:/dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi_**
output-directory =
output-format = mp4
output-extension = mp4
temp-extension =
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to =
move-to =
delete-original = True
sort-streams = True
process-same-extensions = False
force-convert = False
post-process = False
detailed-progress = True
preopts = -loglevel,debug,-probesize,1000000,-analyzeduration,10000000
postopts = -max_muxing_queue_size, 9999
wait-post-process = False
bypass-if-copying-all = False
opts-separator = ,

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = False
tag-language = eng
download-artwork = poster
sanitize-disposition =

[Video]
codec = hevc_nvenc
max-bitrate = 0
crf = -1
crf-profiles = 0:22:4.5M:12M,4100:22:8M:24M,8000:18:10M:30M
codec-parameters =
max-width = 0
profile = Main10
max-level = 5.1
pix-fmt = p010le,nv12
filter =
force-filter = False
dynamic-parameters = true
preset = fast
bitrate-ratio =

[HDR]
codec = hevc,x265,h265
pix-fmt = yuv420p10le
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = fast
codec-parameters =
filter =
force-filter = False
profile =

AutoProcess.ini File
autoProcess.zip

**Comment by mdhiggins** [comment]
Seems like you need to read up a little more on hwaccels

I would say first it seems like you're mixing up your encoders and decoders

Decoders are affected by the `hwaccels` and `hwaccel-decoders` options

The devices and formats can affect both encoders/decoders

For a windows based NV system I would just leave both `hwaccel-output-format` and `hwdevices` blank which will default to the FFMPEG auto settings which for nvidia is typically fine unless you have multiple nvidia cards

For the encoding side of things, it seems you want to not use NVENC for encoding  for HDR, probably because of the metadata issues so that's fine and your current settings look good, just don't include that codec in the HDR section on your list.

If for some reason you wanted to use the hwdevices setting, it needs to be a dict (see the readme) so it would be `hevc_nvenc:0`

The formats can be cuda or cuvid, read up through nVidia on which one you want

Finally, for your general codecs under non HDR video, by including only `hevc_nvenc` you will never copy a video stream because that's only an encoder. You'll need to add the base codec to that list if you ever want to copy, like `hevc_nvenc, hevc` in the event a source video already meets all your other parameters for encoding. If any conversion does need to take place, it will still use nvenc
