### ISSUE TITLE
hw on sabnzbd 

### ISSUE THREAD

**Issue by pazport** [mdhiggins/sickbeard_mp4_automator#1426]
hello mate, i have got GPU to work fine with manualy.py but when i try and use it in sabnzbd i keep getting error saying it is not set right. but yet in manual.py it works fine. this is the error.

```Failed to set value 'vaapi=sma:/dev/dri/renderD128' for option 'init_hw_device': Invalid argument
Error parsing global options: Invalid argument```

also full log is posted below mate.


https://pastebin.com/9usnYaNb

**Comment by mdhiggins** [comment]
You running in docker? You on linux? Do you have /dev/dri/renderD128 accessible by the user executing SABNZB?

**Comment by pazport** [comment]
running in docker
linux ubuntu 18.04 LTS
it as full access to /dev/dri
``# docker exec  sabnzbdtv2 ls /dev/dri
card0
renderD128``

**Comment by mdhiggins** [comment]
The person who made the container needs to fix permissions on your acceleration device, I solved this on my containers take a look at the 50-gid-video file on how its handled. The error is because it doesn't have access and if it works in manual (probably running as root) that's almost certainly a permissions issue

https://github.com/mdhiggins/sonarr-sma/blob/build/root/etc/cont-init.d/50-gid-video

Same error as here
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1177

**Comment by pazport** [comment]
yes it was permission error. i had to add ``abc`` to ``root`` group thanks for your advice mate :) helpful as always mate :)
