### ISSUE TITLE
How do I get NVENC acceleration working in this?

### ISSUE THREAD

**Issue by Garvaethelarvae** [mdhiggins/sickbeard_mp4_automator#1463]
I'm currently in the process of setting this up for sonarr but I'm having an issue whenever I run manual.py. It outputs the attached error whenever I convert a 10 bit HEVC file to an 8 bit H264 file:

`[h264_nvenc @ 000001c73656b580] 10 bit encode not supported`

`[h264_nvenc @ 000001c73656b580] Provided device doesn't support required NVENC features`

`Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height`

`Conversion failed!`

[log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/6868368/error.txt) 

whenever I ran it. I first tested conversion in FFMPEG (through CMD, I'm using Windows 10) directly with this to make sure FFMPEG was not the issue, 

`ffmpeg -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -i D:\foldee\examplefile.mkv -c:a copy -c:v h264_nvenc -b:v 5M D:\transcode\waawe.mkv` 

but it still outputted the same error. I then ran it with `-pix_fmt yuv420p`:

`ffmpeg -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -i D:\foldee\examplefile.mkv -c:a copy -pix_fmt yuv420p -c:v h264_nvenc -b:v 5M -loglevel verbose D:\transcode\waawe.mkv`

this time it outputted with this [error](https://imgur.com/a/6nJqS20). Finally, I got NVENC to work with this:

`ffmpeg -y -vsync 0 -i D:\foldee\examplefile.mkv -c:a copy -c:v h264_nvenc -pix_fmt yuv420p -b:v 5M D:\transcode\waawe.mkv`

Apparently, according to the person that helped me with that: "for pixel reformatting from 10-bit color depth to 8-bit you need to mix both CPU & GPU in the processing, which means you cannot ask ffmpeg to use CUDA hardware acceleration"
I tried to use CUVID in FFMPEG directly, but it just outputted `unknown encoder 'h264_cuvid'`.

I don't know how to make those changes in Sickbeard MP4 Automator though. Here's my autoprocess.ini:

[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/6868439/autoProcess.txt)

Sidenote: Is there a way to not convert audio or subtitles in Sickbeard MP4 Automator? I don't think converting them would be necessary in my use case.

**Comment by mdhiggins** [comment]
Try removing the hwaccels if you think you can't convert using both the decoder or encoder (though I'm not sure that's 100% true, might just be a filter issue). What Nvidia card are you using?

`hwaccels = `

SMA will only convert streams that don't meet your parameters set by the config file, so if you don't want to convert audio/subtitles just ensure you have your settings configured so that your source material is valid and can just be remuxed

Posting logs makes it way easier to tell you why something is getting converted

**Comment by mdhiggins** [comment]
https://forums.developer.nvidia.com/t/how-to-convert-pix-format-in-hardware-when-transcoding-10-bit-hevc-to-h264/59233

That also might be helpful

In that case, try

`hwaccels = cuvid`
`hwaccel-decoders = hevc_cuvid` (you can have more than 1 option here but put hevc_cuvid first)
`pix_fmt = yuv420p`

Also just looking over the truncated log you posted it looks like your audio stream was remuxed

**Comment by Garvaethelarvae** [comment]
I tried adding `hwaccels = cuvid`, leaving hwaccels blank, and `hwaccel-decoders = hevc_cuvid`, still no dice. Here's the logs and my autoprocess.ini.
[nocuvid.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/6873725/nocuvid.txt)
[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/6873726/autoProcess.txt)
[cuvid.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/6873724/cuvid.txt)

**Comment by mdhiggins** [comment]
So it looks like the `cuvid` options aren't being applied.

Your command with `hwaccels = cuvid` and `hwaccel-decorders = hevc_cuvid, ...` generates the following FFMPEG command

```
C:\ffmpeg-20200612-38737b3-win64-static\bin\ffmpeg.exe -fix_sub_duration -i "D:\Torrentz\[Judas] One Piece - 984.mkv" -vcodec h264_nvenc -map 0:0 -vb 2386k -metadata:s:v BPS=2386000 -metadata:s:v BPS-eng=2386000 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -c:a:0 copy -map 0:1 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=jpn -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 copy -map 0:2 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:1 copy -map 0:3 -metadata:s:s:1 title= -metadata:s:s:1 handler_name= -metadata:s:s:1 language=por -disposition:s:1 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:2 copy -map 0:4 -metadata:s:s:2 title= -metadata:s:s:2 handler_name= -metadata:s:s:2 language=ara -disposition:s:2 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f matroska -threads 0 -metadata:g encoding_tool=SMA -y "D:\Torrentz\[Judas] One Piece - 984.2.mkv
```

The command without `cuvid` is exactly the same
```
C:\ffmpeg-20200612-38737b3-win64-static\bin\ffmpeg.exe -fix_sub_duration -i "D:\Torrentz\[Judas] One Piece - 984.mkv" -vcodec h264_nvenc -map 0:0 -vb 2386k -metadata:s:v BPS=2386000 -metadata:s:v BPS-eng=2386000 -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -c:a:0 copy -map 0:1 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=jpn -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 copy -map 0:2 -metadata:s:s:0 title= -metadata:s:s:0 handler_name= -metadata:s:s:0 language=eng -disposition:s:0 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:1 copy -map 0:3 -metadata:s:s:1 title= -metadata:s:s:1 handler_name= -metadata:s:s:1 language=por -disposition:s:1 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:2 copy -map 0:4 -metadata:s:s:2 title= -metadata:s:s:2 handler_name= -metadata:s:s:2 language=ara -disposition:s:2 -default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -f matroska -threads 0 -metadata:g encoding_tool=SMA -y "D:\Torrentz\[Judas] One Piece - 984.2.mkv"
```

This is failing most likely because your FFMpeg build doesn't support CUVID. When the script considers adding the hwaccel options, it checks your FFMpeg binary to see if it supports these features before adding them to the command line, and if they aren't supported it skips

You can run `ffmpeg -hwaccels` to see yourself what is supported. You probably need to compile FFMpeg yourself to get the full nVidia feature set to get this working. Judging from your folder structure you're just using an off the shelf static build (`C:\ffmpeg-20200612-38737b3-win64-static`)

Can check this out though I only just googled this, haven't tried it myself
https://www.youtube.com/watch?v=hEYqT0IcpAo

Getting hwaccel and a decoder to work is your best bet to enable hardware accelerated decoding and encoding which will give you the best performance by a wide margin

You're still getting your `10 bit encode not supported` error because neither of the FFMpeg commands above include the `pix-fmt` option. Looking at your included autoProcess.ini file `pix-fmt = ` so you need to include some kind of 8 bit format that to downsample from 10 bit to 8 bit. On your sample from your first post that worked you do include that `-pix_fmt yuv420p`. That solution uses software decoding and hardware encoding so its a mix and therefore slower than the pure hardware approach

Setting `pix-fmt = yuv420p` should get at least the mixed hardware/software approach working

Also just be aware there is a separate `[HDR]` section in autoProcess.ini so if you start feeding HDR sources into the script those options will be used instead. You can leave the `space`, `transfer`, and `primaries` sections blank if you don't want to detect HDR content and treat it differently

**Comment by mdhiggins** [comment]
And finally if you want to keep the `-vsync 0` option in your command that you included in your samples just add that to your preopts

`preopts = -vsync, 0` (include the comma)

**Comment by Garvaethelarvae** [comment]
Well, thank you, it works now. I think I was just being dumb. I added `pix-fmt = yuv420p` under the `[Video]` section instead of adding `pix_fmt = yuv420p` under the `[Converter]` section (which what I originally did), and it works now. I left `hwaccels` blank and set `codec` to `h264_nvenc, x264, h264`.
