### ISSUE TITLE
SMAConfigParser no attribute

### ISSUE THREAD

**Issue by KATPWR** [mdhiggins/sickbeard_mp4_automator#1473]
after installing automator running manual.py gives the error 
`
local@hedonismbot:/opt/Automator$ python manual.py
Manual processor started.
Python 64-bit 2.7.18 (default, Mar  8 2021, 13:02:45)
[GCC 9.3.0].
Guessit version: 1.0.3.
/usr/bin/python
Python 2 is no longer officially supported. Use with caution.
Loading config file /opt/Automator/config/autoProcess.ini.
Traceback (most recent call last):
  File "manual.py", line 430, in <module>
    main()
  File "manual.py", line 368, in main
    settings = ReadSettings(logger=log)
  File "/opt/Automator/resources/readsettings.py", line 591, in __init__
    self.readConfig(config)
  File "/opt/Automator/resources/readsettings.py", line 740, in readConfig
    for key in config[section]:
TypeError: 'SMAConfigParser' object has no attribute '__getitem__'
`

**Comment by mdhiggins** [comment]
2bb656b98cb1e3ec6f9048807ca728bffb12a288

This is an error because Python 2 isn't supported anymore and this method isn't backwards compatible. Should probably upgrade to Python 3. It is however an easy fix to include backwards compatibility so the above change is a small patch that should fix this error and allow it to be Python 2 and 3 friendly

Long term though you're going to want to upgrade

Let me know if that fixes things and close the issue
