### ISSUE TITLE
Post Radarr and Sonarr failing due to sma.log permissions

### ISSUE THREAD

**Issue by Miguel102** [mdhiggins/sickbeard_mp4_automator#1493]
Hello, first of all great job with the automator! Really helpful!

I know this [Issue](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1486) has been closed but I'm having the same situation with Radarr and Sonarr not having permissions to use sma.log, and I've used chmod and chown to change the permissions of the full directory of the script, and it works. Temporarily. I haven't figured out why or when, but after a while the sma.log files go back to their owner being root instead of pi which is my main user, and losing permissions.

This is after deleting the sma.log files and running manual.py:

```
drwxrwxrwx 3 pi   pi   4096 Nov 13 12:43 .
drwxrwxrwx 8 pi   pi   4096 Nov 13 12:43 ..
-rwxrwxrwx 1 pi   pi   4224 Nov  8 21:32 autoProcess.ini
-rwxrwxrwx 1 pi   pi      0 Nov  6 18:11 __init__.py
-rwxrwxrwx 1 pi   pi   1209 Nov  8 14:45 logging.ini
drwxrwxrwx 2 pi   pi   4096 Nov  8 14:45 __pycache__
-rw-r--r-- 1 root root  245 Nov 13 12:43 sma.log
```

Is there any configuration on the script that changes what the user and permissions that file is created with that I'm missing? You mentioned changing something in the container but I'm not sure what you meant by that. If it's related to docker then I'm not using one, I just have the script on a directory on /home/pi and run it directly from there.

**Comment by mdhiggins** [comment]
The problem here is that you're running manual.py as your root user, and so when no log file exists it has no choice but to create the sma.log file as the user that's running the script

the log files also recycle with time (sma.log becomes sma.log.1) as the file size gets bigger, so if you're running lots of jobs as root then when that recycle event occurs you may end up with an sma.log file owned by root instead of pi. I would suggest just being consistent as to which user is running the script

**Comment by Miguel102** [comment]
That solved it! I was using sudo nohup to run manual.py in the background, but didn't know that by using that command I was basically running at as root. Quick search, changed the command to sudo -u user and now the logs are being created with the proper user. Thanks for the quick reply!
