### ISSUE TITLE
How to use with GPU?

### ISSUE THREAD

**Issue by kennfoxx** [mdhiggins/sickbeard_mp4_automator#1503]
Hi everyone, I've been looking for information on using sickbeard_mp4_automator on a GPU server. The machine is Linux Ubuntu 18 + RTX 2070, could someone guide me how to configure?

**Comment by mdhiggins** [comment]
Lots of discussion on previous issues about this, just search for nvenc for closed issues on this repo to see what other people have done

First step is you'll need to understand hardware decoding / encoding for FFMPEG to determine what options you want since this is actually what drives everything

https://trac.ffmpeg.org/wiki/HWAccelIntro

and specifically additional documentation for NVIDIA

https://docs.nvidia.com/video-technologies/video-codec-sdk/ffmpeg-with-nvidia-gpu/

Once you have a working build of FFMPEG and can get hardware encoding working manually then you're ready to configure the script to automate it

The main options you'll want for decoding are 

`hwaccels`
`hwaccel-decoders`
`hwdevices`
`hwaccel-output-format`

and for encoding you'll just want to set your codec to one of the nvenc encoders depending on if you want h264 or hevc/h265

So just set your first codec to `h264_nvenc` or `hevc_nvenc`, though you should include `hevc` or `h264` after that so that remuxing can still be enabled

Example
```
[Video]
codec = hevc_nvenc, hevc
```

That should be more than enough to get you started

https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1444
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1499
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1463
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1421

**Comment by kennfoxx** [comment]
Very grateful for the help.
