### ISSUE TITLE
qBittorrent error

### ISSUE THREAD

**Issue by kennfoxx** [mdhiggins/sickbeard_mp4_automator#1508]
When running shows the following error.

2021-12-18 09:04:49 - qBittorrentPostProcess - INFO - qBittorrent post processing started.
2021-12-18 09:04:49 - resources.readsettings - INFO - /usr/bin/python3
2021-12-18 09:04:49 - resources.readsettings - INFO - Loading config file /scripts/mp4_automator-vod/config/autoProcess.ini.
2021-12-18 09:04:49 - qBittorrentPostProcess - ERROR - No valid label detected.
2021-12-18 09:04:49 - qBittorrentPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
  File "/scripts/mp4_automator-vod/qBittorrentPostProcess.py", line 49, in <module>
    sys.exit(1)
SystemExit: 1

**Comment by mdhiggins** [comment]
2021-12-18 09:04:49 - qBittorrentPostProcess - ERROR - No valid label detected.

Fix your labels

**Comment by kennfoxx** [comment]
Forgive me, I'm new to all this, where do I set the labels to make the script work?

**Comment by mdhiggins** [comment]
![image](https://user-images.githubusercontent.com/3608298/146765035-faa3229a-dc00-4d02-961a-e9ced126265e.png)

```
[qBittorrent]
couchpotato-label = couchpotato
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
port = 8080
ssl = False
host = localhost
username = 
password = 
output-directory = 
path-mapping = 
```

The label/category need to match

**Comment by kennfoxx** [comment]
There is a possibility to call the script without the need for labels, I download torrents via magnetic links

**Comment by mdhiggins** [comment]
You can just manually set a category from inside qbittorrent but you need some category

![image](https://user-images.githubusercontent.com/3608298/146773080-b3d5ca94-629a-42fd-a956-bbce1db8d2d5.png)

**Comment by kennfoxx** [comment]
Great. Thank You

**Comment by mdhiggins** [comment]
If you're not using any of the media managers and just want conversion the bypass category is what you want

**Comment by mcaps1** [comment]
Duplicate of #1508
I am having the same issue using qBittorrent v4.4.2. All the labels are matching. However, the error still continues.


**Describe the bug**
qBittorrentPostProcess script is not recognizing the category/label of "radarr" set by Radarr.exe. However, category is being properly passed to qBittorrent.

**Command or context you are trying to run**
Python.exe "C:\Media Server\sickbeard_mp4_automator-master\qBittorrentPostProcess.py" "%L" "%T" "%R" "%F" "%N" "%I"

**autoProcess.ini settings**
[Converter]
ffmpeg = ffmpeg.exe
ffprobe = ffprobe.exe
threads = 0
hwaccels = 
hwaccel-decoders = 
hwdevices = 
hwaccel-output-format = 
output-directory = 
output-format = mp4
output-extension = mp4
temp-extension = 
temp-output = False
minimum-size = 0
ignored-extensions = nfo, ds_store
copy-to = 
move-to = 
delete-original = True
process-same-extensions = False
bypass-if-copying-all = False
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]

[Permissions]
chmod = 0644
uid = -1
gid = -1

[Metadata]
relocate-moov = True
full-path-guess = True
tag = True
tag-language = eng
download-artwork = poster
sanitize-disposition = 
strip-metadata = False
keep-titles = False

[Video]
codec = h264, x264
max-bitrate = 0
bitrate-ratio = 
crf = -1
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = False
max-width = 0
profile = 
max-level = 0.0
pix-fmt = 
prioritize-source-pix-fmt = True
filter = 
force-filter = False

[HDR]
codec = 
pix-fmt = 
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = 
codec-parameters = 
filter = 
force-filter = False
profile = 

[Audio]
codec = ac3
languages = 
default-language = 
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 128
variable-bitrate = 0
max-bitrate = 0
max-channels = 0
filter = 
profile = 
force-filter = False
sample-rates = 
sample-format = 
copy-original = False
copy-original-before = False
aac-adtstoasc = False
ignored-dispositions = 
unique-dispositions = False
stream-codec-combinations = 

[Audio.Sorting]
sorting = language, channels.d, map, d.comment
default-sorting = channels.d, map, d.comment
codecs = 

[Universal Audio]
codec = aac
channel-bitrate = 128
variable-bitrate = 0
first-stream-only = False
move-after = False
filter = 
profile = 
force-filter = False

[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

[Subtitle]
codec = mov_text
codec-image-based = 
languages = 
default-language = 
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
embed-subs = True
embed-image-subs = False
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
unique-dispositions = False
attachment-codec = 

[Subtitle.Sorting]
sorting = language, d.comment, d.default.d, d.forced.d
codecs = 

[Subtitle.CleanIt]
enabled = False
config-path = 
tags = 

[Subtitle.Subliminal]
download-subs = False
download-hearing-impaired-subs = False
providers = 

[Subtitle.Subliminal.Auth]
opensubtitles = 
tvsubtitles = 

[Sonarr]
host = localhost
port = 8989
apikey = 
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False

[Radarr]
host = localhost
port = 7878
apikey = ***********
ssl = False
webroot = 
force-rename = False
rescan = True
block-reprocess = False

[Sickbeard]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[Sickrage]
host = localhost
port = 8081
ssl = False
apikey = 
webroot = 
username = 
password = 

[SABNZBD]
convert = True
sickbeard-category = sickbeard
sickrage-category = sickrage
sonarr-category = sonarr
radarr-category = radarr
bypass-category = bypass
output-directory = 
path-mapping = 

[Deluge]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
host = localhost
port = 58846
username = 
password = 
output-directory = 
remove = False
path-mapping = 

[qBittorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
action-before = 
action-after = 
host = localhost
port = 8080
ssl = False
username = ***********
password = ***********
output-directory = 
path-mapping = 

[uTorrent]
sickbeard-label = sickbeard
sickrage-label = sickrage
sonarr-label = sonarr
radarr-label = radarr
bypass-label = bypass
convert = True
webui = False
action-before = 
action-after = 
host = localhost
ssl = False
port = 8080
username = 
password = 
output-directory = 
path-mapping = 

[Plex]
host = localhost
port = 32400
refresh = False
token = ***********



**Log files**
2022-04-22 17:12:10 - qBittorrentPostProcess - INFO - qBittorrent post processing started.
2022-04-22 17:12:10 - resources.readsettings - INFO - C:\Python310\python.exe
2022-04-22 17:12:10 - resources.readsettings - INFO - Loading config file C:\Media Server\sickbeard_mp4_automator-master\config\autoProcess.ini.
2022-04-22 17:12:10 - qBittorrentPostProcess - ERROR - No valid label detected.
2022-04-22 17:12:10 - qBittorrentPostProcess - ERROR - Unexpected exception.
Traceback (most recent call last):
  File "C:\Media Server\sickbeard_mp4_automator-master\qBittorrentPostProcess.py", line 50, in <module>
    sys.exit(1)
SystemExit: 1

**FFMpeg headers**
ffmpeg version N-106643-g70db14376c-20220422 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.533_681aaef)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20220422
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 26.100 / 59. 26.100
  libavformat    59. 22.100 / 59. 22.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 33.100 /  8. 33.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
Hyper fast Audio and Video encoder

**System Information**
 - OS: Windows 10 Pro Version:21H2
 - Python version: 3.10
 - qBittorrent v4.4.2

**Expected behavior**
Expect script to recognize label and pass on properly to Radarr[
![Screen Shot 2022-04-22 at 5 37 44 PM](https://user-images.githubusercontent.com/46031113/164817600-82ee5926-d9c1-4516-bccd-0b566aa07e59.png)
[](url)](![Screen Shot 2022-04-22 at 5 38 39 PM](https://user-images.githubusercontent.com/46031113/164817602-72bb527a-958d-4ff9-9acd-3a6bf7c79fac.png))
