### ISSUE TITLE
[Feature] Account for subtitles with RTL reading and convert them accordingly

### ISSUE THREAD

**Issue by VXsz** [mdhiggins/sickbeard_mp4_automator#1517]
Languages that are RTL sometimes have the wrong "orientation" 

for example, in English, imagine lines looked like this
```
Hey, where's Bob -
stop -

!Where is my supersuit
```
This is how the wrong it looks when RTL language are set to LTR

basically stuff will look like this when the translator doesn't account for the right RTL/LTR, I know this is might be on the lazy side (and kinda on me to do) but it would be actually cool and save so much time if it gets implemented, subtitlesedit can do it in one line I think

**Comment by mdhiggins** [comment]
The script really doesn't have any capacity to do this unless it's something FFMPEG can offer. If there's a way FFMPEG can reverse subtitles I'm happy to try to integrate this but other than maybe using AAS subtitles instead of SRT I'm not sure how to go about this. If you can provide a sample of how you've approached this I can take a look.

Is there a python program that offers this?

**Comment by VXsz** [comment]
I actually don't know as I haven't checked if there are python libs, but I know subtitleedit (calling the exe through cli) works well for it
