### ISSUE TITLE
SSA/AAS subtitles configuration problem?

### ISSUE THREAD

**Issue by Protektor-Desura** [mdhiggins/sickbeard_mp4_automator#1528]
I am clearly doing something wrong. If I leave "codec-image-based = " blank then it seems to try and convert ALL subtitles to VTT.

Can you reliably convert ASS to VTT/SRT? I notice that the converted subtitles were all hosed on videos with ASS subtitles. They had all kinds of information that wasn't actually the words being spoken. Because I notice that the VTT subtitles were all hosed on videos with ASS subtitles originally. They had all kinds of information that wasn't actually the words being spoken.  

Because I was having issues I decided forget it, I'll just save the ASS subtitles to the container (MKV), and then things went further downhill from there. I wanted to convert all text subtitles to VTT, given that wasn't reliable I said okay, keep all ASS subtitles and convert all graphic subtitles to ASS unless there is a better supported graphic subtitle option. If I put in "codec-image-based =  ass" then the files get deleted. 

So clearly I am doing something wrong.

The anime I am trying to get tagged and change the audio on is "World's End Harem" but also running in to this with other anime as well.

Totally different note

I eventually want to convert everything to VP9 unless it is AV1. But currently I am only copying the video file. Could you look at my video setup and see if I set it up properly to eventually convert everything to 10Bit and HDR 10Bit? It should be:
10-bit 4:2:0: yuv420p10le

based on:
https://trac.ffmpeg.org/wiki/Chroma%20Subsampling

I assume this is probably the most compatible version of 10Bit for Amazon Firestick and Google Android and Google Android TV? I only use Amazon Firestick, Android tablets and phones and Google Android TVs.

Here is my config file. I just removed my OpenSubTitle login/pass and my API-Keys.
[autoProcess.txt](https://github.com/mdhiggins/sickbeard_mp4_automator/files/7998745/autoProcess.txt)

**Comment by mdhiggins** [comment]
ASS isn't an image based codec that's probably your primary issue, try `codec = webvtt, ass`

http://matroska.sourceforge.net/technical/specs/subtitles/ssa.html for reference

As far as your video question, its complicated

I would think h264/hevc are going to be your most compatible and widely supported codecs with AV1 and VP9 being more niche formats but admittedly the only android TV device I use is the shield which is pretty much compatible with everything. Most sources will alt come in one of those 2 formats aside aside from older bluray rips if you're doing that yourself.

You won't be able to and shouldn't try to convert non 10bit sources to 10bit its just a waste of space and you can't create data where it doesn't exist, though I'm not sure that's exactly what you're asking. The best policy for HDR and high-quality sources is to always try to remux and find them in sources that are already in the current format when possible and only convert for outliers.

Right now I see you're blind copying everything that doesn't meet HDR criteria which is fine I suppose, though with that being said none of the checks will be able to do anything since copy is the only codec is has to work with. For example it doesn't matter what pix-fmt or profile you have set under the [Video] section since regardless the answer will always be `copy` and copy doesn't listen to any options, it just remuxes as is.

You have a mistake in your [HDR] codec options. `vp` isn't a valid codec and will never be reported by FFPROBE. You need to change that to `vp9`.

The general summary of what the script does is that it will copy if all your criteria are met, and will convert if criteria is not met, and when converting it will choose the first option on your list (first codec, first pix-fmt etc)
