### ISSUE TITLE
Cant do video copy hevc to hevc and only audio convert to ac3/aac....its converting video as well to h264 as default

### ISSUE THREAD

**Issue by jahmac23** [mdhiggins/sickbeard_mp4_automator#1529]
Hi, source file 4k hevc eac3 audio. I am trying to convert only audio to ac3 and aac from eac3 audio on a 4k video hevc and want to keep hevc as video copy but its keep on trying to convert video as well to h264 as default. In autoprocess.ini file video codec = hevc, h265, x265 but when I run manual.py it keeps on converting hevc video to h264 video as well. How do I setup video copy and only audio convert to ac3 and aac audio.

**Comment by mdhiggins** [comment]
It shouldn't be trying to convert to h264 if your first codec is hevc. It should also just copy as long as you don't have another setting preventing that

Can you post the log of the attempted conversion? And post your autoProcess.ini

**Comment by jahmac23** [comment]
ok thanks I will post here later. But I am just confusing why manual.php file doesnt affect at all on any change on autoprocess.ini file. Even after I fresh downlaoad and without any change on autoprocess.ini.sample file....without even renaming to autoprocess.ini if I run manual.py file it still converts to mp4 with default h264. Looks like manual.php file doesnt even need autoprocess.ini and even any change on autoprocess.ini it ddooesnt affect. it still does its default. I may be missing something.

**Comment by mdhiggins** [comment]
No PHP files in this script :P

If you don't provide an autoProcess.ini file it will generate a default one for you so if you were just editing the sample that won't do anything the sample is just that, a sample

It absolutely needs autoProcess.ini though its just generating one using the default options if not provided

In fact, if you pay attention to the startup text on manual.py it'll tell you what its doing, here is what it says when you launch it without any config file

```
Manual processor started.
Python 64-bit 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)].
Guessit version: 3.1.1.
C:\Program Files\Python39\python.exe
Loading default config file.
Loading config file C:\Users\***\GitHub\sickbeard_mp4_automator\config\autoProcess.ini.
Config file not found, creating C:\Users\***\GitHub\sickbeard_mp4_automator\config\autoProcess.ini.
Enter path to file:
#:
```

It tries to load the config file from the default location and then creates one because it does not exist. You'll also want to make sure the file you're editing matches that path that's reported

**Comment by jahmac23** [comment]
Thank you so much. its fixed. my issue was I didnt put autoprocess.ini on /config folder. I only put on /setup folder. thats why it was using default autoprocess.ini from /config folder. thank you so much. its sorted now.
