### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by panaris** [mdhiggins/sickbeard_mp4_automator#1533]
**Describe the bug**
An error occurred trying to start process 'python.exe' with working directory 'C:\WINDOWS\system32'. The system cannot find the file specified. Whe try to setup connection to sonarr and radarr.

**System Information**
 - OS: Windows 11
 - Python version 3.10.2

**Autoprocess.ini**
[Sonarr]
host = localhost
port = 8989
apikey = ****
ssl = False
webroot = /sonarr
force-rename = False
rescan = True
block-reprocess = False

**Screenshots**
https://bit.ly/3uJBU2v
https://bit.ly/3uC5oiQ
https://bit.ly/3oFSkFj
https://bit.ly/34wBUbw

**Comment by mdhiggins** [comment]
Looks like Python isn't installed properly or is missing some file associations on windows

Does manual.py run?

Can you run a python script by double clicking it? (not python.exe per se)

Does a python script run from the command line? (not python.exe per se)

Try reading through this; might be a file association or PATH problem

https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-so-it-finds-my-modules-packages

One thing you can do is create a batch file to point things to the correct python executable

Also since python is installing in system32 there's the possibility this is a permissions issue as well

Overall though this looks like a python installation and configuration problem; the script is never executing, your python installation if failing before any code is touched so you'll need to do some python troubleshooting

Example batch file you can try (and then point Sonarr/Radarr to the batch file instead)

```
C:\Python\Python.exe C:\mp4Automator\postSonarr.py
```

**Comment by panaris** [comment]
Python script doubleclicking works, though if I want to run a python script correctly, it seems that I have to do it with python3 instead of python command. This is weird because I have no other python installed. I think all these are caused by the windows store python installation. Anyway, pointing to custom batch file worked but I won't be using sma in the end because of no proper compatibility with amd gpus. I'll stick with handbrake for now. Thanks for your time,
