### ISSUE TITLE
request: custom method to skip encoding

### ISSUE THREAD

**Issue by eikowagenknecht** [mdhiggins/sickbeard_mp4_automator#1539]
**Is your feature request related to a problem? Please describe.**
Some hevc 10bit videos are tried to be encoded, but vaapi doesn't support it, failing with:

```
[Parsed_scale_vaapi_2 @ 0x55822b8a5680] Hardware does not support output format yuv420p10le.
[Parsed_scale_vaapi_2 @ 0x55822b8a5680] Failed to configure output pad on Parsed_scale_vaapi_2
```

In:
```json
    "video": {
        "index": 0,
        "codec": "hevc",
        "bitrate": 8066898,
        "pix_fmt": "yuv420p10le",
        "profile": "2",
        "fps": 23.976023976023978,
        "framedata": {
            "pix_fmt": "yuv420p10le",
            "color_space": "bt709",
            "color_primaries": "bt709",
            "color_transfer": "bt709"
        },
        "dimensions": "1920x1080",
        "level": 4.0,
        "field_order": "unknown"
    },
```

Out:
```json
    "video": {
        "codec": "h265vaapi",
        "map": 0,
        "bitrate": 6000,
        "crf": 23,
        "maxrate": "10m",
        "bufsize": "24m",
        "level": 0.0,
        "profile": null,
        "preset": null,
        "pix_fmt": "yuv420p10le",
        "field_order": "unknown",
        "width": null,
        "filter": null,
        "params": null,
        "framedata": null,
        "title": "FHD",
        "debug": "video.max-bitrate",
        "device": "sma"
    },
```

autoProcess.ini
```ini
[Converter]
postopts = 
hwaccel-decoders = h264_vaapi, hevc_vaapi, mjpeg_vaapi, mpeg2_vaapi, vp8_vaapi, vp9_vaapi
post-process = False
ignored-extensions = nfo, ds_store
temp-extension = 
ffmpeg = /usr/local/bin/ffmpeg
preopts = 
minimum-size = 0
delete-original = True
ffprobe = /usr/local/bin/ffprobe
force-convert = False
output-extension = mp4
hwaccels = vaapi
output-directory = 
process-same-extensions = False
threads = 0
move-to = 
copy-to = 
output-format = mp4
sort-streams = True
detailed-progress = True
hwdevices = vaapi:/dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi
wait-post-process = False
bypass-if-copying-all = False
opts-separator = ,
regex-directory-replace = [^\w\-_\. ]
[Video]
profile = 
crf-profiles = 0:23:5M:15M,4000:23:10M:24M,8000:23:20M:60M
codec = h265vaapi, hevc, h265, x265, x264, h264
crf = -1
max-width = 0
max-bitrate = 6000
pix-fmt = nv12, yuv420p, yuv420p10le
max-level = 0.0
filter = 
force-filter = False
codec-parameters = 
preset = 
dynamic-parameters = False
bitrate-ratio = 
```

**Describe the solution you'd like**
In #1385 you introduced the custom function `blockVideoCopy` so that I could **force** encoding of x264 10bit videos.
Maybe a solution to this is a `blockVideoTranscode` option, working exactly the other way?

**Describe alternatives you've considered**
I could remove 10bit alltogether (yuv420p10le) bit since my TV supports playing those (10bit HEVC at least) I'd rather not. Not sure if that would even work.

I could also ser max-bitrate to something way higher so the file would not need to be encoded. But for other formats that can be encoded I enjoy having smaller files.

An alternative could also be to disable vaapi for just those files and use cpu transcoding instead. Not sure how this would be implemented here.

**Comment by eikowagenknecht** [comment]
Maybe transcoding does not need to be skipped but use another ffmpeg command? I just found out that

... -vf "format=yuv420p10le|vaapi,hwupload,scale_vaapi=format=yuv420p10le" ...

results in the error while 

... -vf "format=nv12|vaapi,hwupload" ...

seems to work (
in: Video: HVC1 1920x1080 23.976fps [V: hevc main 10 L4.0, yuv420p10le, 1920x1080 [default]]
out: Video: HVC1 1920x1080 23.976fps 5594kbps [V: FHD (hevc main 10 L4.0, yuv420p10le, 1920x1080, 5594 kb/s)]
)

But honestly I have no idea about ffmpeg filters and was just trying to get rid of the "yuv420p10le" I saw in the error message ;-)

**Comment by mdhiggins** [comment]
Seems like you need to just remove that pixfmt from your allowed list and use a different one. 

A lot of this can also be handled via the HDR options

Looks like you're just moving things from hardware to software shuffling those codecs around and then reuploading to hardware sort of negating your VAAPI benefits

**Comment by eikowagenknecht** [comment]
In https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1300#issuecomment-674547729 you wrote that both formats should be on the list to prevent reencoding. Sind I don't want to reencode HEVC 10bit (unless the bitrate is too high), I have yuv420p10le on that list (at the end). Is that not correct any more?

**Comment by mdhiggins** [comment]
In general the script attempts to maintain the existing pixfmt as converting between different formats can cause problems and color issues and it's gets tricky automating conversion between them. It behaves differently than codecs. 

What is the end goal for your media conversion? Having a pixfmt that your hardware encoder doesn't support will definitely introduce errors it seems like you're trying to reduce bitrate mostly

I suppose I could include an option to attempt to preserve the source pixfmt versus using the first on the list. That would let you include it but not use it for conversion.

I also might be able to read the supported pixfmt options by querying FFMPEG though not sure how helpful that would be since I don't think it reports encoder specifics I'll have to research that.

**Comment by eikowagenknecht** [comment]
> What is the end goal for your media conversion?

That's a very good question and got me thinking. It could previously probably be summed up like this:
"Just use whatever source there is as long as it's supported by my TV (264 8bit, 265 8bit, 265 10bit). If the source has a ridicoulous bitrate, convert to hevc with a good but not over-the-top quality."

I defined "ridiculous bitrate" as anything >6000 for the video part.

But thinking of it, it usually doesn't really matter as I have only used half of the 20TB my NAS is equipped with and my devices have at least 100Mbit capabilities. So probably I can just go with max-bitrate = 0 and be done with it. Will try how that works for me.

**Comment by mdhiggins** [comment]
My personal strategy is to avoid transcoding video at all costs. Unless I'm encountering an unplayable format, I try to remux as much as possible. Any sort of conversion is going to degrade quality to some degree even without capping bitrate (and more so if capping bitrate) and I aim to try to preserve the quality of the original source as best as possible especially for things like 4K HDR content where I'm using more storage space because I want that higher quality. It's always a good rule of thumb to try and get things in a source format that's close to what you want. Transcoding audio is generally not as big of a deal and creating an extra audio stream for compatibility and keeping an 'original' is a more viable strategy without wasting a ton of space unlike for video

I also have 2 separate instances of Radarr running in parallel, one for standard stuff and one for my 4K bluray rips so I can have varying degrees of quality. On the 4K Radarr instance I keep the MKV container, remux everything, and just filter out languages I don't need.  These are for things I intended to play on my home theater with ATMOS/4KHDR playback

I have a 2nd Radarr instance that contains most of my other movies in lower quality that I convert to more streaming friendly formats for watching on lesser quality setups/mobile etc where I convert to mp4 h264/ac3

Anyway

db52f28708f4e20db8addd42cc245a12071df813

That includes a new option `prioritize-source-pix-fmt` which defaults to `True`

If you set that to `False` then the script will use the first option on the list more like codecs and should give you the control you want

Another option available:

The custom "validation" method (https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Custom-Functions) can be used to intercept the script settings and run custom logic and change settings before the FFMPEG options are generated

You could for instance here detect some aspect of the codec/pix_fmt and make dynamic changes to your settings to achieve more granular control

Here is an example where if trueHD is present the output format/extension are changed to mkv
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1541

**Comment by eikowagenknecht** [comment]
Thank you again for your amazing support and the insights of how you use radarr personally. I've been using the max-bitrate=0 setting now for a week and I think I'll stick with it, converting only the few files that my TV unfortunately doesn't support. Closing this now :-)
