### ISSUE TITLE
ffmpeg/ffprobe path in autoprocess.ini changed

### ISSUE THREAD

**Issue by tjfriese** [mdhiggins/sickbeard_mp4_automator#1554]
I had an open issue last week related to files being created without sound. I solved this by updating the paths for ffmpeg and ffprobe. Today I found another file created without sound and noticed that the paths for ffmpeg and ffprobe had reverted. Any idea why this is happening or how to prevent it from happening in the future?

**Comment by mdhiggins** [comment]
Unless you're using docker the script won't be modifying your FFMPEG paths?

I'm not even sure what this means

**Comment by mdhiggins** [comment]
What was your before/after?

**Comment by tjfriese** [comment]
I modified the paths to: "/volume1/@appstore/ffmpeg/bin/ffmpeg" and "/volume1/@appstore/ffmpeg/bin/ffprobe" the paths reverted to "ffmpeg" and "ffprobe"

I am running sonarr in docker. I am testing right now by removing my /usr/local/sma path from docker that pointed to sma directory. Does that make sense?

**Comment by mdhiggins** [comment]
Not sure why you would approach it that way.

Again operating on limited information here since you posted so little and dodged the templated info on all previous issues but assuming you're using one of the official docker containers, the container automatically makes configuration changes to autoProcess.ini via the included update.py file (part of the docker containers, not part of SMA). Seems like you're trying to get some alternate FFMPEG binary into the container in some fashion or another (I'm guessing this is where the issue with your previous FFMPEG build stemmed from since the included builds should support all those libraries that were disabled on your previous issues)

If you want to sub in an alternate version of FFMPEG, you can either adjust the FFMPEG URL via the SMA_FFMPEG_URL environment variable or if you just have alternate binaries you want to use, just replace the existing ones by mounting them using docker volumes, the setup portion of the script only pulls/downloads FFMPEG if it's not found

The SMA_FFMPEG_URL will only change things on first launch though, you can reference the startup script to see how that's handled (\etc\cont-init.d\90-sma-config). This is also where the update.py file is called that makes the configuration changes

If you're using a custom made docker container or a different docker container other than sonarr-sma/radarr-sma/sma-mod then none of  this applies
