### ISSUE TITLE
Losing subtitles after conversion

### ISSUE THREAD

**Issue by reddragonguy** [mdhiggins/sickbeard_mp4_automator#1556]
**Describe the bug**
I have an anime file that is being converted from `mkv` to `mp4`.  It seems like after conversion though, the `mp4` doesn't have the subtitles anymore.

**Command or context you are trying to run**
n/a

**autoProcess.ini settings**
attached
[autoprocess.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/8207965/autoprocess.log)

**Log files**
Include log files *for the specific job (not just a dump of all your logs for the past month)* that's causing the issue. Please turn on [debug level logging](https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/Debug-Level-Logging)
Log files are found in your script root config folder `./sma/config/sma.log`
[sma.2.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/8208055/sma.2.log)

**FFMpeg headers**
Run ffmpeg and post the headers, example [headers]https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/FFMPEG-Headers

**System Information**
 - OS: docker
 - Python version
 - Docker config (if relevant)

**Expected behavior**
to be able to view file in plex with subtitles.

**Additional context**

*Issues posted without any logs or autoProcess settings will be closed*

**Comment by mdhiggins** [comment]
Much better, now I can see info about the source file and your settings

Looks like this is because your source file subtitle language is 'und' or undefined

If you set 

```
[Subtitle]
default-language = eng
```

it will assume undefined subtitles are English and then you should get the import behavior you're looking for

**Comment by reddragonguy** [comment]
thanks, that helped.  One final question, is there something that controls the size of subtitle?  They are very large even after I set the subtitle display to "tiny" inside of plex. 

![image](https://user-images.githubusercontent.com/71977193/157293832-81b96fab-8477-45f6-9d45-b9c367c10f60.png)

**Comment by mdhiggins** [comment]
You'll have to upload to some cloud service and send me a link via email and I can take a look.

**Comment by reddragonguy** [comment]
on their way and thanks!

**Comment by mdhiggins** [comment]
Hm so those files were very helpful

It looks like FFMPEG continues to carry some of the HTML font size tags over to the mov_text conversion which is inflating the font sizes probably because the actual fonts are now gone (MP4 doesn't support embedded fonts)

Only way around this since FFMPEG doesn't support filtering that data is to temporarily extract the subtitles from the source, clean them, and then merge them back into the final output file

012d8931a1ce30759e87b7759ffa0e8c5280a333

That update adds support for that feature

I'll update the wiki shortly but please test it out and see if it works

It requires a new python library called `cleanit` to handle cleaning up the subs but has the added benefit of also removing things like ads and formatting issues so that's nice. I've been wanting to implement subtitle cleaning for a while so this was a nice motivator

`pip install cleanit` should get that dependency installed

Then, next time you run the script a new settings section will be created, please run manual.py, close it, and then update that section to include settings like this

```
[Subtitle.CleanIt]
enabled = True
config-path = 
tags = default, no-style
```

The most important tag there is the `no-style` tag which will remove the leftover html style tags from the ASS subs that's causing your font size issues. This fixed the large subtitles for me

Let me know if you have any issues, biggest things to look out for is .srt files being left behind after creating the new file (delete-original will need to be enabled for final cleanup) and any conversion errors from the extraction and remerging process

The ability to clean the subs will only apply to text-based subtitles

**Comment by reddragonguy** [comment]
sorry, but how do i pull down the latest.  I currently use your docker images

**Comment by mdhiggins** [comment]
The containers should be updated now

**Comment by reddragonguy** [comment]
everything seems great now.  Thank you!

**Comment by mdhiggins** [comment]
Nice, updated the wiki with the new settings thanks for checking
