### ISSUE TITLE
RAMDISK integration for ffmpeg

### ISSUE THREAD

**Issue by henryjb99** [mdhiggins/sickbeard_mp4_automator#1559]
Is it possible to setup the ffmpeg used by the docker instance to use a ramdisk when transcoding? This would help speed up transocding significantly.

**Comment by mdhiggins** [comment]
It probably wouldn't cause you still need it to end up on the HDD at some point, you're not transcoding for playback but yeah you can set whatever you want your working directory to be using `output-dir` option including the ramdisk

**Comment by mdhiggins** [comment]
1e81e44b2e9cb77049cbc7661190c06a09f85f70

Added a small option to make restoring the original directory easier too

Set your `output-directory` to your ramdisk and set `temp-output` to True and this will restore the file when processing is done to its final destination

Not sure if this will save you any time since everything needs to go to the drive for final storage anyway but at least you can test it out this way.
