### ISSUE TITLE
Jellyfin/Emby support?

### ISSUE THREAD

**Issue by Yankees4life** [mdhiggins/sickbeard_mp4_automator#1564]
Is there a way to implement jellyfin support? I want to setup a server refresh via api after I convert a file. I'm a little stuck on the postproceesing script. Am I support to use batch or python?

**Comment by mdhiggins** [comment]
The Plex refresh is mostly maintained for legacy reasons, it would be better to just use the post-process feature for these refreshes and eventually I'll probably drop the plex refresh in favor of using the PP solution

749a7aae16a983a926b9971e9df6e64b5335eb7a

That adds samples for all 3, haven't tested them though since I don't have an active Jellyfin or Emby setup but you should be able to add your credentials to those and just run them to see if they work since they are standalone scripts
