### ISSUE TITLE
How to handle downloaded subtitles

### ISSUE THREAD

**Issue by m33ts4k0z** [mdhiggins/sickbeard_mp4_automator#1579]
Hello again,

I'm having another question and I couldn't find the answer online. 

I want to embedd subtitles. Since I use Bazarr to download subtitles, I wonder how could I run the script after this happens? Because having the shell script running after Radarr's import event is to early and running it after Bazarr's subtitle download event is very ineffective since this event runs after every download. 

Is there a solution to this? I tried adding sleep in the sh file but radarr wait's for the script to finish before signaling to Bazarr.

If I could wait for like 2-3 minutes after bazarr picks up the movie in order to run the script it would be perfect.

Thank you

**Comment by mdhiggins** [comment]
No good solutions for direct Bazarr integration that doesn't break existing workflows; that's sort of why the script integrates with subliminal and cleanit to pull in and sanitize the subtitles before the conversion takes place and you could try using that option

I'm open to suggestions if you think there's a way to leverage the Bazarr API to wait or trigger a rerun, otherwise a scheduled script that ran periodically and uses manual.py could merge external subtitles with video files is a solution I've seen others use
