### ISSUE TITLE
ModuleNotFoundError: No module named 'mutagen.mp4'

### ISSUE THREAD

**Issue by tjfriese** [mdhiggins/sickbeard_mp4_automator#1627]
I'm running the Sonarr with SMA docker and a locally installed SABnzbd on a Synology NAS. I have a locally installed ffmpeg that I hope to have SABnzbd call to take advantage of hardware acceleration for quicker conversions to mp4 files.

I've been through the python requirements. However, SABnzbd is not detecting Mutagen (as per the title of this post). It is detecting the other pip modules. I believe this to be due to the various pythons that seem to be installed. I have looked at the various pythons and it seems like mutagen is installed where they are (verified by running the various pips that I have accessible and confirming that they show mutagen installed).

Is there a way to troubleshoot something like this?

**Comment by mdhiggins** [comment]
This is more of a generic python question asking how do I determine which environment I'm in and subsequently install dependencies to that environment. There's a million posts about this but you can run a very simple python script to see, settings.py in this script actually logs it too cause this is a common problem for people who aren't familiar with python

```py
import sys
print(sys.executable)
print(sys.prefix)
```

That should tell you which python environment you're under and you'll need to install the dependencies on that environment or redirect SAB to use the correct environment you've already installed under

SAB should also respect the shebang at the top of your python files so you may just need to modify that for SABPostProcess.py to direct it to whatever python executable you've installed your dependencies under

Or the python recommended solution would be to install all this stuff under a virtual environment and direct SAB to that instead of whatever python environment its using as default

For my docker containers and the docker mod (which works with the linuxserver SAB container) I explicitly create the virtual environment, install all dependencies under that, and then use a wrapper that looks like this

```bash
#!/usr/bin/env bash

# env check
if [[ -z "${SMA_PATH}" ]]; then
    export SMA_PATH="/usr/local/sma"
fi

$SMA_PATH/venv/bin/python3 $SMA_PATH/SABPostProcess.py "$@"
```
