### ISSUE TITLE
Covert 10bit to 8bit if it see it be no other ones

### ISSUE THREAD

**Issue by Whereamnow** [mdhiggins/sickbeard_mp4_automator#1644]
So my TV with Chromecast still has trouble seeing 10bit. (causes artifacts). Is there a way to convert 10bit to 8bit but skip everything else that is not 10bit?

**Comment by mdhiggins** [comment]
The script always attempts to remux files without conversion, just set up autoProcess to include the 8 bit pix fmts and codecs you want and leave the 10-bit ones off the list and then it will convert

**Comment by Whereamnow** [comment]
is that under [Video] or do i also have to change [HDR] too?

**Comment by mdhiggins** [comment]
The HDR section allows to you set profiles that are considered 'HDR' and then have alternative options applied in that context, you could do this if you wanted or your could just blank out that whole section since you don't really want special treatment for HDR files, you want to convert everything to SDR essentially

The script determines if something qualifies as HDR based on the space, transfer, and primaries options in the HDR section, so if those are blank the other HDR level options won't be applied
