### ISSUE TITLE
blockAudioCopy

### ISSUE THREAD

**Issue by screamjojo** [mdhiggins/sickbeard_mp4_automator#1656]
Hello,

Can you explain how "blockAudioCopy" work in custom.py ?

I've write : 

```
def blockAudioCopy(mp, stream, path):
    # Custom function that skips HDR files that are missing proper HDR metadata / framedata
    mp.log.info("Initiating custom audio copy check method.")
    if stream.type == "audio" and stream.metadata.get('language') == 'fra' <=2 and "vfq" in stream.metadata.get('title', ''):
        return True
    return False
```

But don't work, so I don't thinks it's the good approach ...
Thanks for your time and your help.

**Comment by mdhiggins** [comment]
You have some nonsensical code in there, particularly a random `<=2` that's probably throwing an exception

```
def blockAudioCopy(mp, stream, path):
    # Custom function that skips HDR files that are missing proper HDR metadata / framedata
    mp.log.info("Initiating custom audio copy check method.")
    if stream.type == "audio" and stream.metadata.get('language') == 'fra' and "vfq" in stream.metadata.get('title', ''):
        return True
    return False
```

**Comment by screamjojo** [comment]
Thanks for your reply but don't work,
I need `<=2` because I want to block the audio stream wich contains the word "vfq" only if there are another "fra" stream language...
Maybe I must use skipStream for that ?

**Comment by mdhiggins** [comment]
I mean regardless of what you need throwing a random <=2 isn't valid Python; its not going to work

blockAudioCopy is also probably not what you want, since its still going to let the track be created its just going to impact whether the stream is transcoded versus remuxed

skipStream is probably what you want and you need to write some more complex logic to determine if that stream is the first one that meets your criteria or not


I haven't tested this code but this might do what you want, might need to tweak it a little bit

```py
def skipStream(mp, stream, info, path, tagdata):
    # Custom function that skips over a stream
    mp.log.info("Initiating custom stream skip check method.")
    fra_vfq_audio_streams = [a for a in info.audio if a.metadata.get('language', '') == 'fra' and 'vfq' in stream.metadata.get('title', '')]
    if stream in fra_vfq_audio_streams:
         return (fra_vfq_audio_streams.index(stream) != 0)

    return False
```

This collects all your audio streams with language 'fra' and 'vfq' in the title into an array `fra_vfq_streams`, it then looks to see if the particular streams you're checking is part of that array. If it is, it only returns False (aka 'Don't Skip') if that is stream 0 on that list (the first stream) all others will return True and skip

**Comment by screamjojo** [comment]
> Are you going from MKV to MP4 container? MP4 doesn't support the forced disposition tag

Mkv to mkv
If my files contains a forced audio disposition the vfq track is not ignored...

**Comment by mdhiggins** [comment]
Gonna need to see the conversion logs and your autoProcess.ini file to help further

**Comment by screamjojo** [comment]
> Gonna need to see the conversion logs and your autoProcess.ini file to help further

I'm sorry, your code work great, it's my fault, I've changed the fake custom file (into setup)...

Thanks again for your help and your time, very appreciated :)
