### ISSUE TITLE
is not in a valid format

### ISSUE THREAD

**Issue by VampiricAlien** [mdhiggins/sickbeard_mp4_automator#1657]
Howdy,

Script fails to tag media if minimum-size = is below set limit.

minimum-size = 1500 (1.5gb)

command: ` /manual.py -to ` will return ` is not in a valid format` error when video path has been entered because it's below the set limit of 1.5 GB

"Minimum file size in megabytes. Use to ignore small sample files. Set to 0 for no minimum"
I am trying to use it so it will only tag and not change file settings for any file under 1.5 GB

Solution 1
bypass minimum size for tag only (will fail to work if using other post scripts unless they are also updated)

Solution 2
include new minimum process size option, default too 0 (minimum-size can be to ignored and have minimum process size)

I think solution 1 would be the easiest? What do you feel comfortable doing?

**Comment by mdhiggins** [comment]
Purpose of the minimum size is to skip media entirely that the script isn't meant to interact with so it doesn't waste time on things like sample files, whether to just tag the file versus convert/remux uses an entirely different set of logic/options

What's the goal/intention here?

**Comment by mdhiggins** [comment]
I meant what is your practical use case for this. Are you trying to use this to differentiate or filter between files that have vs haven't been processed based on file size?

**Comment by mdhiggins** [comment]
So this workflow isn't ideal and wasn't the intent of the minimum-size option because file size as a measure of quality isn't particularly helpful because it varies so much with content duration. As a best practice, its better to use bitrate and codec to determine if a file should be converted or not, which is supported as part of the main SMA workflow

That being said, if you're running some other scripts to loop manual.py and just wanted an override so you could lower the min size temporarily for tagging purposes, it would be trivial to add a command line parameter to override it. Would that work for what you're trying to do?

**Comment by mdhiggins** [comment]
The command line tag would just be for manual.py, not the post scripts

The command line override would essentially just be the same as temporarily adjusting your minimum-bitrate setting in autoProcess for that one session if that makes sense (without actually changing the ini file)

**Comment by mdhiggins** [comment]
0ed5da3133b5aa2ea00ee6b0badda9ba6d10f2cd

Just added it, `-ms` or `--minsize`

Set to 0 for no minimum
