### ISSUE TITLE
[Question] Seeking

### ISSUE THREAD

**Issue by VampiricAlien** [mdhiggins/sickbeard_mp4_automator#1678]
Sometimes  I can only  watch from the beginning and can’t seek through the video, if I do it starts at the beginning again.

Do you know why or how this would happen? creating a new file fixes the issue. 

   ```
 "format": "matroska,webm",
    "format-fullname": "Matroska / WebM",
    "video": {
        "index": 0,
        "codec": "h264",
        "bitrate": 13586614,
        "pix_fmt": "yuv420p",
        "profile": "high",
        "fps": 25.0,
        "framedata": {
            "pix_fmt": "yuv420p",
            "color_space": "bt709",
            "color_primaries": "bt709",
            "color_transfer": "bt709"
        },
        "dimensions": "1920x1080",
        "level": 4.0,
        "field_order": "progressive"
        

  "format": "mkv",
    "video": {
        "codec": "h265vaapi",
        "map": 0,
        "bitrate": 12909.276399999999,
        "crf": 0,
        "maxrate": null,
        "bufsize": null,
        "level": 5.2,
        "profile": "main10",
        "preset": "veryslow",
        "pix_fmt": "p010le",
        "field_order": "progressive",
        "width": null,
        "filter": null,
        "params": null,
        "framedata": null,
        "bsf": null,
        "debug": "video.profile.pix_fmt",
        "title": "FHD",
        "device": "sma"
        
-vcodec hevc_vaapi -map 0:0 -field_order progressive -metadata:s:v title=FHD -metadata:s:v handler_name=FHD -preset veryslow -profile:v main10 -level 5.2 -tag:v hvc1 -qp 0 -filter_hw_device sma -vf "format=p010le|vaapi,hwupload,scale_vaapi=format=p010le" -c:a:0 copy -map 0:1 -metadata:s:a:0 title=Stereo -metadata:s:a:0 handler_name=Stereo -metadata:s:a:0 language=eng -disposition:a:0 +default-dub-original-comment-lyrics-karaoke-forced-hearing_impaired-visual_impaired-captions -c:s:0 copy -map 0:2 -metadata:s:s:0 "title=Hearing Impaired" -metadata:s:s:0
```

**Comment by mdhiggins** [comment]
Not really enough info to help

I assume the original file that's failing is created with SMA and also creating a new file with SMA fixes it?

Only time I've seen seeking issues is when trying to tag/add metadata AFTER qtfaststart or equivalent MOOV atom has been moved which if you're doing MKV doesn't apply

**Comment by mdhiggins** [comment]
I don't think there's a programmatic way to see if this has occurred if that's what you're asking, but that's tough to say without seeing if there was some problem or error during the conversion process or looking to see if the file is malformed in some way. Usually its a problem with the wrapper and that's why recreating it using FFMPEG copy fixes things but if you have some logs I can take a look and see if anything stands out

**Comment by mdhiggins** [comment]
Everything looks to be proceeding without any major issues (other than the cleanit error which is irrelevant)

I'm curious maybe if you try turning off tagging if that makes any impact but otherwise looks like an appropriate FFMPEG command is generated

**Comment by mdhiggins** [comment]
It will always remux a stream even with hardware acceleration if the stream doesn't break any rules so just add make sure to add the codec and pixfmt to the lists

**Comment by mdhiggins** [comment]
Share your config it shouldn't be your first option. Please review in the wiki

**Comment by mdhiggins** [comment]
If you're getting the error above that means its still not copying, the "debug" tag on the json data usually tells you why its not getting copied

Depending on your specific needs you can also potentially just leave pix_fmt blank

```
IO... p010le                 3             15      10-10-10
```

p010le isn't a hardware accelerated format so that shouldn't be your first choice since you're trying to use VAAPI

`ffmpeg -pix_fmts` will give you a list of your ffmpeg builds supported pix_fmts

You'll also probably need to play around with `prioritize-source-pix-fmt = True` as it might need to be set to false in situations where you need to convert

**Comment by mdhiggins** [comment]
Sharing the full logs would be helpful too
