### ISSUE TITLE
Not tagging movie off of IMDB

### ISSUE THREAD

**Issue by Geordon** [mdhiggins/sickbeard_mp4_automator#187]
Hello, I've got a movie that I'm trying to tag. There is an entry for the movie in IMDB, but not one in TMDB.  This is what happens when I try to manually tag the file:

```
gvantass@Enso ~/Downloads $ /usr/local/etc/SAB_post_process/sickbeard_mp4_automator-master/manual.py
64
Enter path to file:
#: ./Twilight.of.the.Yakuza.x264.720p-VODO.mp4
Unable to determine identity based on filename, must enter manually
Select media type:
1. Movie (via IMDB ID)
2. Movie (via TMDB ID)
3. TV
4. Convert without tagging
5. Skip file
#: 1
Enter IMDB ID:
#: tt3138664
Failed to connect to tMDB, trying again in 20 seconds
'title'
Failed to connect to tMDB, trying again in 20 seconds
'title'
Failed to connect to tMDB, trying again in 20 seconds
'title'
Processing movie
Tagging file :./Twilight.of.the.Yakuza.x264.720p-VODO.mp4
There was an error tagging the file
Relocating MOOV atom to start of file
QT FastStart did not run - perhaps moov atom was at the start already
```

It appears that the script is trying to pull the info form TMDB even though I want to pull data from IMDB.  Since there is no entry in TMDB, it is timing out and failing to tag.  Am I reading this right?  And, is there anything I can do to get around this?

**Comment by mdhiggins** [comment]
This is expected behavior. While the script does identify movies based on either an imdb ID or tmdb ID it does not actually communicate with IMDB at all. All movie data is pulled from tmdb. There aren't any plans to change this in the future as imdbs database doesn't have the same consistency as TMBD. That being said, TMBD is an open database so you could simply add this movie to their database to fix your issue and prevent future users from having the same problem with this title. 

—

**Comment by Geordon** [comment]
Ah, got it.  Thanks for the explanation!
