### ISSUE TITLE
Max bitrate

### ISSUE THREAD

**Issue by xpack90** [mdhiggins/sickbeard_mp4_automator#188]
Is there a way to set the max video bitrate so that if needed ffmpeg can decrease the bitrate so that is can play better with Chromecast and FireTV

**Comment by mdhiggins** [comment]
This feature has been added and the readme has been updated. Look for the new `video-bitrate` setting in the autoProcess.ini file (run manual.py for it to be auto-added). If left blank the script will behave as it did before. If the source video codec is in the right format it will still be copied to avoid quality loss otherwise it will transcode down to the new target bitrate. Give it a shot and let me know if there's any bugs but it seems to be working fine on my end.

**Comment by mdhiggins** [comment]
Since no feedback has been posted I'm gonna close the issue. The feature has been implemented.
