### ISSUE TITLE
SABnzbd+ to Sonar

### ISSUE THREAD

**Issue by KaHooli** [mdhiggins/sickbeard_mp4_automator#201]
What happened to the SABnzbd+ to Sonar script?  This seems to have disappeared.

**Comment by mdhiggins** [comment]
Are you referring to the nzbToSonarrMP4.py file? I don't think its changed in the master branch

**Comment by mdhiggins** [comment]
Additionally, I've been doing a rewrite of the SAB and NZBGet scripts, check out the `nzbget` branch which will be merged into the main branch after some more testing. It consolidates all the post scripts into 2 files (one for SAB and one for NZBGet). You then set your "categories" in SAB or NZBGet to either 'couchpotato' 'sickbeard' or 'sonarr' and that's where the download will be sent. Additionally you can set the `convert` option in autoProcess.ini for SAB under CouchPotato or SickBeard sections to enable conversion before passing the file on.

Any feedback on this is appreciated so I can get the bugs out and merge it into the main branch. Should make setting the script up way easier since it consolidates what would have ended up being potentially 12 different files into 2.

**Comment by mdhiggins** [comment]
This has been merged into the master branch and old script is gone. Use SABPostProcess.py now and set the categories appropriately (see the updated readme if there's any questions).
