### ISSUE TITLE
error with manual.py 

### ISSUE THREAD

**Issue by vinnytr9** [mdhiggins/sickbeard_mp4_automator#204]
Script was running perfect until I cloned the latest commit then the manual.py returns this error: 

Traceback (most recent call last):
File "manual.py", line 18, in <module>
    settings = ReadSettings(os.path.dirname(sys.argv[0]), "autoProcess.ini"
)
File "C:\Users\Vinh\Downloads\Compressed\MP4 Automator\readSettings.py",
line 316, in __init__
    self.uTorrent['convert'] = config.getboolean(section, "convert")
File "C:\Python27\lib\ConfigParser.py", line 370, in getboolean
    raise ValueError, 'Not a boolean: %s' % v
ValueError: Not a boolean:

not sure what the problem is since I didn't change anything.

**Comment by mdhiggins** [comment]
Looks like this is happening because the 'convert' option in the uTorrent settings section is blank and needs to be either True or False. Setting this option should fix the error. Additionally I went ahead and added a new commit that will catch this error in the future and prevent it from crashing the rest of the script. If you update, it should also fix this.
