### ISSUE TITLE
Issues with Tagging

### ISSUE THREAD

**Issue by astlaurent** [mdhiggins/sickbeard_mp4_automator#230]
I am having one small problem where it does not seem to tag any of the files or apply the artwork. Some of the newer movie releases have their own tagging information such as title = visit micromkv.com and when plex see’s this it takes it as gospel and makes that the movie name where I then need to go and fix it. I would think that your script would scrub out this information and apply the proper tagging but it still remains after the conversion. I have the appropriate options set for true in the config file as well.

**Comment by mdhiggins** [comment]
What script are you using to do the tagging? I need more information to help. 



—

**Comment by astlaurent** [comment]
in sabnzb i have the post processing script as sabpostprocess.py
I am using this in windows with python27

**Comment by mdhiggins** [comment]
So post-download scripts don't do any tagging by design. The downloads are 'dumb' and don't have any knowledge of the content you're downloading. Automated tagging is currently supported by Sickbeard/Sickrage (via postConversion.py) and CouchPotato (via the CP plugin in the setup folder). Check the readme for how to set those up. Sonarr does not yet support tagging.

If you want to just manually tag your files, you can do that with manual.py. But no tagging is performed directly from the downloaders (uTorrent/Deluge/SAB/NZBGet)

**Comment by astlaurent** [comment]
ok so it seems to be working better when i put the script in couchpotato.
if i have the script in couchpotato do i still need to have the script in sabnzb as well? it seems to be double converting it now. meaning converts it coming out of sab and then converts it when couchpotato  runs its scripts.

**Comment by mdhiggins** [comment]
The only way you'll run into the double conversion issues is if you have post downloading conversion enabled and the `convert-mp4` option also enabled.

**Comment by astlaurent** [comment]
thank you so much for your help. i think i got almost everything straightened out. i am having one more small problem hoping you might have an idea on. When couchpotato runs its script i get an error during the QTFastStart moov operation basically when it is trying to rename the file from what i believe is from QTFS > MP4 again. the problem is i am using btsync to sync all my movies to another system. so basically as soon as couchpotato drops the movie in the final folder it tries to sync but your script is also trying to do the moov operation. i excluded QTFS from the sync process but it still has issues. The only way i got it to work is disable the moov operation. I know it is not directly related to your script but i am hoping you have a couple ideas. 

Does the extension change to anything else other than QTFS and MP4, maybe i need to exclude something else?
is there a way i can do the QTFastStart coming out of SAB instead of having couchpotato do it in my final folder?
is there a way to do this operation in a temporary folder?
Do i really need to do the moov operation, how much does it really help, should i just leave it disabled?

again thank you so much for your help.

**Comment by mdhiggins** [comment]
What QTFS does essentially is reorder a large portion of data in the file, it reads the mp4 and shuffles thigns around making essentially a copy of all the data in the .mp4 file and puts it into a .qtfs file. When its all finished it deletes the original mp4 then renames the .qtfs to .mp4. 

Unfortunately, the QTFS processing needs to be done after tagging or you run into issues and playback problems, particularly with larger files.

I'm guessing the problem is that BTSync is reading the .mp4 when it gets dropped off and then the script can't delete it to rename the QTFS file. What you could do is have CouchPotato dump things in a folder not managed by BTSync, then set the scripts 'move-to' option in autoProcess.ini to the file destination folder that BTSync handles. Move-to is the very final command execute by the script after everything is complete so QTFS will be finished at that point. The only disadvantage here is that you won't be able to create fancy folders if that's something CouchPotato is doing for you (like putting each movie into its own folder). The other issues is that if you use this script for TV shows as well the move-to option will be applied to them.
