### ISSUE TITLE
CouchPotato not calling script on download completion

### ISSUE THREAD

**Issue by OskarPersson** [mdhiggins/sickbeard_mp4_automator#235]
I'm trying to setup sickbeard_mp4_automator together with CouchPotato but I can't get CP to call SMA when the download is complete.

If I restart CP I can see the following in the log

> 04-05 13:07:53   INFO   [  couchpotato.core.loader] Loaded custom_plugins: PostProcess

**Comment by mdhiggins** [comment]
Do you have the renamer enabled? and is the renamer running when the download completes? If you can send me the part of the log after the file is processed that would be helpful.

Essentially the way it works is that the script piggybacks off the renamer module being run and is execute by the renamer when its finished its task. Therefore the renamer needs to be triggered with by a periodic timed scan (not the best way) or by one of the post-downloader scripts informing couch potato to run a renamer scan.

**Comment by OskarPersson** [comment]
Not sure how it should be, these are my settings right now

![skarmavbild 2015-04-05 kl 21 45 54](https://cloud.githubusercontent.com/assets/935414/6998319/37c22168-dbdd-11e4-8b34-0243737b1cc1.png)

**Comment by mdhiggins** [comment]
Are your downloaded movies renamed and moved to that iTunes folder I see in the screenshot?



—

**Comment by OskarPersson** [comment]
Never mind, it worked if I waited a bit. Thought that CP scanned once every 1 minute but it was once every 1 hour.

**Comment by mdhiggins** [comment]
So ideally, if your autoProcess.ini is setup right and your post downloading script has the appropriate categories set, you shouldn't ever need to `force every` or periodically run the renamer because the script will tell couch potato to do it manually when its all done converting the file. This is the preferred method because it prevents CP from starting a renamer scan in the middle of a file conversion.

Aside from that, is everything working now?

**Comment by OskarPersson** [comment]
Yes
