### ISSUE TITLE
Add To iTunes

### ISSUE THREAD

**Issue by JohnMaree** [mdhiggins/sickbeard_mp4_automator#253]
Hi,

Have tried the method of copying over the converted media file into the Automatically Add To iTunes directory, but that sometimes just fails to work/copy over and renames my files in a way I do not like. It also creates a copy which i then later on have to remove before I have duplicates crowding up my hard drive.

I have done some research and there is a script i found for adding into itunes but i've had nothing but trouble and bad luck trying to run it as an extra script (Keep getting error code 8: Exec format error) and for the life of me cant figure out how to make a script for myself to.

If you have any ways of helping I would much appreciate it.

Thanks, John

**Comment by mdhiggins** [comment]
iTunes is unfortunately a giant headache. If your goal is to have all your media managed by iTunes without additional copies being managed by Sickbeard or CP or whatever, then I would try the following options:

- Determine which drive your `Automatically Add to iTunes` folder resides on
- Set your `output-dir` option in the autoProcess.ini file to by a folder on that same drive, but NOT the automatically add to iTunes folder
- Set your `move-to` directory to the `Automatically Add to iTunes` directory

This means that the files are created on the correct drive, which is important. Then when the move-to function is called its a very quick process since its already on the correct drive. This prevents iTunes from registering partially created files. I think this is your best option.

If you're on Windows ironically, there are some 3rd party programs which can monitor directories and will keep those directories in sync with your iTunes library and still let Sickbeard/CP manage the actual destinations.

**Comment by mdhiggins** [comment]
Here is the windows program:

iTunes Library Toolkit
http://klarita.net/itlt.html

**Comment by grahamr** [comment]
What i have done is: Sickbeard watches/reads the itunes folders but makes no changes/metadata
i have your script dumping into a folder on my machine, and then a scheduled task moving the files to the automatically add to itunes folders.

The only thing i had to do to get SB to "work" this way was to comment out your line to add the season as the disc number and then i do loose some archiving based on release size/quality etc but SB does pickup all episodes correctly.

**Comment by mdhiggins** [comment]
I'm not quite sure I follow

**Comment by grahamr** [comment]
Rather than have your script move the files, i have the scheduled task move them to the auto add folder where itunes then imports.

What i found by default was that itunes would name the episode:
X\Season 2\2-01 XXXXXX (HD).m4v for example.

This resulted in the following error:
2015-05-07 03:03:29 SHOWQUEUE-REFRESH :: No episode number found in Y:\Itunes Music\TV Shows\X\Season 2\2-01 XXXXXX  (HD).m4v, ignoring it

by commenting out the line in the processor that added the season to the disc section it flattted the names to Season 2\01 XXXXXX (HD).m4v and sickbeard lined up correctly.

I played with SB filters and name formats and couldn't for the life of me get one working if the season was in both the folder and the file name.

**Comment by mdhiggins** [comment]
That's interesting I wasn't aware of iTunes naming convention. I had copied the way iTunes metadata was applied when I wrote the tagging for the tv episodes, but if it was confusing Sickbeard then I guess commenting that out isn't a bad idea.

**Comment by mdhiggins** [comment]
John were you able to resolve your issue with either my or grahamr's help?

**Comment by JohnMaree** [comment]
Sorry for not replying. 

No I didn't quite follow grahamrs methods, maybe I'm being dumb. The thing that I'm trying to achieve is complete automation etc and the automatically add to iTunes watch folder that iTunes provides isn't very reliable for me. For 1, I really don't like how it renames the show to something like 02x03 - episode name, and doesn't show you the show itself, and sometimes it doesn't add I to iTunes and pushes it into a folder called not added or something similar. I like the way I have my shows named and all my shows. The move_to function is also a problem because it then creates a copy of the show which is have to delete later. (I feel like I'm not making sense). I am running on a Mac and was sort of close to getting something with the Automator scripts but I don't know... What I don't understand is why there isn't a code we could write that tells iTunes to 'refresh' as the script does with plex? 

I'm sorry if this makes no sense and thus whole thing is a bit confusing to me too 😂

**Comment by grahamr** [comment]
John, from what i have experienced it sounds like what you want to do is enable the Move_to function (it will only create a copy if using torrents) 

from an automated approach, including itunes you will likely need "something" to move and rename the files when finished - Are you using SB as the input source? if so you could point that to the folder with your media, have sickbeard handle the file moving and renaming to it's standard.

from there you would need to have an applescript or automator action that would tell itunes to rescan those folders, or all folders on a certain basis. the windows tool linked can do this, but on the mac side i don't know of anything that does.

Is there a reason you dont like the itunes naming convention?

TV Shows\Show Name\Season S##\E## - EP Title (if there is no "disk number" in the metadata)

Plex and SB will parse that correctly.

**Comment by grahamr** [comment]
this pull request has some basic work done on this already actually:
https://github.com/mdhiggins/sickbeard_mp4_automator/pull/191

**Comment by JohnMaree** [comment]
Hi,

I have tried the move_to function to the automatically add to iTunes folder and that only occasionally worked and yes it did create a copy but there's 2 problems with that; 1 being that I believe that when the script doesn't parse the metadata correctly onto the video file and since iTunes doesn't look at the actual name of the file when automatically importing it, but rather the metadata, it sometimes doesn't add it into the library, and when I then go into the add folder/file to library and manually add it, it adds just fine, which frustrates me! Secondly when it creates a copy of the file, after I've watched the show, I'll have to delete that copy at some stage otherwise it just takes up space on my drive.. 

The problem I have with the naming convention is that I have become comfortable and prefer the naming in the am form of /Show Name/Season %/Show Name - S0%E0% - Episode Name.m4v/ which to me not only makes more sense when I read it but just looks way better and particularly when sharing or fiddling with the files themselves, makes it easier to follow what I'm fiddling with if that makes sense. 

This is directed to both of you wonderful people: Is there no way we can add a line of code or create a script to call in the Extra_scrips function that would say something along the lines of: 
Tell application iTunes 
Add this_file (being the file that was just parsed into the correct season folder with the nice naming) to library 
End tell

?? Note that that may be completely wrong and it's just me thinking. I hope I'm explains this okay. 

Best wishes

**Comment by grahamr** [comment]
John,

I think the issue is sort of twofold - this script just takes Download
input -> output

It doesnt have any sense of managing files/folders.

You need another "middleman" applicaiton that would take the output from
this, spit it out into folders and names with the convention you like, then
you need to add the files to itunes.

there are only two ways right now to automate itunes with this script so
it's totally hands off i can think of:

Option 1:

   - Script output to Auto Add to Itunes folder
   - Itunes set to copy files to library and manage the library folders

Result:
iTunes will import, delete the file from the Auto add folder, and parse it
using metadata into the previous named folders. Sometimes throwing an error
or not categorizeing correctly due to lost metatdata (100% of my marvels
agents of shield fall into this category)

Option 2:

   - Have the script output to a folder - Any folder anywhere
   - Have itunes set NOT to consolodate files, but reference them
   - Have a script run to add any new files in that folder to itunes

Result:
One big folder with all your media, named as they were when downloaded, but
with no folders
To me that would be less ideal than the itunes structure

What you really need though is an application that does the following


   1. Finds show A
   2. Downloads show A
   3. Calls this script to convert the file
   4. Takes the converted file and renames it following your standard
   5. Calls itunes to do an inplace import.


Sickbeard and Sickrage will handle steps 1-4, and im just not sure about
step 5.

That all said, you could use an applicaiton like sickbeard and have it
manage the folderstructure while not enabling any of the download features.

The workflow then would be:


   1. Get file from whatever source
   2. Convert file using script
   3. Have sickbeard rename file according to spec

from there you still need to import with itunes.. which is again, the
sticky point as apple has a very limited API on mac and non-existant on
windows.

For me my workflow is automated up to the last step of importing to itunes.
I want to run a final check to make sure all the metadata feels right - so
i have the script output to a folder, then i load all the files into
something like MP3Tag so i can do a quick check to make sure nothing was
missed.

For the sake of 30 seconds once or twice a week its not too bad.

**Comment by mdhiggins** [comment]
I also think we need to figure out why your move to option is creating two copies of the new MP4 file. It shouldn't and I don't see any way that it could be duplicating the output file. The only thing I can think is maybe you have delete original disabled and you're counting that plus the new MP4 as two files. 



—

**Comment by JohnMaree** [comment]
Have figured out how to do it!!! I managed to create an apple script to add folder to iTunes and it works great, now I saved that script as an app for Python, with use of the extra_scripts option in sickbeard a config.ini file to call a script to launch that application. One problem is when I run it, it gives me the error "Unable to run extra_script: error 13 : Permission denied" :( 

The script to launch the app looks like this:

import os

os.system("/users/john_maree/sickbeard/extrascripts/add.app")



And the weird thing is if I test the script from the Python script editor thing (goto the option that says run), it works fine... Only gives me permission error when I make sickbeard do it through extra_scripts

I'm so close to solving this

**Comment by mdhiggins** [comment]
If you're on a Mac, the new post processing script feature can be used for adding processed files to iTunes. The iTunes.py script is included by default.
