### ISSUE TITLE
Couchpotato Main.py Issue

### ISSUE THREAD

**Issue by xpack90** [mdhiggins/sickbeard_mp4_automator#261]
I saw here that we are suppose to point line 11 in main.py file to the scripts location.
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/234

I installed sickbeard_mp4_automator to /opt/Automator and pointed line 11 to that location and this is the error I get 

ERROR[  couchpotato.core.loader] Can't import PostProcess: Traceback (most recent call last):
  File "/opt/CouchPotatoServer/couchpotato/core/loader.py", line 58, in run
    m = self.loadModule(module_name)
  File "/opt/CouchPotatoServer/couchpotato/core/loader.py", line 164, in loadModule
    return import_module(name)
  File "/opt/CouchPotatoServer/libs/importhelper/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/opt/couchpotato/custom_plugins/PostProcess/__init__.py", line 1, in <module>
    from .main import PostProcess
  File "/var/opt/couchpotato/custom_plugins/PostProcess/main.py", line 11
SyntaxError: Non-ASCII character '\xe2' in file /var/opt/couchpotato/custom_plugins/PostProcess/main.py on line 11, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by mdhiggins** [comment]
This appears to be because you have put a non-unicode character in the path on line 11 (where you're pointing to your script directory). Based on what you're telling me however, I don't think you actually did put any unicode characters since you only pointed to /opt/Automator. My guess is whatever way your text editor saved the file screwed things up.

What text editor did you use to mod the main.py file?

**Comment by xpack90** [comment]
I used the built in Notepad in OSX, but deleting and switching to textwrangler seemed to have fixed it. Thank you again. Never have seen a more active developer, great work and product!

**Comment by mdhiggins** [comment]
Thanks! Glad that was an easy fix. Enjoy
