### ISSUE TITLE
Issues with setup

### ISSUE THREAD

**Issue by hubdows** [mdhiggins/sickbeard_mp4_automator#282]
Hello,

I'm having a lot of trouble getting set up. Some parts of the readme.md don't make sense, and I am curious if you can clarify them? I'm only using sabnzbd, sickbeard and couchpotato, so my question will be around them.

MP4 Section
max-audio-channels - Should I be using this if I set ios-audio to false? Do you have guidance on recommended settings?
embed-subs - If a movie is in english, but has some foreign language subs will this setting add the full subs to the file? What is the best way to handle foreign language subs?
video-max-width - When should this be used?
ios-first-track-only - should this only be used if ios-audio is set to true?

Sick Beard Setup
web_root - if root is the setting do I need to supply '/'? If it is home, should it be '/home' or '/home/'?

Couch Potato Setup
renamer - Is that just the checkbox in CP that says 'rename downloaded movies'? It is unclear if it needs to be checked or not. Mine is unchecked. When I check it and set 'run every' to 0, do I also need to set 'force every' to 0? Are there any other settings which need to be change from the default?

sabnzbd
categories - Is anything required in the 'groups\indexer tags' field?

manual.py
Running: manual.py 'x:\movies\The Matrix (1999).mkv' results in :
Manual processor started.
Invalid interal subtitle codec srt, defaulting to 'mov_text'.
usage: manual.py [-h] [-i INPUT] [-c CONFIG] [-a] [-tv TVDBID] [-s SEASON]
                 [-e EPISODE] [-imdb IMDBID] [-tmdb TMDBID] [-nm] [-nc] [-nd]
                 [-nt] [-pr] [-cmp4]
manual.py: error: unrecognized arguments: Matrix (1999).mkv'

Changing the subtitle codec to mov_text results in:
Manual processor started.
usage: manual.py [-h] [-i INPUT] [-c CONFIG] [-a] [-tv TVDBID] [-s SEASON]
                 [-e EPISODE] [-imdb IMDBID] [-tmdb TMDBID] [-nm] [-nc] [-nd]
                 [-nt] [-pr] [-cmp4]
manual.py: error: unrecognized arguments: Matrix (1999).mkv'

I thought it might be the imdb switch, but I get the same from it.

c:\>manual.py -i 'x:\movies\The Matrix (1999).mkv'-imdb tt0133093
Manual processor started.
usage: manual.py [-h] [-i INPUT] [-c CONFIG] [-a] [-tv TVDBID] [-s SEASON]
                 [-e EPISODE] [-imdb IMDBID] [-tmdb TMDBID] [-nm] [-nc] [-nd]
                 [-nt] [-pr] [-cmp4]
manual.py: error: unrecognized arguments: Matrix (1999).mkv'-imdb tt0133093

Regards,
Keith

**Comment by hubdows** [comment]
I was able to get manual.py going, but still getting this message when using srt as the subtitle codec:
'Invalid interal subtitle codec srt, defaulting to 'mov_text'.'

Any ideas?

**Comment by mdhiggins** [comment]
Can you post your autoProcess.ini settings?

**Comment by mdhiggins** [comment]
Let me try and go through and address some of these questions as well:

- max-audio-channels is meant to be used independently of the iOS audio option. While it can be used with the option without issues, the reason that option is present is for people who have no interest in preserving surround sound audio and would rather just downsample all audio tracks to a set number of channels instead of replicating audio streams.
- embed-subs only refers to whether you want your subtitles in external files vs embedded in the mp4 container. Foreign language subs are handled by the two options `subtitle-language` and `subtitle-default-language`. You can refer to the readme for how these options behave.
- video-max-width: use if you wish to downsample content to a certain resolution
- ios-first-track-only is an option to ensure that only the first audio track present is given the ios-audio treatment. Some users requested this option so that they wouldn't get multiple stereo audio tracks if the source file had multiple languages or director commentary etc embedded, it simply makes the stereo audio track (the ios audio track) for whichever audio stream is first and not for the remaining tracks

- the web_root (and most of the Sickbeard options) are taken right from Sickbeard's config and just merged into autoProcess for convenience. Refer to Sickbeard's instructions for those, I didn't design/make those options.

- Renamer is  the renamer module in CouchPotato. If you're looking at Couch Potato, on the left hand nav bar its called "Renamer". Post downloader scripts (SAB/NZB/Torrents) will as part of their routine trigger a "renamer scan" manually so periodic refreshing isn't required. This is helpful because periodic checks can sometimes overlap with other processing and cause issues, so having them turned off helps avoid this. You can have them on if you desire but the scripts will trigger it manually when the downloads complete

-groups/indexer - nope

- Your subtitle codec error is because SRT isn't a valid subtitle codec for an embeded/internal subtitle. Only mov_text for MP4. SRT can be used if you don't want to embed and want external *.srt files.

As far as your command line arguments, I'm guessing you aren't super experienced with using the command line and that's why you're having some issues. You have to pay attention to what parameters are required and how they must be used, and multiple parameters need to separated by a space. This is universal across all command line applications. I'll correct the two problems you're having just as an example:

- `manual.py 'x:\movies\The Matrix (1999).mkv'` should be `manual.py -i 'x:\movies\The Matrix (1999).mkv'`
- `manual.py -i 'x:\movies\The Matrix (1999).mkv'-imdb tt0133093` should be `manual.py -i 'x:\movies\The Matrix (1999).mkv' -imdb tt0133093` (space was missing before the -imdb switch)


As I was writing this I've gone through the readme to add some additional clarification for a few of these points.

**Comment by hubdows** [comment]
Michael, thanks. No the issue with manual.py, was that I was trying to run
it through the python command line. :) I have been able to get the files to
process manually, and will take a look at your changes to the readme. I'm
still working through a couple issues with CP and SB, but I'm a lot closer
to sorting it now. Thank you so much for your work, you have a great
project here.

**Comment by mdhiggins** [comment]
Glad things are starting to work for you. Gonna close this issue for now. If you run into any specific problems feel free to reopen or create a new issue.
