### ISSUE TITLE
Unexpected Error Occurred

### ISSUE THREAD

**Issue by elit3ge** [mdhiggins/sickbeard_mp4_automator#283]
Was working perfectly until a recent update, now this is all I get.

This seems to only be when it's a mkv.

Reading video stream.
Video codec detected: h264
Pix Fmt: yuv420p
Reading audio streams.
Audio detected for stream #1: aac [eng].
Creating audio stream 0 from source stream 1.
An unexpected error occurred, processing of this file has failed
unsupported operand type(s) for /: 'NoneType' and 'int'

and when it processes a mp4 it seems to be adding (2) to the end of the videos.

**Comment by elit3ge** [comment]
and from SAB i'm getting.

Traceback (most recent call last):
  File "D:\mkvtomp4\trunk\SABPostProcess.py", line 58, in <module>
    output = converter.process(inputfile)
  File "D:\mkvtomp4\trunk\mkvtomp4.py", line 137, in process
    options = self.generateOptions(inputfile, original=original)
  File "D:\mkvtomp4\trunk\mkvtomp4.py", line 335, in generateOptions
    abitrate = a.bitrate/1000
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by mdhiggins** [comment]
Looks like the script is failing to detect your audio bitrate. Is this the same video file or is it happening to all of them? Have you made any changes to ffprobe? Also just post your autoprocess.ini file if you can

**Comment by elit3ge** [comment]
It was happening to all of them. No changes to ffprobe.exe only since the update of automator it happened. After trial and error, the only way I can get the script to run properly is by changing audio-channel-bitrate = 0 to audio-channel-bitrate ="0"

**Comment by mdhiggins** [comment]
Leave audio channel bitrate blank

**Comment by mdhiggins** [comment]
Now that I'm in front of my computer I can elaborate. Setting the bitrate to `"0"` with quotes actually makes it a string and invalidates the bitrate, so the script defaults to 256 per channel. If that behavior is fine for you, you can set it as 256 and be done with it. If you're attempting to mirror the source audio bitrate, (which can be dangerous because bitrates are not always equivalent across codecs, but that's a whole different discussion) then leave the bitrate as `0`.

What seems to be happening is for some reason ffprobe isn't passing the audio bitrate to the script and so its detected no bitrate and the value is being set to `None` which won't work. I went ahead and just pushed an update that will catch this problem and default to 256 per channel, the default audio bitrate setting for the script.

That being said, if you're consistently getting this error with every video, or after you update you're getting this lovely new warning: `Unable to determine audio bitrate from source stream [stream number], defaulting to 256 per channel.` then there's something wrong with FFPROBE and I would try replacing whatever build you're using.

**Comment by elit3ge** [comment]
Thanks for that.
