### ISSUE TITLE
TVDB episode Artwork instead of season artwork

### ISSUE THREAD

**Issue by c010rb1indusa** [mdhiggins/sickbeard_mp4_automator#302]
I would like an option for the script to use the episode artwork from the TVBD for the file's metadata rather than the season artwork. I know this might be a problem for automation because the episode artwork isn't always posted on TVDB right after an episode finishes airing, but it would be nice to have the option.

**Comment by mdhiggins** [comment]
Just added this feature with the latest commit, feel free to update and give it a test.

The `download-artwork` option has been modified now to accept the values `poster` or `thumbnail`. Set it to `thumbnail` and try processing some TV shows. This feature only applies to TV shows at this point cause it doesn't make much sense for movies.

Let me know if its working well or if you run into any issues otherwise go ahead and close this.
