### ISSUE TITLE
pip install deluge-client

### ISSUE THREAD

**Issue by ptowns188** [mdhiggins/sickbeard_mp4_automator#357]
can you elaberate more on pip install deluge-client please

i use deluge on an older version of your script and have the gvent pip package installed if i was to get the latest version of your script would i have to run pip install deluge-client also what happen when i install it? would the old deluge install still be needed 

thanks

**Comment by mdhiggins** [comment]
I'd be happy to explain.

I've been having problems with the latest version of deluge and the script communicating of the last several days so I did some investigating. Previously, the API that the script used to talk to Deluge (using the Deluge RPC) was provided by the `deluge` directory in the root of the script. That particular set of code hadn't been updated in 3 years. A new set of python code for talking to deluge has since been released and is now part of the PyPi/PIP software system, so, I simply updated the delugePostProcess.py script to take advantage of the newer version of the software, removed the old `deluge` folder from the script, and started using the `deluge-client` code base, which comes from pip.

So, your actual deluge install isn't touched, I think that may be where the confusion is coming from. The `deluge-client` pip package isn't replacing deluge, its just replacing the small bit of python code that was previously packaged into the script that was used to talk to deluge.

To update, all you need to do is:
1. `pip install deluge-client`
2. update sickbeard_mp4_automator from git
3. optionally delete the leftover empty `deluge` directory in the root of the script folder

And that's it. Hope that clarifies
