### ISSUE TITLE
(2) in filename (even when delete_original = True)

### ISSUE THREAD

**Issue by HazCod** [mdhiggins/sickbeard_mp4_automator#365]
Is it normal it leaves the reprocessed mp4 with a (2) ?

e.g. input: `Blackwater.mp4`

output: `Blackwater(2).mp4`

I think the problem here is the script assumes input filename is different from the output filename, which is not guaranteed. Possible solution is naming the output file with a random postfix and renaming afterwards. (only when delete_original is True)

```
[MP4]
ffmpeg = ffmpeg
ffprobe = ffprobe
output_directory =
copy_to =
move_to = (overridden)
output_extension = mp4
output_format = mp4
delete_original = True
relocate_moov = True
video-codec = h264,x264
video-bitrate =
video-max-width =
h264-max-level = 5.1
ios-audio = True
ios-first-track-only = False
max-audio-channels = 
audio-codec = ac3
audio-language = eng,nld
audio-default-language = eng
audio-channel-bitrate = 256
subtitle-codec = srt
subtitle-language = eng,nld
subtitle-default-language = nld
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = False
download-subs = True
embed-subs = False
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
pix-fmt =

```

**Comment by mdhiggins** [comment]
Currently this is the expected behavior. I agree its not ideal and I'll look into coming up with a different solution, at least in the setting of `delete-original=True`

**Comment by traxinv** [comment]
Would be great if in the last step (if delete-original=True) is set to rename the file and remove the (2) since the metadata tagging is done by sickbeard after the file has already moved to the destination folder. Alternatively, if you could at the metadata tagging to the SABPostProcess script that would also solve this problem. 

PS: Awesome app man!

**Comment by traxinv** [comment]
Actually, would it not in general be a better option to do the metadata tagging in the SABPostProcess script. Since after the file is moved by sickbeard the plex index is updated etc, while the metadata tagging is taking place. as a result i get "missing" in plex since the files name has already changed to (2).

**Comment by mdhiggins** [comment]
Can't add the metadata option to SAB because SAB is a dumb downloader (no offense to SAB) and isn't aware of the content it downloads. Same for all downloading clients. The media managers are the ones that know things like the TVDBID and episode information, and that's where the metadata is generated from. Guessing based on the filename, which would be the only option for SAB, isn't reliable for an automated process.

I do agree that a renaming option when using the convert-mp4 option that eliminates the (2) etc would be the most ideal option. I'll look into implementing this soon

**Comment by traxinv** [comment]
@mdhiggins yeah once i got into your code I realized why you needed to do that part on the sickbeard/sickrage side of things. I think if the (2) problem is sorted out it will not be a problem since the path will remain the same (even if the actual file changes).

**Comment by mstrelan** [comment]
How about instead of renaming the output file, rename the input file while it is being processed, eg add ".tmp" or something to the end. Then the output file is free to use the original filename.

**Comment by 0mni** [comment]
Until this issue is fixed, anyone who has a lot of files with the (2) in the file name can do the following:

Require Bash 4
```
shopt -s globstar
rename -v -n 's/\(2\)//' /TV-Shows/**
```
This will not actually make any changes, read the output, make sure everything is good, then remove the "-n" and rerun the same command to make actual changes.

**Comment by mdhiggins** [comment]
(2) issue should now be resolved. Original file will be renamed to a .original and deleted if the options are appropriately set. If for some reason renaming the original fails, it will fall back to the old renaming system.

**Comment by jjbrunton** [comment]
Sorry to open this back up, what are the expected options to prevent (2) from happening?

output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = True

**Comment by mdhiggins** [comment]
You don't need any combination of options now to avoid the (2) issue.
By default now the (2) naming scheme will only appear if there's an issue renaming the original source file.

**Comment by traxinv** [comment]
Works for me :)
