### ISSUE TITLE
Deluge script failing to execute

### ISSUE THREAD

**Issue by lwittwer** [mdhiggins/sickbeard_mp4_automator#371]
I am trying to get the automator running on a headless raspberry pi build and I cannot get deluge to execute the post process script at all. Running manual.py works and the delugePostProcess.py script can be run in terminal and it complains about not enough arguments but only when I specify python /path/to/delugePostProcess.py I built a script to just to point to delugePostProcess.py and feed it the arguments however deluge does not seem to like that either. The error I get out of deluge is:
[ERROR   ] 01:34:03 core:148 [execute] Execute script not found or not executable
[WARNING ] 01:34:04 core:132 [execute] command '/home/pi/sickbeard_mp4_automator/delugePostProcess.sh' failed with exit code 1
[WARNING ] 01:34:04 core:136 [execute] stderr: Upon execvpe /home/pi/sickbeard_mp4_automator/delugePostProcess.sh ['/home/pi/sickbeard_mp4_automator/delugePostProcess.sh', 'randomtorrentid', 'totallynotatvshow$
:Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 403, in _fork
    path, uid, gid, executable, args, environment)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/process.py", line 453, in _execChild
    os.execvpe(executable, args, environment)
  File "/usr/lib/python2.7/os.py", line 355, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 370, in _execvpe
    func(file, *argrest)
OSError: [Errno 8] Exec format error

This is the error when running the bash script:
2015-11-23 02:43:42 - delugePostProcess - INFO - Deluge post processing started.
2015-11-23 02:43:42 - readSettings - WARNING - Audio bitrate was invalid, defaulting to 256 per channel.
2015-11-23 02:43:42 - delugePostProcess - INFO - Successfully connected to Deluge
Traceback (most recent call last):
  File "/home/pi/sickbeard_mp4_automator/delugePostProcess.py", line 43, in <module>
    torrent_files = torrent_data['files']
KeyError: 'files'

I don't really know what else to try at this point.

**Comment by mdhiggins** [comment]
Looks like you're setting your path to .sh instead of .py

/home/pi/sickbeard_mp4_automator/delugePostProcess.sh

**Comment by mdhiggins** [comment]
Never mind just read your post carefully. I'll look into this more when I have some time.

**Comment by mdhiggins** [comment]
The `OSError: [Errno 8] Exec format error` error is one that is seen when the file that the script is trying to execute isn't being seen as a valid executable. Because the error message you're posting here is from the .sh script you tried to create, my initial guess is that the permissions for that file were incorrect and it didn't have executable permissions, or there's some other issue (maybe that popen here isn't use Shell=True). 

Could you post the log information for when you're attempting to have the script open the python file directly instead of the shell file?

I would also double check all your file permissions and make sure they have execute permissions and are also relaxed enough that the deluge daemon can access them.

**Comment by lwittwer** [comment]
Yep. All files were not executable and this was exactly why it was failing. Man I feel stupid
