### ISSUE TITLE
Support for multi episode files

### ISSUE THREAD

**Issue by tf2manu994** [mdhiggins/sickbeard_mp4_automator#459]
Ie a file with 2 eps in one.. It could grab subs for both and stack them next to each other. 

General file name would be

Show name - S01E01-E02 - episode 1 title - episode 2 title

**Comment by mdhiggins** [comment]
Subliminal doesn't support multi episode files as far as I know and there's no good mechanism via FFMPEG to stack/merge two subitlte files to achieve what you're looking for. Additionally subtitle timing would likely be off if you tried to merge two subtitle files together since subtitles need to be specifically timed for the release (not just the season/episode). If subliminal starts supporting them then this can be achieved by updating subliminal but until then this isn't something I'm gonna be able to add in a reliable fashion.

I personally avoid multiepisode files like the plague, they're the bane of a clean automated setup. Most release groups these days are avoiding them as well.
