### ISSUE TITLE
mkvtoMP4 script does not optimize for web placing the MOOV in the begining

### ISSUE THREAD

**Issue by medjai** [mdhiggins/sickbeard_mp4_automator#483]
looking at the logs of the conversion script it doesn't show that we are optimizing for web by moving the MOOV to the front. I believe you already do this though with mp4's that are inserted as the input file though.

Am I missing an option?

**Comment by medjai** [comment]
relocate_moov = True is already set on my autoProcess.ini

**Comment by mdhiggins** [comment]
By design. MOOV atom move occurs after tagging

**Comment by medjai** [comment]
but I do have tagfile = True as well and my most recently processed video shows on Plex and via ffprobe that the moov isn't at the begining

**Comment by mdhiggins** [comment]
Are you passing them through to some sort postConversion script or just a post downloader script?

**Comment by medjai** [comment]
Not at all

Sickbeard => SABnzbd with categorie TV which runs SABpostProcess.py => After processing Sickbeard does it's post processing of renaming and moving

Shouldn't this be the correct workflow?

**Comment by mdhiggins** [comment]
Does Sickbeard then run postConversion.py as the final step? Should be your extra_script for Sickbeard

**Comment by Mirabis** [comment]
Experienced the same, but manually changed a ffmpeg command to re-locate moov ... (searching now)

**Comment by medjai** [comment]
No Post Processing and no extra_scripts folder in my Sickbeard or sickbeard data

![sb post-processing](https://cloud.githubusercontent.com/assets/16169426/15451808/d34307b4-1fa3-11e6-8b34-e27d6de349e7.png)

**Comment by medjai** [comment]
Same behavior exists with Couch Potato it seems as well. all my movies also don't have MOOV in the beginning but what's weird enough is that when I process manually using "./manual -nm -a" It does move the MOOV even when the input file is an MKV

**Comment by mdhiggins** [comment]
I think both of you guys haven't actually set up the final step of the script which is where the moov move is executed (with manual.py being the exception). 

You need to open up your config.ini and setup postConversion.py so Sickbeard will run its final post processing steps after it has moved and renamed the files. Then tagging will occur. Then the MOOV atom move is performed. I intentionally avoid what @Mirabis has suggested because it created problems. It was actually implemented briefly about a year ago, but there were problems moving the MOOV atom before tagging took place, and if you do it as part of the initial conversion all that metadata hasn't been written yet, which is why its not part of the script and is done as one of the final steps.

As far as CP not doing it either, I should ask if you set up the post CouchPotato script either? If you don't set up the final post processing scripts then you'll definitely be missing functionality.
