### ISSUE TITLE
Request: Incorporate Filebot to rename folders & files during/after conversion

### ISSUE THREAD

**Issue by drazin** [mdhiggins/sickbeard_mp4_automator#489]
I would love to use this script as an all in one post processing script and the only thing it's missing (for me) is the renaming of files and folders as i still get things like 123.mp4 as an output.  

Is it possible to incorporate the Filebot command line script into this script?

**Comment by mdhiggins** [comment]
The script supports additional post processing scripts. See the readme

**Comment by drazin** [comment]
perfect!!! i'll check it out. Thanks for an amazing effort on this project!

**Comment by tac00** [comment]
@drazin did you figure out how you can handle the renaming with Filebot amc and then call the mp4a to convert?

**Comment by drazin** [comment]
@tac00 i have not used this software in a while as it created some compatibility issues with my current setup.  However i do think i used a NZBget re-namer script which executed after the conversion as a solution.

**Comment by tac00** [comment]
@drazin Okay. Im using Sonarr and Radarr as media managers and Deluge as my downloader for torrents and the delugePostprocess.py script works great for calling mp4a after Radarr/Sonarr adds new content to Deluge. But some torrents I download is compressed in RAR files and nor Mp4a or Radarr/Sonarr can handle compressed files.

But Filebot have the option of unraring compressed content and the Im interested in calling the mp4a  and let Filebot handle all the renaming and moving instead of Sonarr and Radarr doing the renaming etc.
