### ISSUE TITLE
Difference between using NzbGet script for Sonarr & postSonarr.py in Sonarr

### ISSUE THREAD

**Issue by Mirabis** [mdhiggins/sickbeard_mp4_automator#501]
Could you describe the difference in behavior?

I'm not sure if setting it in postSonarr allows it to convert to .mp4 after nzbget passes it to sonarr, or if the behavior stays the same. If the former, that would speed up the emptying of the queue I guess?

**Comment by mdhiggins** [comment]
postSonarr will convert if the file hasn't been converted by one of the other postscripts

Might speed things up depending on how your workflow is setup, I personally convert right after download before the file is passed back to Sonarr (from NZBGet)

postSonarr will handle tagging though, NZBGet will not since it has no knowledge of the metadata

**Comment by Mirabis** [comment]
Okay, thanks 

Will try moving it to Sonarr as the download queue moves faster than the processing :)
