### ISSUE TITLE
acd_cli upload

### ISSUE THREAD

**Issue by sowie2016** [mdhiggins/sickbeard_mp4_automator#542]
I have got this integrated with Couchpotato & Sickrage and it's working lovely... I just wondered if there was anyway to auto upload the converted folder to Amazon Cloud drive once the file has finished and deleted the original video file? (So the upload starts after each individual conversion)

I am really new to Python so I do apologise if this is simple to integrate but any help would be massively appreciated!!

Thanks in Advance

**Comment by mdhiggins** [comment]
Not integrated into the script at baseline, but the script does support
writing your own addons that do anything you want after conversion is
complete in an automated fashion.

See the "extra scripts" section of the readme

**Comment by enz1ey** [comment]
Sorry, I know this is closed, but I have a simple upload bash script for acdcli and then a python script to call it (because I don't know python lol). I put the python script in the post_process directory and set the option to true in autoProcess.ini, however it doesn't seem to run it at all. 

When this script is set up for use with SabNZBD, Sonarr, and CouchPotato, does it need set up in ALL of those apps as per the readme? Because when I did that, it appeared to be processing the video with ffmpeg both after downloading in SabNZBD and after being moved by Sonarr and Couchpotato. So I now just have the script set up in SabNZBD and not Sonarr/CP. 

Would that be why it's not running the scripts in the post_process directory? Or should it run those even if SabNZBD is the only app set up?
