### ISSUE TITLE
Feature Request: Notify on completion or failure

### ISSUE THREAD

**Issue by wjbeckett** [mdhiggins/sickbeard_mp4_automator#577]
It'd be great to have the script notify on successful/failed conversion to various services (Slack, pushover, pushbullet, etc).

This would add an extra layer of certainty that the file has been processed properly.

**Comment by meks007** [comment]
Hi,

I'm doing this differently. I have the conversion run in the background and trigger SickRage and CouchPotato as soon as a conversion is finished. SR and CP then have Pushbullet turned on as soon as they "downloaded" the file. (ie import the converted file in to their library).

If your setup works differently it's an easy thing to create a Pushbullet post_process plugin that utilizes the PB-API using simple JSON calls.

Granted having an autonomous PB interface to notify on fatal conversion errors that result in the output to be invalid would be a good thing, because that's the only time when SR/CP wouldn't notify as they don't see any files to import.

**Comment by mdhiggins** [comment]
Most of the media managers have this notification feature built in to them so reproducing it just for an extension script isn't too high on the priority list
Not sure where the various media managers are about reporting processing errors but this would be an ideal feature to implement in them since they handle more aspects that could be prone for failure
