### ISSUE TITLE
Sonarr converting AFTER move

### ISSUE THREAD

**Issue by lbinderup** [mdhiggins/sickbeard_mp4_automator#604]
My issue is as follows - I have SABNZbd set up to pass the files to sonarr (This part works). SABNZbd leaves the files on my Mac-mini's harddrive to (ideally) have the conversion happen locally. I had the impression that Sonarr would convert the file first and THEN move it to the Sonarr-library (which is networked). Instead, Sonarr picks up the file, adds it to library, and then starts converting it - which is bad since it's now being converted on a network drive resulting in poor speeds.

Is the only way to have the file converted first, by going "convert = True" in the SABNZbd part of autoProcess.ini - and won't this mess with tagging, since this only seems to happen during the PostSonarr phase?

**Comment by lbinderup** [comment]
I guess this would work fine if I could somehow get the Post-SABNZbd operation to actually tag my converted files - that would make their meta-data nice and neat for Sonarr, and no Post-sonarr would be needed.

**Comment by mdhiggins** [comment]
The SAB stuff isn't designed to tag because it would have to guess based on the file name which isn't reliable. You should enable the convert option to have the bulk of the work done before Sonarr and then just let Sonarr tag which is quick and takes only a few seconds and relatively no processing power.
