### ISSUE TITLE
Sonarr or Deluge doesn't delete after processing?

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#623]
So after processing and converting the file and moving it where it needs to be. Deluge nor Sonarr deletes the original files. Do I need to enable complete download handling in Sonarr for that? Also if I do that will it affect how NZBs are handled by Sonarr? I know in a certain part of the readme it say's to disable it?

any suggestions?

**Comment by justinglock40** [comment]
So after more careful review. It seems Sonarr remove the original stuff, but doesn't remove the folder that gets labeled "whateverfoldername{rarbg}-convert" Do I need to setup anything differently to get this stuff cleared after the converted file has been moved?

**Comment by niallobr** [comment]
I think it's a permissions issue with Deluge. I can see it doesn't give write access to the users group on downloaded files and there's a permissions error in the Couchpotato log when post-processing.

Apparently this can be fixed by adding UMASK = 0 somewhere in Deluge. There's a guide here:

https://forum.synology.com/enu/viewtopic.php?p=343410#p343410

I can't figure out how to make it work on my Synology. If anyone has any suggestions I'd appreciate it.

**Comment by niallobr** [comment]
@justinglock40 A quick update. 

I created a new Deluge instance inside a Docker container from linuxserver.io. Using this Linux build I was able to find the files in which you can specify the umask:

**/etc/services.d/deluged/run
/etc/services.d/deluge-web**

You can specify a umask 000 here (or something [more restrictive](https://www.cyberciti.biz/tips/understanding-linux-unix-umask-value-usage.html)) and it is now deleting the -convert folder for me. The original folder and video file still remains, I'm not 100% sure if this is intended or not.
