### ISSUE TITLE
Feature Request: Ability to set maximum framerate

### ISSUE THREAD

**Issue by rob51i03** [mdhiggins/sickbeard_mp4_automator#653]
Would it be possible to set a maximum framerate in autoProcess.ini? I'd like to ensure the video framerate doesn't exceed my Roku box's ability to process, and setting the h264 max level doesn't appear to influence the framerate that the file is re-encoded at?

**Comment by mdhiggins** [comment]
What video source are you using that you're exceeding the max number of frames on the roku?

**Comment by rob51i03** [comment]
Here's the media info from the Plex server after it's been transcoded by sickbeard_mp4_converter:
![plexmediainfo_1](https://cloud.githubusercontent.com/assets/25386198/22381637/60147ee6-e490-11e6-92ca-277d06a1c2cd.png)
![plexmediainfo_2](https://cloud.githubusercontent.com/assets/25386198/22381636/6013b682-e490-11e6-95ca-12e1ed977781.png)

Here's what I see in the Roku logs:
1/27/2017 03:39:28 INFO Choice media: 1080p, 6.3 Mbps container=mp4 videoCodec=h264 audioCodec=aac audioChannels=2 id=189682 part:0
1/27/2017 03:39:28 INFO Choice videoStream: H264
1/27/2017 03:39:28 INFO Choice audioStream: English (AAC-LC Stereo)
1/27/2017 03:39:28 INFO MDE: Frame rate is not supported for resolution: 1080@50.
1/27/2017 03:39:28 INFO MDE: MediaChoice: direct playable=false version=1080p, 6.3 Mbps container=mp4 videoCodec=h264 audioCodec=aac audioChannels=2 id=189682

Hoping this helps

**Comment by rob51i03** [comment]
To clarify context for my prior comment, the log is from the Roku Plex client (http://IP.OF.ROKU.BOX:8324/logs) while opening the stream content served by the Plex Server.

**Comment by mdhiggins** [comment]
I was more curious what download source you were using that was giving your 50fps videos

That’s a very rare occurrence.

I can look into adding framerate adjustment options but you’re better off just downloading standard FPS videos since you can get judder and other issues when downsampling the frame rate.

**Comment by mdhiggins** [comment]
I'm just surprised uploaders are bothering to upload 50fps video files since pretty much all TV content is ~24fps. Is this an issue you're having with every show? I would say your Sickrage presences look fine and shouldn't be having this issue. I'll look into adding an FPS limiting option though, shouldn't be too hard to implement

**Comment by rob51i03** [comment]
It's a recent issue and not widespread. I can live with it, but wouldn't it be great for my system to be smart enough to either filter this problem out before it's downloaded, or convert the problem away? That would at least reduce the "awwww Daaad!" moments in front of the TV a little!

If you could implement, I'd be delighted to see it :-)

**Comment by elit3ge** [comment]
I have noticed that one 4 of my downloads come as 25fps and end up being converted to 50fps.
