### ISSUE TITLE
Feautre Request: Progress bar in NZBGET

### ISSUE THREAD

**Issue by trippinshrumes** [mdhiggins/sickbeard_mp4_automator#670]
I'm sorry I'm not sure where I could put a possible new feature on here so I'll throw it here and let you decide what to do with it. 

I was recently batch processing a folder of mine with this, I noticed that there's a progress bar.

Would it be simple enough to provide the information to NZBget so that it's able to show the progress within it's gui when the post process script is running? 

Thanks

**Comment by mdhiggins** [comment]
As far as I know this isn't supported ini the NZBGet post script API

**Comment by mdcollins05** [comment]
What about adding a message every 5% or so which could be seen in the NZBGet log interface?

**Comment by mdhiggins** [comment]
Is there an API callback that allows us to talk to the progress bar? I had looked into it a while a go and couldn't find anything

If there's an API we could support it but I don't think NZBGet lets the scripts do it, its an NZBGet limitation as far as I know

**Comment by mdcollins05** [comment]
I can't find any documentation on setting the progress bar either.

From http://forum.nzbget.net/viewtopic.php?f=3&t=2009#p13449: "The progress or estimated time cannot be changed by the script. However the green status message is controlled by the script and you can put the pecentage there."

Could we go that route and just simply print out the percentage every so often so that it shows?
