### ISSUE TITLE
Feature Request: QBitTorrent integration

### ISSUE THREAD

**Issue by dalcon007** [mdhiggins/sickbeard_mp4_automator#684]
Is it possible to integrate QBitTorrent support?

**Comment by mdhiggins** [comment]
Unfortunately QBitTorrent doesn't pass enough command line parameters to the external programs to make this doable. 

The script relies heavily on a label/category system for directing downloads back to their source and QBitTorrent doesn't pass that information back. 

If they expand this in the future I'd be happy to add support.

**Comment by dalcon007** [comment]
Thanks for the information!

**Comment by haxcop** [comment]
:(

**Comment by tj1816** [comment]
It looks like qBittorrent has added a few parameters since the last time this was requested.  As of version 4.1.2 the parameters are:

Torrent Name
Category
Tags
Content Path
Root Path
Save Path
Number of Files
Torrent Size
Current Tracker
Info Hash

Are there any parameters that are missing for this to work?

**Comment by mdhiggins** [comment]
Got a link to the documentation for this?

**Comment by tj1816** [comment]
I was just going off the release notes https://www.qbittorrent.org/news.php 
I'll attach a picture of the settings:

![untitled](https://user-images.githubusercontent.com/15915222/44039434-11ac5d7e-9ee7-11e8-82d8-61ecfd5dc94a.png)

**Comment by mrzoops** [comment]
Any update on this? Is this being worked on/planned at all?
