### ISSUE TITLE
Only using 1 CPU thread

### ISSUE THREAD

**Issue by kaydaryl** [mdhiggins/sickbeard_mp4_automator#713]
After switching from a 2-thread CPU to an 8-thread CPU I noticed that only 1 thread was being used during conversion despite threads being tried @ "auto" (default), 0, and 8.  
ffmpeg version 3.2.4-1~16.04.york1

[autoProcess.zip](https://github.com/mdhiggins/sickbeard_mp4_automator/files/904545/autoProcess.zip)

**Comment by mdhiggins** [comment]
This is an FFMPEG issue and unrelated to the script. Many FFMPEG builds and encoding libraries do not include multi threading 

I would raise the issue on FFMPEG support channels

**Comment by kaydaryl** [comment]
Thank you for the quick reply!  
If I run "ffmpeg -i $input.mkv $output.mp4" I get the expected threads * 1.5 instances of ffmpeg (watching via htop). Is there a way to confirm an ffmpeg build that threads well with your wonderful script?

**Comment by mdhiggins** [comment]
It depends on many factors not just builds. I think any recent build should be fine but your encoder is also important in determining threading. 

You could try putting the threads option in your preopts and see if that makes any difference in performance (preopts = -threads, auto)

**Comment by kmr2319** [comment]
I have the same "problem". Via manual.py ffmpeg only uses 1 core. Running ffmpeg manually (with the simple syntax that @kaydaryl attempted), it uses 6-8 cores (I have 1*8 core CPU).

However, with this very simple syntax, I'm guessing that it's re-encoding the video stream:
```Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (dts (dca) -> aac (native))```

Which is why its making available use of all cores. When using the manual.py and my acceptable video codecs of [xh]264, so it just needs to convert audio and mux the streams.

I think this is going to be normal and likely the best performance you will receive if I'm understanding everything properly...

**Comment by mdhiggins** [comment]
Yeah, if you're copying a stream that has almost no CPU utilization. So then CPU usage is determined by the audio encoder only which may not be multi threaded.
