### ISSUE TITLE
[Question] Video-Bitrate setting

### ISSUE THREAD

**Issue by justinglock40** [mdhiggins/sickbeard_mp4_automator#719]
I know there is quality loss in the transcoding of any video/audio file. However, I was wondering how bad does the quality drop off from say a 30mbps blu-ray remux to something like 10-15mbps using that video bitrate option?

Also will this work with HEVC/H.265 encoded files and preserve things like BT2020 and 10bit?

**Comment by MReptile** [comment]
In my humble opinion everything above 7.5mbit can be considered HD!!
But in every movie there are short timespans where more bitrate is always needed. To make this possible people use CRF while encoding.

CRF 17 and 18 is visually lossless.
Use CRF 21 for good average HD output. If you plan on using your files for streaming. Probably Plex. Make sure to limit the Bitrate spikes. CRF can vary extremely. It takes whatever bitrate is necessary for the actual frame to preserve the given Quality (CRF 21).

to make a video perfectly playable with chromecast and everything use something like
-maxrate 10000k -bufsize 30000k
This makes sure the movie will be playable with an 11mbit connection, as the movie is in average 10mbit/s
ffmpeg will make sure that the average is checked every 3 seconds (bufsize is 3x maxrate)
Most players can handle 3 seconds fine.
If you want to be absolutely foolproof use -bufsize 20000k instead of 30000k
