### ISSUE TITLE
multiple CRF values for different bitrates

### ISSUE THREAD

**Issue by Filechaser** [mdhiggins/sickbeard_mp4_automator#724]
I already asked for -maxrate -bufsize. Thanks for your help again at this point.
High quality source files can be perfectly encoded by using crf 21 -maxrate 10000k -bufsize 30000k
Unfortunately if the sourcefile has already a low bitrate it needs to be processed with crf 17 to avoid any further quality loss.

I need to reencode even the lower bitrate files because of the bitrate spikes that even low average bitrate movies can have that were encoded with the crf option. 
Those videos stutter on a chromecast if not reencoded.

Could you add an option for if lower than X bitrate use crf YY instead of copy

BTW: Where is your donation button?

**Comment by justinglock40** [comment]
How do i set that in the script

**Comment by MReptile** [comment]
in the autoproccess ini you can add -maxrate and -bufsize at postopts=

**Comment by justinglock40** [comment]
So that would set the video to a constant bitrate to avoid the spikes? 

And do you also need to set video-bitrate and crf in autoProcess?

**Comment by MReptile** [comment]
Not really it is not a Constant Bitrate like CBR is. Let me explain this real quick.
Every device has a buffer. And at the beginning of a stream you are buffering let's say 3 seconds.
If your video is encoded CRF 21 without any options then Bitrate spikes can go wild. The first 3 seconds of the movie may need 4 mbit link speed and the next 3 seconds may need 20 mbit link speed. So the average is not quite high but your movie will buffer despite of the low average bitrate.  

maxrate specifies the average bitrate maximum. Bufsize makes sure that the average is met every X seconds. So the crf still works but it can only spike insainly high for the duration of the filled buffer. 
ConstantBitrate can never spike up to make the quality better. It is always the same for the duration of the video.
As long as there is enough buffered FFmpeg will use the crf as normal = really good quality. If there are too many spikes needed, ffmpeg will lower the quality to avoid buffering. 


Some settings for you to test with your chromecast...

-maxrate 1500k -bufsize 3000k (playable with 3mbit connection as the average of 1.5 mbit is met every 2 seconds.
-maxrate 4000k -bufsize 12000k (playable with 5.5mbit upload speed as the average of 4 mbit is met every 3 seconds for sure . Most devices can easily buffer 3 seconds. (720p)
-maxrate 8000k -bufsize 24000k (playable with 9.5 mbit upload speed as the average of 8 mbit is met every 3 seconds.  (normal Fullhd Quality)
-maxrate 10000k -bufsize 30000k (playable with 11.5 mbit upload speed as the average of 10mbit is met every 3 seconds. (really good FullHD Quality)

No more buffering when using plex :-)

Video Bitrate just needs to be set if you don't want to transcode videos below that bitrate and copy them (remuxing) However if you copy the streams bitrate spikes are not eliminated.

If CRF is set in autoproccess.ini it uses this instead of the bitrate.
It uses the bitrate only to decide whether the movie should be remuxed (copied without transcoding) or transcoded.

**Comment by justinglock40** [comment]
So for clarification does setting these in post-opts cause ffmpeg to reencode file? Or just remix with no settings?

**Comment by MReptile** [comment]
bitrate = 7500
crf = 21
postopts = -maxrate,10000k,-bufsize,30000k

This settings will copy every file to mp4 with a bitrate of 7500 or lower WITHOUT Transcoding or changing the spikes of the bitrates.
Every file with an average bitrate over 7500 will be transcoded with crf 21 and the bitrate spikes that crf 21 would generate are removed.

Clear enough?

**Comment by justinglock40** [comment]
Yea I see what you're saying that sucks. I was hoping I could remove spikes without re encoding

**Comment by MReptile** [comment]
Some files you encode will not even reach the 10mbit limit. If you encode a dvd CRF 21 will never reach 10mbit. So just the spikes will be removed. That's the wonderful thing about it. If the bitrate is not needed for some frames it saves harddisk-space while maintaining quality.

Those settings are good for content up to full hd: If you feed them a lower res file. It will automatically use a lower bitrate (crf 21 chooses the bitrate by itself. ) Crf 21 looks at the original resolution to do this.

MAXsize 1080p (4K will look like crap with this settings)

-maxrate 7000k -bufsize 21000k (playable with 8 mbit upload speed (low full hd)
-maxrate 8000k -bufsize 24000k (playable with 9.5 mbit upload speed  (normal Fullhd Quality)
-maxrate 10000k -bufsize 30000k (playable with 11.5 mbit upload speed (really good FullHD Quality)

IF you use the one below you have to set the resolution to 720p because full hd content will look like crap otherwise

-maxrate 4000k -bufsize 12000k (playable with 5mbit upload speed) (SET THE MAX RESOLUTION TO 720p FULL HD WILL LOOK LIKE CRAP)

Just choose what meets your needs!

**Comment by MReptile** [comment]
Unfortunately I have not figured out how to do that. And after hours of reading I think it will be impossible. FFmpeg has to analyze all the frames and simulate a buffer to choose the bitrate for each section correctly. I don't think this is possible without reencoding. 

I am going to ask some ffmpeg devs about this

**Comment by MReptile** [comment]
Despite the offtopic talk I would appreciate an answer from @mdhiggins. Most of us are using this for plex anyway. And at least this solves all the chromecast buffering issues. But as I said higher bitrate needs to be converted at crf 21 maxrate 8000 bufsize 24000
and lower bitrates at crf 18 or 17 with maxrate 8000 bufsize 24000

This way spikes in even lower bitrate files are properly removed to play at 9 mbit upload.
I don't want to reencode everything with crf 21. Files that are already at low bitrate would look terrible

**Comment by Mirabis** [comment]
Can't you add a if statement...

If vbr <= 8000:
   Apply the low nitrate logic here 
Else:
  Crf 21 stuff here ?


On phone so just pseudo :)

**Comment by MReptile** [comment]
I have to admit that I can't code.
😭 
But of course it should be something like that. I just wnated @mdhiggins to directly intecrate it to the autoprocess ini

**Comment by Mirabis** [comment]
Something like 
```
        # Fix max buffer to max 3 avg
        try:
            if not vcodec == 'copy':
                if vbr > 8000: #probably always, cuz bitrate check happens at 10mbits
                    options['postopts'].extend(['-maxrate', '10M','-bufsize', '30M'])
                elif vbr <= 4100:
                    options['video']['crf'] = 17
                    options['postopts'].extend(['-maxrate', '4.5M','-bufsize', '12M'])
                else:
                    options['video']['crf'] = 21
                    options['postopts'].extend(['-maxrate', '8M','-bufsize', '24M'])
                del options['video']['bitrate']
        except Exception as e:
                self.log.info("Error adding crf", exc_info=True)
```

**Comment by mdhiggins** [comment]
I know this post is very old but I'm trying to go through and clear out old issues and this one seemed like a feature that was doable in the more modern version of the script

ef90b9811034c2e9b9db945a9f6b0695d705dbc0

Adds a new video-crf-profiles option to autoProcess.ini where you can define various profile pairings for crf, maxrate, and bufsize based on the input file's bitrate
