### ISSUE TITLE
TVDB ID ignored on manual run

### ISSUE THREAD

**Issue by MichaelMallett** [mdhiggins/sickbeard_mp4_automator#741]
hen trying to specify a TVDB for a series it is ignored and gets the incorrect tags. If I enter this tag manually when it asks (ie without -a) it will retrieve the correct details

Command and output:

```
 python manual.py -i ~/Movies/ATLANTA -tv 313999 -a
Manual processor started.
/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Please install QTFastStart via PIP, relocate_moov will be disabled without this module.
64bit Python.
Processing file /Users/Mike/Movies/ATLANTA/ATLANTA - S01 E01 - The Big Bang (720p Web-DL).mp4
Matched movie title as: Atlanta 2007-05-09
```

**Comment by mdhiggins** [comment]
The TV show override works fine when guessit still detects the file as a TV show (even when it guesses the wrong TV show) but would fail if it thought the file was a movie

This is fixed now.

Additionally, the reason manual.py was failing to recognize this as a TV show is because you put it in a folder named "Movies". If you continue to run into guessing errors, set `fullpathguess` in autoprocess.ini to `False` and it will ignore the directory and only look at the file name and fix this problem 99% of time. But the command line parameter override should work now as well
