### ISSUE TITLE
Script is moving the downloaded file then converting

### ISSUE THREAD

**Issue by Smalfinn** [mdhiggins/sickbeard_mp4_automator#775]
Should the script not be converting the file and then moving it?

I am using default settings.

**Comment by raynotroy** [comment]
This behaviour is normal.  The script can be set to move the file to a directory manually using `move to = ` after the conversion.

**Comment by mdhiggins** [comment]
Actually I need more information, the behavior may be due to an incomplete installation
Did you set up all components of the script or just part of it? Without setting up the post downloader scripts (Sonarr/SAB/Torrent) you will not get conversion before moving file. If you do set those up then converting before the file is moved is easily possible

**Comment by Smalfinn** [comment]
I have setup settings for Sonarr, Radarr, Deluge, SABnzb and PLEX

**Comment by mdhiggins** [comment]
So then the Deluge and SAB scripts if set up properly and if conversion is enabled in their respective sections of autoProcess.ini should convert the files before they are moved to their final destination

Tagging however is done after moving

**Comment by Smalfinn** [comment]
autoProcess.ini: https://pastebin.com/ajc7dprv

Conversion was enabled on both but still moves the file and then converts

**Comment by Smalfinn** [comment]
Removed "output_directory =" from Deluge and SAB in autoProcess.ini and it now works the way I expected... weird

**Comment by Smalfinn** [comment]
But now re-converts the .mp4 when it is moved to it's final location?!

**Comment by mdhiggins** [comment]
Turn off convert-MP4 in options

**Comment by Smalfinn** [comment]
Perfect!
