### ISSUE TITLE
Can WMV be added as a codec?

### ISSUE THREAD

**Issue by morpheus2n2** [mdhiggins/sickbeard_mp4_automator#812]
Is it possible to use this to convert WMV, I found a load of old videos I want to convert and was hoping to use this instead of Handbrake (much prefer this script works so much better :) )

**Comment by mdhiggins** [comment]
WMV is usually a wrapper not a codec, any idea what codec?

**Comment by morpheus2n2** [comment]
Mediainfo says VC-1 (WMV3)

**Comment by mdhiggins** [comment]
So its not the codec that's preventing encoding, just the wrapper

I'm not gonna officially add WMV as supported since I suspect there will be bugs, but if you have a large library you wanna convert, open up the extensions.py file in the script root
And add 'wmv' to your `valid_input_extensions` array

`valid_input_extensions = ['mkv', 'avi', 'ts', 'mov', 'vob', 'mpg', 'mts', 'wmv']`

**Comment by morpheus2n2** [comment]
Awesome will do thank you :)
