### ISSUE TITLE
How do I use tx3g embedded subtitles in MP4 container?

### ISSUE THREAD

**Issue by astrodad** [mdhiggins/sickbeard_mp4_automator#823]
Looking at the documentation for autoProcess.ini, it says that mov_text is the only supported format for embedded subtitles. Why is this? According to a Plex developer, he recommended using tx3g for embedded to prevent transcoding when using subs.

**Comment by Collisionc** [comment]
mov_text is just a shorthand for 3GPP Timed Text subtitle, which is also known as tx3g. If you use mov_text, you are already doing that. 

Even if you do everything perfectly, there are some clients that will always force your plex server to transcode subtitles because the client doesn't support subtitle streams.

**Comment by mdhiggins** [comment]
This is the correct answer
