### ISSUE TITLE
uTorrent Post Process file not running

### ISSUE THREAD

**Issue by leafsfan525** [mdhiggins/sickbeard_mp4_automator#851]
I had everything working well before but I had to reset my system due to some issues and I lost my settings. Pretty sure I set it up the same way but the post process file does not seem to be launching when torrents finish. Here is what my script looks like:

"C:\ {{path}}\uTorrentPostProcess.py" "%L" "%T" "%D" "%K" "%F" "%I" "%N"

Any idea why this wouldn't be working?

**Comment by mdhiggins** [comment]
Does uTorrent execute anything? Try having it execute something that will be easy to see like notepad.exe first

If it does, then check your python environment settings or use a bat file to then point to the py file

**Comment by acosmichippo** [comment]
I'm also having this issue.  utorrent does successfully run "notepad.exe" when a torrent finishes, but not

`C:\Users\username\Documents\Programs\mp4 automator\uTorrentPostProcess.py %L %T %D %K %F %I %N`

or 

`"C:\Users\username\Documents\Programs\mp4 automator\uTorrentPostProcess.py" %L %T %D %K %F %I %N`

I would like to try the .bat idea, but I'm not sure what ti include in the bat.  How do I include the various parameters?

Thanks for any help!

**Comment by acosmichippo** [comment]
as a follow-up to the above, i think i figured out my issue.  i was able to confirm that the post process script was indeed running - the issue was it was erroring out at "no valid label".

so i saw in the source code that at that error check the script is looking for categories "sonarr" and I realized that the category set for utorrent inside my sonarr settings was still "tv-sonarr".  So hopefully that'll fix the issue now.
