### ISSUE TITLE
Sonarr Alpha

### ISSUE THREAD

**Issue by RemeJuan** [mdhiggins/sickbeard_mp4_automator#956]
Has this been tested with Sonarr Alpha as I cannot get it working, simply returns `Script exited with code: 1` which is definitely a very helpful error /s

Would the fact that I am using sonarr docker container perhaps be the cause?

Thanks

**Comment by Glynnryan** [comment]
I have the same issue and can't seem to figure out how to resolve this. I was having the same issue on V2 since after the last update (7 Feb 2019) though. So somehow I don't think the issue is isolated to V3

**Comment by Migz93** [comment]
I've used SMA with Sonarr V2 before no issue, trying it with Sonarr V3 I get the same error as OP.
SonarrV3 seems to need the script to return output correctly when tested otherwise the script can't be added which is what i assume is happening.

Sonarr says the following in the add script screen:

> Testing will execute the script with the EventType set to Test, ensure your script handles this correctly

**Comment by Glynnryan** [comment]
I ended up rolling back to V2, it still didn’t work so I deleted my MP4 Automator folder and set it up again. In the process I ran pip install requests and noticed that there was an update for the requests, so I updated it. Long story short, it appears to be working again. 

As reference, I followed this guide when configuring my MP4 Automator: https://www.reddit.com/r/PleX/comments/7gkdbl/sickbeard_mp4_automator_noob_how_to/

**Comment by Migz93** [comment]
@Glynnryan have you actually managed to get it to work with postSonarr.py? I have managed to get the script to add to Sonarr V3 but upon import it doesn't even attempt to convert so i feel like theres still an issue somewhere.

**Comment by Glynnryan** [comment]
The issue might be with Sonarr V3. I have gotten it to work on V2 (whatever the current build is as of last week). It doesn’t convert and move some tv shows at times. But that’s a separate issue I believe.

**Comment by Migz93** [comment]
Oh sorry, I didn't see that you said you went back to V2. I've actually managed to fix it in V3, it was related to Sonarr V3s new script test. I'll be doing a PR tonight/tomorrow with the fix.

**Comment by Glynnryan** [comment]
@Migz93 let me know if it works correctly? Maybe I’ll consider going back to V3 :-)

**Comment by Migz93** [comment]
@Glynnryan working succesfully, have it running for myself and it's converted 10+ of my downloads so far.
I've also created a pull request for it #986, so you can make the changes yourself if you want (Less then a handful of lines.)

**Comment by Glynnryan** [comment]
Nicely done @Migz93. I will setup a V3 test environment over the weekend before moving over completely.

**Comment by mdhiggins** [comment]
Reverted @Migz93 commit which just checked for test environment then immediately aborted the script before any code was executed on postSonarr.py

If the issue was that it needs a system exit code I added that to the end of the file, can try that for v3 but would update to delete that previous change before doing any testing since while it may get rid of the error it also exits the script immediately rendering it pointless

**Comment by Migz93** [comment]
It's meant to exit the script when the environment variable test is passed through as that var is only passed through when testing the script.
It's what Sonarr V3 requires, it needs to exit correctly when it passes through the test var.
When Sonarr V3 imports a file like normal it does't send the test var and therefore would carry on with the rest of the script.

I've tested your new commit and as expected the script fails to test and won't run, because it's not exiting when the test var is sent.

**Comment by mdhiggins** [comment]
But doesn't that prevent the script from doing anything?

**Comment by mdhiggins** [comment]
Tried another update, take a look, also updated radarr

**Comment by Migz93** [comment]
I assume you understand now but for the sake of any other's who stumble across here and don't, I'll explain how it works.

When you hit the test button, Sonarr sends the variable "sonarr_eventtype" with the result "Test".
My commit had the script check for this result, if true it exits (0) which is what Sonarr requires to test correctly and allow you to use the script. The script will not run but the test will return successful, as expected. If the script does not exit correctly (0) then Sonarr does not allow you to add it.

When you then import/upgrade a file Sonar sends the all the various media file variables but specifically it sends "sonarr_eventtype" with the result of "Download" (There may be other eventtypes for upgrade ect but i haven't checked that). In postSonarr.py this doesn't match to my sonarr_eventtype check, therefore it skips the test and carries on with the rest of your script as expected, converting the file etc.

I assume technically you don't need it to exit as a specific action to the "sonarrevent_type" test but i thought it would be cleaner to have it do that check first & then exit, as i'm not sure if putting it at the end will work. Your script may error/exit incorrectly before it gets to the end when being tested as it won't be passed through the required variables to perform the normal script tasks.

P.s can't see your new commit to postSonarr.py, or anything for postRadarr.py yet but i'll test again as soon as it's up. For Radarr atm the test they have just tests for the existence of the file so that should work regardless but yeah having it the same as Sonarr will stop any future headaches for the same issue.

**Comment by Migz93** [comment]
The two commits have shown now, tested them both and working as expected, thank you :).

**Comment by Maglorsmith** [comment]
Hello,

im still getting the original error but the logs are showing 
`19-5-16 08:32:44.9|Error|python.exe|Traceback (most recent call last):
19-5-16 08:32:44.9|Error|python.exe|  File "c:\scripts\postSonarr.py", line 9, in <module>
19-5-16 08:32:44.9|Error|python.exe|    from autoprocess import plex
19-5-16 08:32:44.9|Error|python.exe|ImportError: cannot import name 'plex' from 'autoprocess' (unknown location)
19-5-16 08:32:44.9|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Script exited with code: 1`

Been going round in circles for hours trying to figure this out. Any advice?
