### ISSUE TITLE
NZBGetPostProcess.py Doesn't tag created file or relocate the moov atom 

### ISSUE THREAD

**Issue by dhumphrey7** [mdhiggins/sickbeard_mp4_automator#990]
Just noticed this while going back through my library the file will be converted but the moov atom isn't relocated and the video doesn't get tagged.  Only reason I noticed I have the manual script working it's way through my movie folder and it keeps tagging already created mp4s and also relocating the moov atom.  Is there a way to add this into the post process script for NZBGET.

**Comment by mdhiggins** [comment]
Yep that's the normal and intended behavior ofr NZBGetPostProcess, its not meant to do those roles, only convert and hand back to Sonarr/Radarr/etc and those post scripts will do the tagging and MOOV atom move

**Comment by jennec** [comment]
Why is that behaviour different to NZBGet comapre to SABNZBD+ for example?

I recently moved to NZBGet and had noticed the Tagging of Movies and TV shows was not being done any longer where iwas when I used SABNZBD+.  

Now, I can get the ATOM moved during NZBGETPostProcessing by adding postopts = -movflags to the ini file I am using.  But I am wondering how to get tagging done autmatically before Plex see the files.  Any help is appreciated.

**Comment by mdhiggins** [comment]
SAB and NZB get do not support this, they are dumb downloaders, they simple hand the file back to Sonarr/Radarr/CP etc and the tagging and moov atom move is done by those programs respective post scripts.

**Comment by jennec** [comment]
I am not sure you quite understood what I was getting at.  

I am not using Sonarr or Radarr post scripts.  Thisis for the simple reason that too many conversions could happen simultaneously and take up too much CPU resources on my shared server.  So I use the downloads softwares PostProces scripts instead.  

Yes, you are right, the downloader themselves do not support converting, tagging, ATOM movements etc.  But its the different results when using the SABPostProcess script compared to the NBZGETPostProcess script that I was referring to.  

I used to use SABNZBD+ and your SABNZBD Post Processing script to convert my files.  This would convert and tag my files before sending back to Radarr or Sonarr.  When I moved to NZBGet and using the NZBGETProstProcessing script the files get converted (which mainly what I need), but they never get tagged before passing back to Sonarr or Radarr.

I am just wondering why? (is it due to file names being obfuscated in the downloader and therfore the script cannot guess the movie or expisode name?)

I am currently writing a couple of small scripts for Sonarr and Radarr to call the manual.py and pass movie or episode details to it so taggin will ocurr post convertion.

**Comment by mdhiggins** [comment]
I’m telling you that you are incorrect

There is no logic within the SABPostProcess script that performs the tagging or moov atom move before sending the files back to Radarr or Sonarr. I’m guessing what was happening was they were being sent back converted but not tagged then being tagged afterward which is the usual and expected behavior

You also shouldn’t need to be working on small scripts for Sonarr/Radarr to call manual.py, you are describing exactly what their own post processing scripts do already, I’m not sure why you would force manual.py to do this task when its less suited and more error prone when Radarr/Sonarr pass the metadata ID as environment variables

My best guess as to what is happening is since your switch to NZBGet something with your setup is wrong and maybe things aren’t being passed back like they are supposed to so that final step isn’t taking place
