### ISSUE TITLE
How to set 5.1 audio track as default?

### ISSUE THREAD

**Issue by MisterKurtz10** [mdhiggins/sickbeard_mp4_automator#995]
This seems more forum related than an issue, but I was unable to find a forum. My Plex client selects audio track one as the default, which is typically stereo even though my setup supports 5.1

Is there a way to set the 5.1 audio track (if one exists) as track one, or the default?

**Comment by Zeusy123** [comment]
would like to know this also

**Comment by mdhiggins** [comment]
Plex should automatically choose based on your client audio settings. My plex setup automatically switches to surround on my TVs that support it. 

Some info here

https://forums.plex.tv/t/default-audio-to-ac3-5-1/168742/8

**Comment by MisterKurtz10** [comment]
My Plex client is on an LG WebOS TV. It is connected optical to my 5.1 receiver. Plex doesn't select th 5.1 audio track as the default.

**Comment by Zeusy123** [comment]
Any update on this being possible???

**Comment by mdhiggins** [comment]
Support for this is officially added, the default audio track is now determined using some fancy analysis, see here
cbf707288603ab8ce20c2363a044c032dc8f1f8a

Summarized from the commit:
new method of handling setting the default audio track with new associated option
default audio track be determined by three factors, the defaults in the source material, the audio-default-language setting, and a new setting prefer-more-channels

If the options generated ends up with a single default channel from the source material, nothing will happen. If multiple defaults exists, (for example 2 tracks were created from a default because `ios-audio` is enabled) then the `prefer-more-channels` option will determine which remains default. If defaults are outside of your prefererd language they will be wiped and your primary language will be set to default
